import test from 'node:test';
import assert from 'node:assert/strict';
import https from 'node:https';
import {EventEmitter} from 'node:events';
import {parseDouyinShare,resolveDouyinShare,requestDouyinShareHeaders} from '../src/douyin-share.mjs';
const share='https://v.douyin.com/AbCd123/';
const account='https://www.douyin.com/user/MS4wLjABAAAA_SYNTHETIC';
const video='https://www.douyin.com/video/7448118827402972455';
const publicLookup=async()=>[{address:'8.8.8.8',family:4}];
test('share-text parsing is pure, unique and removes only tracking from a valid short URL',t=>{let requests=0;t.mock.method(https,'get',()=>{requests++;throw Error('no network allowed');});assert.deepEqual(parseDouyinShare('复制打开抖音，看看这个账号 '+share+'?from=share 。'),{kind:'douyin-share',platform:'Douyin',url:share});assert.equal(parseDouyinShare(share+' '+share+'?a=b').url,share);assert.throws(()=>parseDouyinShare(share+' https://v.douyin.com/Other123/'),e=>e.code==='DOUYIN_SHARE_AMBIGUOUS');for(const input of ['http://v.douyin.com/AbCd123/','https://v.douyin.com.evil.example/AbCd123/','https://name:pass@v.douyin.com/AbCd123/','https://v.douyin.com:1234/AbCd123/','https://v.douyin.com/AbCd123/extra',account,'v.douyin.com/AbCd123/'])assert.equal(parseDouyinShare(input),null);assert.equal(requests,0);});
test('account and video redirects return canonical IDs after verifying final public DNS',async()=>{for(const target of [account+'?track=1',video+'?from=share']){const calls=[],lookups=[];const result=await resolveDouyinShare(share,{lookup:async(host,options)=>{lookups.push({host,options});return publicLookup();},request:async(url,options)=>{calls.push({url,options});return {status:302,location:target};}});assert.equal(calls.length,1);assert.equal(calls[0].url,share);assert.deepEqual(calls[0].options.addresses,[{address:'8.8.8.8',family:4}]);assert(calls[0].options.signal instanceof AbortSignal);assert.equal(calls[0].options.headers,undefined);assert.deepEqual(lookups.map(x=>x.host),['v.douyin.com','www.douyin.com']);assert(lookups.every(x=>x.options.all===true));assert.equal(result.sourceShareUrl,share);assert.equal(result.redirectCount,1);if(target.includes('/user/')){assert.equal(result.kind,'account');assert.equal(result.secUid,'MS4wLjABAAAA_SYNTHETIC');assert.equal(result.username,result.secUid);assert.equal(result.url,account);}else{assert.equal(result.kind,'video');assert.equal(result.videoId,'7448118827402972455');assert.equal(result.url,video);}}});
test('at most three header-only hops allow relative redirects and stop loops or a fourth hop',async()=>{let calls=0;const request=async url=>{calls++;return {status:302,location:calls===1?'https://www.iesdouyin.com/hop':calls===2?'https://v.douyin.com/Next123/':video};};assert.equal((await resolveDouyinShare(share,{lookup:publicLookup,request})).redirectCount,3);assert.equal(calls,3);calls=0;await assert.rejects(resolveDouyinShare(share,{lookup:publicLookup,request:async()=>({status:302,location:'/Next'+(++calls)+'/'})}),e=>e.code==='DOUYIN_SHARE_LIMIT');assert.equal(calls,3);calls=0;await assert.rejects(resolveDouyinShare(share,{lookup:publicLookup,request:async()=>{calls++;return {status:301,location:share};}}),e=>e.code==='DOUYIN_SHARE_LIMIT');assert.equal(calls,1);});
test('credentialed, non-HTTPS, unknown and internal redirects never make a second request',async()=>{for(const location of ['http://www.douyin.com/user/MS4wLjABAAAA_SYNTHETIC','https://name:pass@www.douyin.com/user/MS4wLjABAAAA_SYNTHETIC','https://www.douyin.com:1234/user/MS4wLjABAAAA_SYNTHETIC','https://www.douyin.com.evil.example/user/SECRET','http://127.0.0.1/private','file:///etc/hosts','https://attacker.example']){let calls=0,lookups=0;await assert.rejects(resolveDouyinShare(share,{lookup:async()=>{lookups++;return publicLookup();},request:async()=>{calls++;return {status:302,location};}}),e=>e.code==='DOUYIN_SHARE_HOST'&&!e.message.includes('SECRET'));assert.equal(calls,1);assert.equal(lookups,1);}});
test('all resolved addresses including final canonical host must be public',async()=>{for(const address of ['127.0.0.1','10.0.0.1','100.64.1.1','169.254.169.254','172.16.0.1','192.168.1.1','192.0.2.1','198.51.100.1','203.0.113.1','224.0.0.1','::1','::ffff:127.0.0.1','fe80::1','2001:db8::1','2002:7f00:1::']){let calls=0;await assert.rejects(resolveDouyinShare(share,{lookup:async()=>[{address,family:address.includes(':')?6:4}],request:async()=>{calls++;return {status:302,location:video};}}),e=>e.code==='DOUYIN_SHARE_DNS');assert.equal(calls,0);}let calls=0;await assert.rejects(resolveDouyinShare(share,{lookup:async host=>host==='v.douyin.com'?publicLookup():[{address:'8.8.8.8',family:4},{address:'127.0.0.1',family:4}],request:async()=>{calls++;return {status:302,location:video};}}),e=>e.code==='DOUYIN_SHARE_DNS');assert.equal(calls,1);});
test('HTML or JavaScript redirects are not read and give a concrete full-link instruction',async()=>{for(const response of [{status:200,location:null},{status:302,location:''}]){let calls=0;await assert.rejects(resolveDouyinShare(share,{lookup:publicLookup,request:async()=>{calls++;return {...response,body:'<script>location="https://attacker.example"</script>'};}}),e=>e.code==='DOUYIN_SHARE_PAGE'&&e.message.includes('完整')&&e.message.includes('/video/'));assert.equal(calls,1);}await assert.rejects(resolveDouyinShare(share,{lookup:publicLookup,request:async()=>({status:302,location:'https://www.douyin.com/note/7448118827402972455'})}),e=>e.code==='DOUYIN_SHARE_IMAGE');});
test('one bounded timeout covers DNS and requests, with no retry or provider fallback',async()=>{for(const during of ['dns','request']){let calls=0;await assert.rejects(resolveDouyinShare(share,{timeoutMs:10,lookup:during==='dns'?async()=>new Promise(()=>{}):publicLookup,request:async()=>{calls++;return new Promise(()=>{});}}),e=>e.code==='DOUYIN_SHARE_TIMEOUT');assert.equal(calls,during==='dns'?0:1);}let calls=0;await assert.rejects(resolveDouyinShare(share,{lookup:publicLookup,request:async()=>{calls++;throw Error('secret-cookie /private/path');}}),e=>e.code==='DOUYIN_SHARE_NETWORK'&&!e.message.includes('secret'));assert.equal(calls,1);});
test('native transport pins DNS, omits credentials and destroys response at headers',async t=>{let captured,destroyed=0;t.mock.method(https,'get',(url,options,onResponse)=>{captured={url:url.href,options};const req=new EventEmitter();queueMicrotask(()=>onResponse({statusCode:302,headers:{location:account,'set-cookie':'never-return-this'},destroy(){destroyed++;},on(){throw Error('must not read a response body');}}));return req;});const result=await requestDouyinShareHeaders(share,{addresses:[{address:'8.8.8.8',family:4}],signal:new AbortController().signal});assert.deepEqual(result,{status:302,location:account});assert.equal(destroyed,1);assert.equal(captured.url,share);assert.equal(captured.options.agent,false);assert.deepEqual(Object.keys(captured.options.headers).sort(),['accept','user-agent']);let pinned;captured.options.lookup('v.douyin.com',{all:true},(error,value)=>{assert.equal(error,null);pinned=value;});assert.deepEqual(pinned,[{address:'8.8.8.8',family:4}]);assert(!JSON.stringify(result).includes('never-return'));await assert.rejects(requestDouyinShareHeaders(share,{addresses:[{address:'127.0.0.1',family:4}]}),e=>e.code==='DOUYIN_SHARE_DNS');});

test('documented iesdouyin video and strict account paths normalize without loading an HTML page',async()=>{for(const target of ['https://www.iesdouyin.com/share/video/7448118827402972455/?region=CN','https://www.iesdouyin.com/share/user/MS4wLjABAAAA_SYNTHETIC/?from=share','https://iesdouyin.com/share/video/7448118827402972455']){let calls=0;const result=await resolveDouyinShare(share,{lookup:publicLookup,request:async()=>{calls++;return{status:302,location:target};}});assert.equal(calls,1);assert.equal(result.url,target.includes('/user/')?account:video);assert.equal(result.redirectCount,1);}for(const target of ['https://www.iesdouyin.com/share/user/7448118827402972455','https://www.iesdouyin.com/share/user/12345','https://www.iesdouyin.com/share/video/not-an-id','https://www.iesdouyin.com/share/user/MS4wLjABAAAA_SYNTHETIC/extra','https://www.iesdouyin.com/share/unknown/7448118827402972455']){let calls=0;await assert.rejects(resolveDouyinShare(share,{lookup:publicLookup,request:async()=>++calls===1?{status:302,location:target}:{status:200}}),e=>e.code==='DOUYIN_SHARE_PAGE');assert.equal(calls,2);}await assert.rejects(resolveDouyinShare(share,{lookup:publicLookup,request:async()=>({status:302,location:'https://www.iesdouyin.com/share/note/7448118827402972455'})}),e=>e.code==='DOUYIN_SHARE_IMAGE');});
