import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mountHistoryLibrary,historyDisplayTitle} from '../src/history-ui.mjs';
const require=createRequire(import.meta.url);
const {parseHTML}=require(process.env.DOM_TEST_MODULE||'linkedom');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const base=(id='one',extra={})=>({id,url:`https://www.instagram.com/reel/${id}/`,account:{username:'sample',url:'https://www.instagram.com/sample/'},title:'合成参考 '+id,notes:'',tags:[],reviewed:false,favorite:false,hidden:false,trashedAt:null,createdAt:'2026-10-10T00:00:00Z',collectedAt:'2026-10-10T00:00:00Z',reportRefs:[],mediaAvailable:false,status:{metadata:'collected',download:'missing',analysis:'pending'},feedback:[],...extra});
function harness(rows=[base()],options={}){
 const {window,document}=parseHTML('<div id="root"></div>'),root=document.querySelector('#root'),calls=[];let records=structuredClone(rows),topics=structuredClone(options.topics||[{id:'sample',title:'日常参考',kind:'brand',automatic:true,recordIds:rows.map(r=>r.id),updatedAt:'2026-10-10T00:00:00Z'}]);
 const load=async({view,q})=>{const visible=records.filter(r=>view==='trash'?r.trashedAt:view==='hidden'?r.hidden&&!r.trashedAt:!r.hidden&&!r.trashedAt).filter(r=>!q||[r.title,r.displayTitleZh,r.notes,r.account?.username,...r.tags].join(' ').includes(q));return {records:visible,topics:topics.map(t=>({...t,recordIds:t.recordIds.filter(id=>visible.some(r=>r.id===id))})).filter(t=>t.recordIds.length||!t.automatic),counts:{active:records.filter(r=>!r.hidden&&!r.trashedAt).length,hidden:records.filter(r=>r.hidden&&!r.trashedAt).length,trash:records.filter(r=>r.trashedAt).length},reviews:options.reviews||[],revision:1};};
 const mutate=async p=>{calls.push(p);if(p.action==='create-topic'){const topic={id:'new-topic',title:p.title,kind:p.kind,automatic:false,recordIds:[]};topics.push(topic);return {topic};}if(p.action==='rename-topic'){const topic=topics.find(t=>t.id===p.topicId);topic.title=p.title;return {topic};}if(p.action==='move-topic'){for(const t of topics)t.recordIds=t.recordIds.filter(id=>!p.ids.includes(id));topics.find(t=>t.id===p.topicId).recordIds.push(...p.ids);return {records};}for(const r of records.filter(r=>p.ids?.includes(r.id))){if(p.action==='hide')r.hidden=true;if(p.action==='unhide')r.hidden=false;if(p.action==='trash')r.trashedAt='2026-10-10T01:00:00Z';if(p.action==='restore')r.trashedAt=null;if(['reviewed','favorite'].includes(p.action))r[p.action]=p.value;if(p.action==='edit')Object.assign(r,{displayTitleZh:p.displayTitleZh,notes:p.notes,tags:p.tags});if(p.action==='feedback'){const id='attempt-'+r.feedback.length;if(p.correctionOf){const old=r.feedback.find(f=>f.attemptId===p.correctionOf);if(old)old.supersededBy=id;}r.feedback.push({...p,attemptId:id,createdAt:'2026-10-10T01:00:00Z',evidence:p.evidence?{description:p.evidence}:null});}}return {records,revision:2};};
 const dispose=mountHistoryLibrary(root,{load,mutate,...options});
 const click=async selector=>{const el=root.querySelector(selector);assert(el,`Missing ${selector}`);el.dispatchEvent(new window.Event('click',{bubbles:true}));await tick();};
 const submit=async name=>{const el=root.querySelector(`[data-hl-form="${name}"]`);assert(el,`Missing form ${name}`);el.dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));await tick();};
 const select=(selector,value=true)=>{const el=root.querySelector(selector);assert(el);el.checked=value;el.dispatchEvent(new window.Event('change',{bubbles:true}));};
 const openTopic=async(id='sample')=>click(`[data-hl-action="topic"][data-id="${id}"]`),openRecord=async(id='one',tab='overview')=>{await click(`[data-hl-action="record"][data-id="${id}"]`);if(tab!=='overview')await click(`[data-hl-action="detail-tab"][data-id="${tab}"]`);};
 return {root,window,dispose,click,submit,select,openTopic,openRecord,calls,load,mutate,records:()=>records};
}
test('history starts with topic cards, opens video detail, searches, saves and reopens',async()=>{
 let app=harness([base(),base('two',{mediaAvailable:true,status:{download:'available',analysis:'available'},reportRefs:[{runId:'sample-run',videoId:'v1'}]})]);await tick();assert.equal(app.root.querySelectorAll('[data-record]').length,0);assert.equal(app.root.querySelectorAll('[data-topic]').length,1);assert(app.root.textContent.includes('已拆解'));assert(app.root.textContent.includes('每周一 09:00'));await app.openTopic();assert(app.root.textContent.includes('原片待下载'));assert(app.root.textContent.includes('拆解已归档'));assert(!app.root.querySelector('[data-hl-action="edit"]'));await app.openRecord('one','manage');await app.click('[data-hl-action="edit"][data-id="one"]');app.root.querySelector('[data-hl-field="title"]').value='值得复用的开头';app.root.querySelector('[data-hl-field="notes"]').value='首镜留长一点';app.root.querySelector('[data-hl-field="tags"]').value='开头，质感,开头';await app.submit('edit');assert.deepEqual(app.calls[0].tags,['开头','质感']);assert.equal(app.calls[0].displayTitleZh,'值得复用的开头');assert.equal(app.records()[0].title,'合成参考 one');const rows=app.records();app.dispose();app=harness(rows);await tick();app.root.querySelector('[data-hl-field="query"]').value='质感';await app.submit('search');assert(app.root.textContent.includes('匹配 1 条视频'));assert.equal(app.root.querySelectorAll('[data-record]').length,0);await app.openTopic();assert.equal(app.root.querySelectorAll('[data-record]').length,1);assert(app.root.textContent.includes('值得复用的开头'));app.dispose();
});
test('hide and trash require confirmation, remain recoverable, and do not remove media',async()=>{
 const app=harness([base('one',{mediaAvailable:true})]);await tick();await app.openTopic();await app.openRecord('one','manage');await app.click('[data-hl-action="hide"][data-id="one"]');assert.equal(app.calls.length,0);assert(app.root.textContent.includes('隐藏不是密码保护'));await app.click('[data-hl-action="confirm"]');assert.equal(app.root.querySelectorAll('[data-record]').length,0);await app.click('[data-hl-action="view"][data-id="hidden"]');await app.openTopic();await app.openRecord('one','manage');await app.click('[data-hl-action="unhide"][data-id="one"]');await app.click('[data-hl-action="view"][data-id="active"]');await app.openTopic();await app.openRecord('one','manage');await app.click('[data-hl-action="trash"][data-id="one"]');await app.click('[data-hl-action="confirm"]');await app.click('[data-hl-action="view"][data-id="trash"]');await app.openTopic();await app.openRecord('one','manage');await app.click('[data-hl-action="restore"][data-id="one"]');await app.click('[data-hl-action="view"][data-id="active"]');await app.openTopic();assert(app.root.querySelector('[data-record="one"]'));assert(app.records()[0].mediaAvailable);assert.deepEqual(app.calls.map(x=>x.action),['hide','unhide','trash','restore']);app.dispose();
});
test('batch read and favorite actions only affect the current topic and filter',async()=>{
 const app=harness([base('one'),base('two'),base('elsewhere')],{topics:[{id:'sample',title:'当前专题',recordIds:['one','two']},{id:'other',title:'另一专题',recordIds:['elsewhere']}]});await tick();await app.openTopic();app.select('[data-hl-all]');await app.click('[data-hl-action="batch:reviewed"]');assert(app.records().slice(0,2).every(r=>r.reviewed));assert(!app.records()[2].reviewed);await app.click('[data-hl-action="filter"][data-id="unread"]');assert.equal(app.root.querySelectorAll('[data-record]').length,0);await app.click('[data-hl-action="filter"][data-id="all"]');app.select('[data-hl-select="one"]');await app.click('[data-hl-action="batch:favorite"]');await app.click('[data-hl-action="filter"][data-id="favorite"]');assert.equal(app.root.querySelectorAll('[data-record]').length,1);assert.equal(app.calls[0].value,true);assert.deepEqual(app.calls[0].ids,['one','two']);app.dispose();
});
test('success feedback requires rationale, stays self-report, correction preserves prior attempts',async()=>{
 const app=harness();await tick();await app.openTopic();await app.openRecord('one','manage');await app.click('[data-hl-action="feedback"][data-id="one"]');for(const el of app.root.querySelectorAll('input[name="hl-outcome"]')){if(el.value==='success')el.setAttribute('checked','');else el.removeAttribute('checked');}await app.submit('feedback');assert.equal(app.calls.length,0);assert(app.root.textContent.includes('请填写你判断成功的依据'));app.root.querySelector('[data-hl-field="note"]').value='我看过外部成片，开头和节奏达到目标';app.root.querySelector('[data-hl-field="evidence"]').value='成片-v1.mp4，待复核';await app.submit('feedback');assert.equal(app.calls[0].outcome,'success');assert(app.root.textContent.includes('自评成功 · 证据待核验'));assert(!app.root.textContent.includes('[object Object]'));await app.click('[data-hl-action="correct-feedback"]');app.root.querySelector('[data-hl-field="note"]').value='更正：结尾还需要缩短';for(const el of app.root.querySelectorAll('input[name="hl-outcome"]')){if(el.value==='needs-improvement')el.setAttribute('checked','');else el.removeAttribute('checked');}await app.submit('feedback');assert.equal(app.calls[1].correctionOf,'attempt-0');assert.equal(app.records()[0].feedback.length,2);assert(app.root.textContent.includes('已被后续记录更正'));app.dispose();
});
test('source, notes, feedback and review are escaped and restricted reviews do not expose content',async()=>{
 const app=harness([base('one',{title:'<img onerror=attack()>',notes:'<script>attack()</script>',url:'javascript:attack()',feedback:[{attemptId:'old',outcome:'success',note:'<svg/onload=attack()>',evidence:{description:'<img src=x>'}}]})],{reviews:[{id:'safe',title:'<b>周复盘</b>',summary:'<img src=x>'},{id:'secret',restricted:true,title:'hidden secret title',summary:'hidden secret body'}],loadReview:async()=>({title:'复盘',markdown:'<script>attack()</script>\n证据不足'})});await tick();assert.equal(app.root.querySelectorAll('img,script,svg').length,0);assert(!app.root.textContent.includes('hidden secret'));assert(!app.root.querySelector('[data-hl-action="review"][data-id="secret"]'));await app.click('[data-hl-action="review"][data-id="safe"]');assert(app.root.querySelector('pre').textContent.includes('<script>attack()</script>'));assert.equal(app.root.querySelectorAll('script').length,0);await app.click('[data-hl-action="back"]');await app.openTopic();await app.openRecord();assert(!app.root.querySelector('a[href^="javascript:"]'));assert.equal(app.root.querySelectorAll('img,script,svg').length,0);await app.click('[data-hl-action="detail-tab"][data-id="manage"]');assert.equal(app.root.querySelectorAll('img,script,svg').length,0);app.dispose();
});
test('archived report opens only current video and related styles using existing data callbacks',async()=>{
 let reportCalls=0,styleCalls=[];const sample={runId:'test-run',title:'合成报告',summary:'合成数据',methodLabel:'无真实模型调用',videos:[{id:'v1',title:'当前视频',file:'v1.mp4',duration:4,shots:[]},{id:'v2',title:'其他视频秘密',file:'v2.mp4',duration:8}],styles:[{id:'test-style',name:'当前形式',reason:'测试',fixedRules:[],variableSlots:[],timeline:[],evidence:[{videoId:'v1',time:'0-1',observation:'当前视频证据'}],requiredAssets:[],fitCaveat:'测试'},{id:'global',name:'账号总建议不可混入',evidence:[]}],totalDuration:12,limitations:[]};
 const app=harness([base('one',{reportRefs:[{runId:'test-run',videoId:'v1'}],status:{analysis:'available'}})],{loadReport:async(r,ref)=>{reportCalls++;assert.equal(ref.runId,'test-run');return {report:sample};},saveStyle:async(...args)=>styleCalls.push(args)});await tick();await app.openTopic();await app.openRecord('one','analysis');await app.click('[data-hl-action="report"]');assert.equal(reportCalls,1);assert(app.root.textContent.includes('当前视频'));assert(!app.root.textContent.includes('其他视频秘密'));assert(!app.root.textContent.includes('账号总建议不可混入'));await app.click('[data-act="pp-save:test-style"]');assert.deepEqual(styleCalls,[['test-run','test-style']]);await app.click('[data-hl-action="back"]');assert(app.root.querySelector('[data-record="one"]'));app.dispose();
});
test('failed writes show error and retain form, retry does not claim saved',async()=>{
 const app=harness(undefined,{mutate:async()=>{throw new Error('合成磁盘写入失败');}});await tick();await app.openTopic();await app.openRecord('one','manage');await app.click('[data-hl-action="edit"][data-id="one"]');app.root.querySelector('[data-hl-field="title"]').value='保持输入';await app.submit('edit');assert(app.root.querySelector('[role="alert"]').textContent.includes('合成磁盘写入失败'));assert.equal(app.root.querySelector('[data-hl-field="title"]').value,'保持输入');assert(!app.root.textContent.includes('名称、备注和标签已保存'));app.dispose();
});
test('dispose removes listeners and ignores pending load result',async()=>{
 let resolve,loads=0;const {window,document}=parseHTML('<div id="root"></div>'),root=document.querySelector('#root');const dispose=mountHistoryLibrary(root,{load:()=>{loads++;return new Promise(r=>resolve=r);}});assert(root.textContent.includes('正在打开'));dispose();resolve({records:[base()],reviews:[],counts:{}});await tick();assert.equal(root.innerHTML,'');root.innerHTML='<button data-hl-action="reload">Reload</button>';root.querySelector('button').dispatchEvent(new window.Event('click',{bubbles:true}));await tick();assert.equal(loads,1);
});
test('imported analysis reopens as unverified, with safe readable sections',async()=>{
 let requested='';const app=harness([base('one',{importedReportIds:['import-1']})],{loadImportedReport:async id=>{requested=id;return {report:{source:'外部Agent',analyzedAt:'2026-10-10T00:00:00Z',types:[{type:'<img src=x>',reason:'可核对的建议',tone:'灰绿',rhythm:'短镜头',hook:'直接展示',subtitles:'少字',requiredAssets:['特写'],evidence:[{url:'javascript:bad()',start:0,end:1,observation:'<script>bad()</script>'}]}]}};}});await tick();await app.openTopic();await app.openRecord('one','analysis');await app.click('[data-hl-action="imported-report"]');assert.equal(requested,'import-1');assert(app.root.textContent.includes('导入建议 · 待核验'));assert(app.root.textContent.includes('短镜头'));assert.equal(app.root.querySelectorAll('script,img,a[href^="javascript:"]').length,0);await app.click('[data-hl-action="back"]');assert(app.root.querySelector('[data-record="one"]'));app.dispose();
});
test('changing from hidden detail to active clears private rows while loading or failing',async()=>{
 let rejectFail,wasHidden=false;const app=harness([],{load:async({view})=>{if(view==='hidden'){wasHidden=true;return {records:[base('secret',{title:'隐藏记录标题',hidden:true})],topics:[{id:'secret-topic',title:'隐藏专题名称',recordIds:['secret']}],counts:{},reviews:[]};}if(wasHidden)return new Promise((resolve,reject)=>{rejectFail=reject;});return {records:[],counts:{},reviews:[]};}});await tick();await app.click('[data-hl-action="view"][data-id="hidden"]');assert(app.root.textContent.includes('隐藏专题名称'));await app.openTopic('secret-topic');await app.openRecord('secret','analysis');assert(app.root.textContent.includes('隐藏记录标题'));await app.click('[data-hl-action="view"][data-id="active"]');assert(!app.root.textContent.includes('隐藏记录标题'));assert(!app.root.textContent.includes('隐藏专题名称'));rejectFail(new Error('加载失败'));await tick();assert(app.root.textContent.includes('加载失败'));assert(!app.root.textContent.includes('隐藏分析秘密'));assert(!app.root.textContent.includes('隐藏记录标题'));app.dispose();
});
test('topic create, rename and move preserve records and breadcrumb navigation',async()=>{
 const app=harness();await tick();await app.click('[data-hl-action="create-topic"]');app.root.querySelector('[data-hl-field="topic-title"]').value='产品开头';await app.submit('topic');assert(app.root.querySelector('[data-topic="new-topic"]'));await app.openTopic();await app.click('[data-hl-action="rename-topic"]');app.root.querySelector('[data-hl-field="topic-title"]').value='品牌参考';await app.submit('topic');assert(app.root.textContent.includes('品牌参考'));app.select('[data-hl-select="one"]');await app.click('[data-hl-action="batch:move-topic"]');const select=app.root.querySelector('[data-hl-field="topic-id"]');select.querySelector('option').setAttribute('selected','');await app.submit('move-topic');assert.deepEqual(app.calls.map(p=>p.action),['create-topic','rename-topic','move-topic']);await app.click('[data-hl-action="home"]');await app.openTopic('new-topic');await app.openRecord();assert(app.root.querySelector('[aria-label="资料库面包屑"]').textContent.includes('产品开头'));await app.click('[data-hl-action="topic"][data-id="new-topic"]');assert(app.root.querySelector('[data-hl-action="record"]'));app.dispose();
});
test('Chinese display titles stay concise while original English caption remains folded',async()=>{
 assert.equal(historyDisplayTitle({title:'A long original English caption'},2),'参考视频 03');assert.equal(historyDisplayTitle({displayTitleZh:'香氛开场',title:'English caption'}),'香氛开场');const app=harness([base('one',{title:'Original English caption <script>attack()</script>',account:null})]);await tick();await app.openTopic();assert(app.root.textContent.includes('参考视频 01'));assert(!app.root.textContent.includes('Original English caption'));await app.openRecord();const caption=app.root.querySelector('.hl-caption');assert(caption&&!caption.hasAttribute('open'));assert(caption.textContent.includes('Original English caption'));assert.equal(app.root.querySelectorAll('script').length,0);app.dispose();
});
test('analysis requires explicit upload consent and preserves intent, cache refresh only reads',async()=>{
 let readCalls=0,statusCalls=0,analyzeCalls=[];const completed={status:'completed',cached:true,intent:'只研究开头',provider:'mosi',result:{titleZh:'开头的节奏',audio:{hasSpeech:false},visual:{observations:[]},rhythm:{measurements:{durationSec:5}}}};
 const app=harness([base('one',{mediaAvailable:true})],{loadAnalysisStatus:async()=>{statusCalls++;return {vlModel:'synthetic-vl',asrModel:'synthetic-asr',priceLabel:'合成价格 / 分钟'};},loadAnalysis:async()=>{readCalls++;return readCalls===1?{status:'not-started'}:completed;},analyze:async(id,input)=>{analyzeCalls.push([id,input]);return completed;}});await tick();assert.equal(statusCalls,1);assert.equal(analyzeCalls.length,0);await app.openTopic();await app.openRecord('one','analysis');assert.equal(readCalls,1);await app.click('[data-hl-action="analyze"]');assert.equal(analyzeCalls.length,0);assert(app.root.textContent.includes('将把本条本机视频发送到模思'));assert(app.root.textContent.includes('synthetic-vl'));assert(app.root.textContent.includes('合成价格'));app.root.querySelector('[data-hl-field="intent"]').value='只研究开头';await app.submit('analysis');assert.deepEqual(analyzeCalls,[['one',{consent:true,intent:'只研究开头'}]]);assert(app.root.textContent.includes('这次参考重点'));assert(app.root.textContent.includes('只研究开头'));assert(app.root.textContent.includes('没有识别到可用语音'));await app.click('[data-hl-action="refresh-analysis"]');assert.equal(readCalls,2);assert.equal(analyzeCalls.length,1);app.dispose();
});
test('late analysis response and rejection cannot leak after changing views',async()=>{
 let resolve,reject;const app=harness([base()],{loadAnalysis:()=>new Promise(r=>resolve=r),analyze:()=>new Promise((r,j)=>reject=j)});await tick();await app.openTopic();await app.openRecord('one','analysis');await app.click('[data-hl-action="view"][data-id="hidden"]');resolve({status:'completed',result:{summaryZh:'前一视图的分析'}});await tick();assert(!app.root.textContent.includes('前一视图的分析'));await app.click('[data-hl-action="view"][data-id="active"]');await app.openTopic();await app.openRecord('one','analysis');resolve({status:'not-started'});await tick();await app.click('[data-hl-action="analyze"]');await app.submit('analysis');await app.click('[data-hl-action="view"][data-id="hidden"]');reject(new Error('前一视图的错误'));await tick();assert(!app.root.textContent.includes('前一视图的错误'));app.dispose();
});
