import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,writeFile,symlink,readdir} from 'node:fs/promises';
import {spawn} from 'node:child_process';
import os from 'node:os';import path from 'node:path';
import {createHistoryStore,canonicalHistoryUrl} from '../src/history-store.mjs';
import {createHistoryHandlers,applyHistoryService} from '../src/history-service.mjs';
const account={username:'testbrand',url:'https://www.instagram.com/testbrand/'};
const sample=(code='AbC',more={})=>({url:`https://www.instagram.com/reel/${code}/`,title:'合成参考视频 '+code,views:120,likes:3,duration:8,...more});
const payload=(samples=[sample()],more={})=>({account,samples,collectedAt:'2026-10-01T02:00:00.000Z',provider:'mock-only',...more});
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'history-synthetic-'));return{root,store:createHistoryStore({root})};}
const post=(body,headers={})=>new Request('http://localhost/history',{method:'POST',headers:{'x-derek-workbench':'1',...headers},body:JSON.stringify(body)});
const get=url=>new Request('http://localhost'+url);
function syntheticReport(){return{schemaVersion:1,accountUrl:account.url,source:'synthetic-only',analyzedAt:'2026-10-01T02:00:00.000Z',types:[{type:'合成风格',evidence:[{url:sample('AbC').url,start:0,end:1,observation:'合成观察1'},{url:sample('XyZ').url,start:1,end:2,observation:'合成观察2'}],tone:'synthetic',rhythm:'synthetic',hook:'synthetic',subtitles:'synthetic',reason:'synthetic',editPlan:'synthetic',replicaPlan:'synthetic',requiredAssets:['synthetic']}]};}

test('canonical Instagram dedupe preserves shortcode case and removes tracking',()=>{assert.equal(canonicalHistoryUrl('https://www.instagram.com/p/AbC/?utm=x').id,'ig_AbC');assert.notEqual(canonicalHistoryUrl(sample('AbC').url).id,canonicalHistoryUrl(sample('abc').url).id);assert.equal(canonicalHistoryUrl('https://youtube.com/watch?v=ABC&token=secret').url,'https://youtube.com/watch?v=ABC');assert.throws(()=>canonicalHistoryUrl('https://a.cdninstagram.com/test.mp4?sig=private'));assert.throws(()=>canonicalHistoryUrl('file:///private/example'));});
test('real file reopen preserves rows, edit and cache; duplicate import does not duplicate row or identical batch',async()=>{const{root,store}=await fixture();await store.ingest(payload());const initial=await store.snapshot();await store.mutate({action:'edit',ids:[initial.records[0].id],title:'自选名',notes:'笔记',tags:['A','A']});await store.ingest(payload());const second=createHistoryStore({root});const read=await second.snapshot();assert.equal(read.records.length,1);assert.equal(read.batches.length,1);assert.equal(read.records[0].title,'自选名');assert.deepEqual(read.records[0].tags,['A']);assert.equal((await second.findAccountCache('TestBrand')).samples.length,1);assert.equal((await readdir(path.join(root,'library'))).filter(f=>f.endsWith('.tmp')).length,0);});
test('hidden and trash records are not resurrected by reimport; restore retains hidden choice',async()=>{const{store}=await fixture();await store.ingest(payload());const id=(await store.snapshot()).records[0].id;await store.mutate({action:'hide',ids:[id]});await store.mutate({action:'trash',ids:[id]});await store.ingest(payload([sample()],{collectedAt:'2026-10-02T00:00:00Z'}));assert.equal((await store.snapshot()).records.length,0);assert.equal((await store.snapshot({view:'trash'})).records.length,1);assert.equal((await store.findAccountCache(account.username)).samples.length,0);await store.mutate({action:'restore',ids:[id]});assert.equal((await store.snapshot({view:'hidden'})).records.length,1);await store.mutate({action:'unhide',ids:[id]});assert.equal((await store.snapshot()).records.length,1);});
test('refresh preserves successful cache on failed ingestion and keeps actual metadata zero values',async()=>{const{store}=await fixture();await store.ingest(payload([sample('AbC',{views:0})]));await assert.rejects(store.ingest(payload([],{status:'failed'})),/失败/);const cache=await store.findAccountCache(account.username);assert.equal(cache.samples.length,1);assert.equal(cache.samples[0].views,0);assert.equal(cache.cached,true);});
test('corrupt existing JSON is never replaced by an empty store',async()=>{const{root,store}=await fixture();await mkdir(path.join(root,'library'));const target=path.join(root,'library/state.json');await writeFile(target,'{ broken');await assert.rejects(store.ingest(payload()),e=>e.code==='HISTORY_CORRUPT');assert.equal(await readFile(target,'utf8'),'{ broken');});
test('parallel modifications through multiple store instances retain every row',async()=>{const{root}=await fixture();const stores=[createHistoryStore({root}),createHistoryStore({root})];await Promise.all(Array.from({length:20},(_,i)=>stores[i%2].ingest(payload([sample('Test'+i)]))));assert.equal((await stores[0].snapshot()).records.length,20);assert.equal((await stores[0].snapshot()).revision,20);});
test('separate node processes serialize writes without dropping records',async()=>{const{root,store}=await fixture();const moduleUrl=new URL('../src/history-store.mjs',import.meta.url).href;const run=i=>new Promise((resolve,reject)=>{const script=`import {createHistoryStore} from ${JSON.stringify(moduleUrl)}; await createHistoryStore({root:process.argv[1]}).ingest(JSON.parse(process.argv[2]));`;const child=spawn(process.execPath,['--input-type=module','-e',script,root,JSON.stringify(payload([sample('Process'+i)]))],{stdio:['ignore','pipe','pipe']});let err='';child.stderr.on('data',chunk=>err+=chunk);child.on('error',reject);child.on('close',code=>code===0?resolve():reject(new Error(err)));});await Promise.all([0,1,2,3].map(run));assert.equal((await store.snapshot()).records.length,4);});
test('feedback correction keeps independent attempts and requires explanation without inventing verification',async()=>{const{store}=await fixture();await store.ingest(payload());const id=(await store.snapshot()).records[0].id;await assert.rejects(store.mutate({action:'feedback',ids:[id],outcome:'success'}),/成功表现/);await store.mutate({action:'feedback',ids:[id],outcome:'success',note:'用户自述画面更清晰'});const first=(await store.snapshot()).records[0].feedback[0];assert.equal(first.evidenceStatus,'user-reported-unverified');assert.equal(first.evidence,null);await store.mutate({action:'feedback',ids:[id],outcome:'needs-improvement',note:'回看发现字幕被遮挡',correctionOf:first.attemptId});const fs=(await store.snapshot()).records[0].feedback;assert.equal(fs.length,2);assert.equal(fs[0].supersededBy,fs[1].attemptId);assert.equal(fs[1].correctionOf,first.attemptId);await assert.rejects(store.mutate({action:'feedback',ids:[id],outcome:'success',note:'再改',correctionOf:first.attemptId}),/已有纠正/);});
test('metadata cannot inject trusted report references or fake downloaded/analysis status',async()=>{const{store}=await fixture();await store.ingest(payload([sample('AbC',{reportRefs:[{runId:'fake',videoId:'v1'}],mediaAvailable:true,status:'completed'})]));const r=(await store.snapshot()).records[0];assert.deepEqual(r.reportRefs,[]);assert.equal(r.mediaAvailable,false);assert.equal(r.status.analysis,'pending');assert.equal(r.status.download,'missing');});
test('legacy migration imports report refs and confirms only existing downloaded media; rerun is idempotent',async()=>{const{root,store}=await fixture();const run='synthetic-20261001';await mkdir(path.join(root,run,'v1'),{recursive:true});await writeFile(path.join(root,run,'v1/source.mp4'),'synthetic-media');await writeFile(path.join(root,'index.json'),JSON.stringify({accounts:{testbrand:run,unsafe:'../escape'}}));await writeFile(path.join(root,run,'samples.json'),JSON.stringify(payload([sample('AbC'),sample('XyZ')])));await writeFile(path.join(root,run,'report.json'),JSON.stringify({account,videos:[{id:'v1',sourceUrl:sample('AbC').url,file:'v1/source.mp4'},{id:'v2',sourceUrl:sample('XyZ').url,file:'v2/source.mp4'}]}));await mkdir(path.join(root,'style-library'));await writeFile(path.join(root,'style-library','style-a.json'),JSON.stringify({templateId:'style-a',sourceReport:run,status:'draft-unconfirmed',style:{name:'合成风格'}}));let snap=await store.snapshot();assert.equal(snap.records.length,2);assert.equal(snap.records.find(r=>r.id==='ig_AbC').mediaAvailable,true);assert.equal(snap.records.find(r=>r.id==='ig_XyZ').mediaAvailable,false);assert.equal(snap.records[0].reportRefs[0].runId,run);assert.equal(snap.records[0].styleRefs[0].templateId,'style-a');assert(!JSON.stringify(snap).includes(root));await store.refreshLegacy();snap=await createHistoryStore({root}).snapshot();assert.equal(snap.batches.length,1);assert.equal(snap.records[0].reportRefs.length,1);});
test('legacy safe run paths cannot follow report symlinks outside data root',async()=>{const{root,store}=await fixture();const outside=await mkdtemp(path.join(os.tmpdir(),'history-outside-'));await writeFile(path.join(outside,'report.json'),JSON.stringify({account,videos:[]}));await symlink(outside,path.join(root,'safe-run'));await writeFile(path.join(root,'index.json'),JSON.stringify({accounts:{testbrand:'safe-run'}}));await assert.rejects(store.snapshot(),e=>e.code==='HISTORY_UNSAFE_PATH');});
test('readable metadata import retains externally validated report with unverified label across restart',async()=>{const{root,store}=await fixture();const report=syntheticReport();const first=await store.importLegacy({...payload(),goal:'合成目标',assets:'合成素材',report});await store.importLegacy({...payload(),report});const reboot=createHistoryStore({root});const snap=await reboot.snapshot();assert.equal(snap.records.length,2);assert.equal(snap.records[0].status.analysis,'imported-unverified');assert.equal((await reboot.readImportedReport(first.importedReportId)).status,'imported-unverified');const cache=await reboot.findAccountCache(account.username);assert.equal(cache.report.types[0].type,'合成风格');assert.equal(cache.goal,'合成目标');assert.equal(snap.records[0].importedReportIds.length,1);await reboot.mutate({action:'hide',ids:['ig_AbC']});assert.equal((await reboot.findAccountCache(account.username)).report,null);await assert.rejects(reboot.readImportedReport(first.importedReportId),e=>e.code==='HISTORY_REPORT_HIDDEN');});
test('weekly source excludes hidden/trash, keeps claims unverified, and old report is restricted after hide',async()=>{const{store}=await fixture();await store.ingest(payload([sample('AbC'),sample('XyZ')]));await store.mutate({action:'hide',ids:['ig_XyZ']});await store.mutate({action:'feedback',ids:['ig_AbC'],outcome:'success',note:'用户报告改善'});const source=await store.exportReviewSource({periodStart:'2020-01-01',periodEnd:'2030-01-01'});assert.equal(source.records.length,1);assert(source.evidencePolicy.includes('未经独立核验'));assert.equal(source.feedbackIds.length,1);const saved=await store.saveReview({kind:'local-summary',periodStart:source.periodStart,periodEnd:source.periodEnd,sourceRevision:source.revision,recordIds:source.records.map(r=>r.id),feedbackIds:source.feedbackIds,markdown:'合成周报：用户自报改善，待核验。'});assert((await store.readReview(saved.review.id)).markdown.includes('待核验'));await store.mutate({action:'hide',ids:['ig_AbC']});assert.equal((await store.snapshot()).reviews[0].restricted,true);await assert.rejects(store.readReview(saved.review.id),e=>e.code==='HISTORY_REVIEW_HIDDEN');});
test('stale weekly writes are rejected and do not silently change evidence source',async()=>{const{store}=await fixture();await store.ingest(payload());const prior=await store.snapshot();await store.mutate({action:'favorite',ids:['ig_AbC']});await assert.rejects(store.saveReview({kind:'local-summary',periodStart:'2026-10-01',periodEnd:'2026-10-08',sourceRevision:prior.revision,recordIds:['ig_AbC'],markdown:'test'}),e=>e.code==='HISTORY_STALE');assert.equal((await store.snapshot()).reviews.length,0);});
test('service validates origin, request size and methods, and preserves backend errors',async()=>{const{store}=await fixture();const h=createHistoryHandlers({store});assert.equal((await h.mutate(post({action:'hide',ids:['x']},{origin:'https://elsewhere.invalid'}))).status,403);assert.equal((await h.mutate(post({action:'hide',ids:['x']}))).status,404);assert.equal((await h.mutate(get('/'))).status,405);assert.equal((await h.importLegacy(post({...payload(),notes:'x'.repeat(70000)}))).status,413);assert.equal((await h.importLegacy(post(payload()))).status,200);assert.equal((await h.snapshot(get('/?view=active&q=合成'))).status,200);assert.equal((await h.snapshot(get('/?view=invalid'))).status,400);});
test('service exact paths register once and root combines GET and POST',async()=>{const{store}=await fixture();const calls=[];const ctx={connection:{fetch:{register:r=>calls.push(r)}}};applyHistoryService(ctx,{store});applyHistoryService(ctx,{store});assert.equal(calls.length,4);assert.deepEqual(calls[0].methods,['GET','POST']);assert.equal(new Set(calls.map(c=>c.path)).size,4);});
test('no operation permanently removes media and evidence cannot leak an absolute local path',async()=>{const{root,store}=await fixture();await store.ingest(payload());await writeFile(path.join(root,'keep.mp4'),'keep');await store.mutate({action:'trash',ids:['ig_AbC']});assert.equal(await readFile(path.join(root,'keep.mp4'),'utf8'),'keep');await store.mutate({action:'restore',ids:['ig_AbC']});await assert.rejects(store.mutate({action:'feedback',ids:['ig_AbC'],outcome:'success',note:'self report',evidence:'/private/sensitive/output.mp4'}),/绝对路径/);});

test('safe named video IDs retain actual downloaded state during migration',async()=>{const{root,store}=await fixture();const run='named-synthetic';await mkdir(path.join(root,run,'clip_a'),{recursive:true});await writeFile(path.join(root,run,'clip_a/source.mp4'),'synthetic-media');await writeFile(path.join(root,'index.json'),JSON.stringify({accounts:{testbrand:run}}));await writeFile(path.join(root,run,'report.json'),JSON.stringify({account,videos:[{id:'clip_a',sourceUrl:sample('NamedClip').url,file:'clip_a/source.mp4'}]}));const r=(await store.snapshot()).records[0];assert.equal(r.mediaAvailable,true);assert.equal(r.status.download,'available');assert.equal(r.reportRefs[0].videoId,'clip_a');});
