import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,readdir,rm,symlink,writeFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {createHash} from 'node:crypto';
import {createResearchComparison,createDshResearchComparisonClient,normalizeComparison,comparisonPrompt} from '../src/research-comparison.mjs';
const ids=['ref_a','ref_b','ref_c','ref_d'];
const plan={userIntent:'研究本次轻便收纳形式',product:'通勤包',audience:'城市通勤者',materialStatus:{state:'none'},budgetScope:{maxComparisonCalls:1,maxPromptCompileCalls:1}};
const job={jobId:'job_synthetic',planRevision:1};
function record(recordId){return {recordId,metadata:{duration:10,publishedAt:'2026-10-01T00:00:00Z',views:null,likes:20,url:'https://www.instagram.com/reel/SYNTHETIC/'},result:{status:'completed',titleZh:'整理物品的收纳过程',summaryZh:'从桌面零散物品到收进通勤包',tagsZh:['收纳演示'],visual:{summaryZh:'手将桌面物品逐次放进包中',observations:[{startSec:0,endSec:10,descriptionZh:'俯拍桌面手把物品放进包里'}]},rhythm:{measurements:{durationSec:10,candidateCutsSec:[5],medianShotSec:5},modelInference:{summaryZh:'以两段动作推进'}},audio:{status:'completed',hasAudio:true,hasSpeech:false,text:'',segments:[]},recommendations:[{nameZh:'桌面收纳演示',status:'conditional',reasonZh:'以物品清单展示容量',requiredMaterials:[{purposeZh:'主体',descriptionZh:'自有包和日常物品'}]}]}};}
const records=()=>ids.map(record);
function ranked(){return {summaryZh:'优先清晰动作和较低拍摄门槛，三种不同表现侧重点',recommendations:ids.slice(0,3).map((recordId,i)=>({recordId,reasonZh:'动作结构清楚，可以替换为自己的商品和展示物品'+i,formZh:'桌面收纳形式'+i,materialThresholdZh:'需要桌面、自己的通勤包与几件日常物品',evidence:[{startSec:0,endSec:5}]})),excluded:[{recordId:ids[3],reasonZh:'结构与已选参考重复，先保留表现更清楚的样本'}]};}
const packageValue=()=>({goalPlanZh:'保留固定俯拍与物品整理顺序，替换为自己的通勤包和真实随身物品',globalPromptEn:'Recreate the overhead tabletop composition in neutral daylight with a fixed camera and consistent beige background, using @Video1 for pacing and @Image2 for the replacement product throughout every visible interaction.',globalNegativeEn:'Avoid inconsistent product geometry, copied logos, extra fingers and unstable camera position.',assetBindings:[{token:'@Image2',required:true}],shots:[{id:'shot-1',startSec:0,endSec:10,descriptionZh:'手将物品整理并放进包里',framingZh:'固定俯拍桌面中近景',cameraZh:'相机保持固定俯拍角度',actionZh:'从桌面散放物品开始，双手依次将它们收入包中',endStateZh:'物品留在打开的包内，双手停在桌面边缘',promptEn:'Framing: overhead medium close view of the beige tabletop and replacement @Image2 bag. Camera: hold the camera fixed above the tabletop throughout the action. Action: hands move the visible small objects from the table into the open replacement @Image2 bag in the observed order. End state: keep the bag open with the visible objects inside and hands resting near the tabletop edge.'}],missingInputs:[]});
function response(json){return {status:'completed',finishReason:'stop',json,usage:{inputTokens:100,outputTokens:200},provider:'deepseek-official',model:'synthetic-model'};}
function client(){const calls=[];return {calls,async completeJson(input){calls.push(input);return response(input.stage==='comparison'?ranked():{packages:ids.slice(0,3).map(recordId=>({recordId,recreationPackage:packageValue()}))});}};}
async function root(t){const dir=await mkdtemp(path.join(os.tmpdir(),'dsh-comparison-test-'));t.after(()=>rm(dir,{recursive:true,force:true}));return dir;}

test('one comparison plus one compilation produces ranked evidence and complete reusable packages',async t=>{const dir=await root(t),c=client(),compare=createResearchComparison({root:dir,client:c});const result=await compare({plan,job,records:records()});assert.equal(result.status,'completed');assert.equal(result.promptStatus,'completed');assert.equal(result.recommendations.length,3);assert.equal(result.recommendations[0].recreationPackage.status,'needs-input');assert.match(result.recommendations[0].recreationPackage.fullPromptText,/Framing:/);assert.deepEqual(c.calls.map(x=>x.stage),['comparison','compilation']);assert.deepEqual(result.providerCalls,{comparison:1,compilation:1});const sub=await readdir(path.join(dir,'research-comparisons'));const files=await readdir(path.join(dir,'research-comparisons',sub[0]));assert(files.includes('comparison.response.json')&&files.includes('compilation.response.json'));assert(!files.includes('in-use.lock'));});
test('same job replay reuses results; scope changes fail before another provider call',async t=>{const dir=await root(t),c=client(),compare=createResearchComparison({root:dir,client:c});await compare({plan,job,records:records()});assert.equal((await compare({plan,job,records:records()})).cached,true);await assert.rejects(compare({plan:{...plan,userIntent:'修改目标'},job,records:records()}),e=>e.code==='COMPARISON_SCOPE');assert.equal(c.calls.length,2);});
test('concurrent callers never dispatch duplicate requests',async t=>{const dir=await root(t),c=client();let release,entered;const wait=new Promise(r=>release=r),started=new Promise(r=>entered=r),original=c.completeJson;c.completeJson=async function(x){if(x.stage==='comparison'){entered();await wait;}return original.call(c,x);};const first=createResearchComparison({root:dir,client:c})({plan,job,records:records()});await started;const second=await createResearchComparison({root:dir,client:c})({plan,job,records:records()});assert.equal(second.status,'pending');release();await first;assert.equal(c.calls.length,2);});
test('failed comparison is saved and replayed without retries or prompt compilation',async t=>{const dir=await root(t);let calls=0;const compare=createResearchComparison({root:dir,client:{async completeJson(){calls++;throw new Error('private supplier failure with secret');}}});const one=await compare({plan,job,records:records()});assert.equal(one.status,'failed');assert(!JSON.stringify(one).includes('secret'));assert.equal((await compare({plan,job,records:records()})).cached,true);assert.equal(calls,1);});
test('prompt failure preserves good top three but marks every package incomplete, and does not retry',async t=>{const dir=await root(t),c=client(),original=c.completeJson;c.completeJson=async function(x){if(x.stage==='compilation'){this.calls.push(x);throw Error('failure');}return original.call(this,x);};const compare=createResearchComparison({root:dir,client:c}),r=await compare({plan,job,records:records()});assert.equal(r.status,'completed');assert.equal(r.promptStatus,'failed');assert.equal(r.recommendations.length,3);assert(r.recommendations.every(x=>x.recreationPackage.status==='incomplete'));await compare({plan,job,records:records()});assert.equal(c.calls.length,2);});
test('all excluded performs only comparison; empty visual input calls no models',async t=>{const dir=await root(t);let calls=0;const compare=createResearchComparison({root:dir,client:{async completeJson(){calls++;return response({summaryZh:'这些视频目前均不适合复刻',recommendations:[],excluded:ids.map(recordId=>({recordId,reasonZh:'素材条件无法满足且不应编造'}))});}}});const r=await compare({plan,job,records:records()});assert.equal(r.promptStatus,'skipped');assert.equal(calls,1);const empty=await compare({plan,job:{jobId:'job_empty'},records:[]});assert.equal(empty.status,'completed');assert.equal(calls,1);});
test('unknown metrics remain null and private stale fields are not included in prompt',async t=>{const dir=await root(t),c=client(),rows=records();rows[0].result.apiKey='SYNTHETIC_SECRET';rows[0].metadata.videoUrl='https://example.invalid?signature=DO_NOT_SEND';rows[0].metadata.likes=undefined;const compare=createResearchComparison({root:dir,client:c});await compare({plan:{...plan,unrelatedHistory:'PAST_PRIVATE_CASE'},job,records:rows});assert(c.calls[0].prompt.includes('"likes":null'));assert(c.calls[0].prompt.includes('"views":null'));assert(!c.calls.some(x=>/SYNTHETIC_SECRET|DO_NOT_SEND|PAST_PRIVATE_CASE/.test(x.prompt)));});
test('invalid rank ids, duplicates, omissions, too many recommendations or out-of-evidence timestamps fail entire comparison',async t=>{for(const mutate of [r=>r.recommendations[0].recordId='unknown',r=>r.recommendations[1].recordId=ids[0],r=>r.excluded=[],r=>r.recommendations.push({...r.recommendations[0],recordId:ids[3]}),r=>r.recommendations[0].evidence[0].endSec=11,r=>r.recommendations[0].reasonZh='English only']){const dir=await root(t),raw=ranked();mutate(raw);let calls=0;const r=await createResearchComparison({root:dir,client:{async completeJson(){calls++;return response(raw);}}})({plan,job,records:records()});assert.equal(r.status,'failed');assert.equal(calls,1);}});
test('incomplete director schema is retained with explicit incomplete prompt status',async t=>{const dir=await root(t),c=client(),original=c.completeJson;c.completeJson=async function(x){if(x.stage==='compilation'){this.calls.push(x);return response({packages:ids.slice(0,3).map(recordId=>({recordId,recreationPackage:{...packageValue(),shots:[]}}))});}return original.call(this,x);};const r=await createResearchComparison({root:dir,client:c})({plan,job,records:records()});assert.equal(r.status,'completed');assert.equal(r.promptStatus,'incomplete');assert(r.recommendations.every(x=>!x.recreationPackage.fullPromptText));});
test('symlinked storage is refused before provider dispatch',async t=>{const dir=await root(t),outside=await root(t),c=client();await symlink(outside,path.join(dir,'research-comparisons'));await assert.rejects(createResearchComparison({root:dir,client:c})({plan,job,records:records()}),e=>e.code==='COMPARISON_STORE');assert.equal(c.calls.length,0);});
test('interrupted persisted stage never automatically restarts a paid request',async t=>{const dir=await root(t),c=client(),compare=createResearchComparison({root:dir,client:c});await compare({plan,job,records:records()});const folders=await readdir(path.join(dir,'research-comparisons')),file=path.join(dir,'research-comparisons',folders[0],'state.json'),s=JSON.parse(await readFile(file));delete s.result;s.steps.compilation='requesting';await writeFile(file,JSON.stringify(s));const before=c.calls.length,r=await compare({plan,job,records:records()});assert.equal(r.status,'failed');assert.equal(r.error.code,'COMPARISON_INTERRUPTED');assert.equal(c.calls.length,before);});
test('inactive records block provider calls and changes during response stop prompt compilation',async t=>{const dir=await root(t),c=client();await assert.rejects(createResearchComparison({root:dir,client:c,isActive:async()=>false})({plan,job,records:records()}),e=>e.code==='COMPARISON_INACTIVE');assert.equal(c.calls.length,0);let n=0;const compare=createResearchComparison({root:dir,client:c,isActive:async()=>++n<3}),r=await compare({plan,job,records:records()});assert.equal(r.status,'failed');assert.equal(c.calls.length,1);});
test('DSH client reuses native official model without reading or exporting credentials',async()=>{const captured=[];const ctx={get(key){if(key==='agentDefaultModel')return {currentSelection:()=>({provider:'deepseek-official',model:'deepseek-flash'})};if(key==='llm')return {async prepareCall(config){captured.push(config);return {config,async *stream(options){assert.equal(options.messages.length,1);assert.equal(options.messages[0].source.kind,'dsh-research-comparison');yield {type:'text-delta',index:0,text:'{"ok":'};yield {type:'text-delta',index:0,text:'true}'};yield {type:'block-end',index:0,block:{type:'text',text:'{"ok":true}'}};yield {type:'usage',usage:{inputTokens:20,outputTokens:4}};yield {type:'finish',reason:{kind:'stop'}};}};}};throw Error('must not read credentials');}};const r=await createDshResearchComparisonClient({ctx}).completeJson({stage:'comparison',prompt:'中文 JSON',maxOutputTokens:4000});assert.equal(r.text,'{"ok":true}');assert.equal(r.provider,'deepseek-official');assert.equal(captured.length,1);assert.equal(captured[0].maxTokens,4000);});
test('DSH client rejects another provider, truncated responses, missing terminal state and tool calls',async()=>{let calls=0;const llm={async prepareCall(config){calls++;return {config,async *stream(){yield {type:'text-delta',index:0,text:'{}'};yield {type:'finish',reason:{kind:'max-tokens'}};}};}};const ctx={get:k=>k==='llm'?llm:{currentSelection:()=>({provider:'other',model:'x'})}};await assert.rejects(createDshResearchComparisonClient({ctx}).completeJson({prompt:'{}',stage:'comparison',maxOutputTokens:4000}),e=>e.code==='COMPARISON_PROVIDER');assert.equal(calls,0);await assert.rejects(createDshResearchComparisonClient({ctx,getConfiguration:()=>({provider:'deepseek-official',model:'configured-model'})}).completeJson({prompt:'{}',stage:'comparison',maxOutputTokens:4000}),e=>e.code==='COMPARISON_FAILED');assert.equal(calls,1);});
test('sparse visual evidence cannot be compiled into a falsely complete full-length package',async t=>{const dir=await root(t),c=client(),rows=records();for(const r of rows)r.result.visual.observations=[{startSec:0,endSec:5,descriptionZh:'只有前五秒看到物品放入包里'}];const r=await createResearchComparison({root:dir,client:c})({plan,job,records:rows});assert.equal(r.status,'completed');assert.equal(r.promptStatus,'incomplete');assert(r.recommendations.every(x=>x.recreationPackage.fullPromptText===''));});
test('pending visual data and explicitly disallowed call budgets never reach provider',async t=>{const dir=await root(t),c=client(),compare=createResearchComparison({root:dir,client:c}),rows=records();rows[0].result.status='pending';await assert.rejects(compare({plan,job,records:rows}),e=>e.code==='COMPARISON_INPUT');await assert.rejects(compare({plan:{...plan,budgetScope:{maxComparisonCalls:0}},job,records:records()}),e=>e.code==='COMPARISON_INPUT');assert.equal(c.calls.length,0);});
test('dead-owner pending stage reports interrupted and does not charge again',async t=>{const dir=await root(t),c=client(),compare=createResearchComparison({root:dir,client:c});await compare({plan,job,records:records()});const folders=await readdir(path.join(dir,'research-comparisons')),folder=path.join(dir,'research-comparisons',folders[0]),file=path.join(folder,'state.json'),s=JSON.parse(await readFile(file));delete s.result;s.steps.compilation='requesting';await writeFile(file,JSON.stringify(s));await writeFile(path.join(folder,'in-use.lock'),JSON.stringify({pid:2147483647}));const n=c.calls.length,r=await compare({plan,job,records:records()});assert.equal(r.status,'failed');assert.equal(r.error.code,'COMPARISON_INTERRUPTED');assert.equal(c.calls.length,n);});
test('selection intent changes comparison and compilation prompts: diverse forms versus known performance',async t=>{for(const [mode,expected,absent] of [['balanced','差异优先','表现优先'],['top-in-page','表现优先','差异优先']]){const dir=await root(t),c=client(),p={...plan,selectionPolicy:{mode,count:6,metric:'views',windowDays:30,windowStart:'2026-09-10T00:00:00Z',windowEnd:'2026-10-10T00:00:00Z'}};await createResearchComparison({root:dir,client:c})({plan:p,job,records:records()});assert.match(c.calls[0].prompt,new RegExp(expected));assert(!c.calls[0].prompt.includes('（'+absent+'）'));assert(c.calls.every(x=>x.prompt.includes('"selectionPolicy":{"mode":"'+mode+'"')));assert(c.calls.every(x=>x.prompt.includes('"metric":"views"')));assert.match(c.calls[0].prompt,/不能保证成功率/);if(mode==='top-in-page')assert.match(c.calls[0].prompt,/未知指标不按零计算/);}});
test('changing only the selection mode or date window invalidates the cached scope before any new charge',async t=>{const dir=await root(t),c=client(),compare=createResearchComparison({root:dir,client:c}),p={...plan,selectionPolicy:{mode:'balanced',metric:'likes',count:6,windowDays:30,windowStart:'2026-09-10T00:00:00Z',windowEnd:'2026-10-10T00:00:00Z'}};await compare({plan:p,job,records:records()});for(const selectionPolicy of [{...p.selectionPolicy,mode:'top-in-page'},{...p.selectionPolicy,windowStart:'2026-09-11T00:00:00Z'}])await assert.rejects(compare({plan:{...p,selectionPolicy},job,records:records()}),e=>e.code==='COMPARISON_SCOPE');assert.equal(c.calls.length,2);});
function gapRecords(){const rows=records();for(const row of rows)row.result.visual.observations=[{startSec:0,endSec:4,descriptionZh:'前四秒看到手整理桌面物品'},{startSec:5,endSec:9.5,descriptionZh:'从第五秒看到手把物品放进包里'}];return rows;}
function gapPackage(){const pack=packageValue(),shot=pack.shots[0];pack.shots=[{...shot,id:'observed-1',startSec:0,endSec:4},{id:'reference-gap-1',startSec:4,endSec:5,referenceOnly:true},{...shot,id:'observed-2',startSec:5,endSec:9.5},{id:'reference-gap-2',startSec:9.5,endSec:10,referenceOnly:true}];return pack;}
function gapClient(mutate=x=>x){const calls=[];return{calls,async completeJson(input){calls.push(input);if(input.stage==='comparison'){const rank=ranked();for(const r of rank.recommendations)r.evidence=[{startSec:0,endSec:3}];return response(rank);}return response({packages:ids.slice(0,3).map(recordId=>({recordId,recreationPackage:mutate(gapPackage())}))});}};}
test('explicit reference-only gaps compile a usable needs-input plan with exact review intervals and fixed wording',async t=>{const dir=await root(t),c=gapClient(),r=await createResearchComparison({root:dir,client:c})({plan,job,records:gapRecords()});assert.equal(r.status,'completed');assert.equal(r.promptStatus,'completed');for(const x of r.recommendations){const p=x.recreationPackage;assert.equal(p.status,'needs-input');assert.deepEqual(p.coverage.gaps,[{startSec:4,endSec:5},{startSec:9.5,endSec:10}]);assert.match(p.fullPromptText,/REFERENCE-DRIVEN PLAN — NEEDS INPUT/);assert.match(p.fullPromptText,/4-5s, 9.5-10s/);assert(p.missingInputs.some(x=>x.key==='reference-gap-1'&&x.labelZh.includes('4–5')));assert.equal(p.shots.filter(x=>x.referenceOnly).length,2);assert(p.shots.filter(x=>x.referenceOnly).every(x=>x.evidenceLevel==='reference-only-unverified'&&x.descriptionZh.includes('不是已识别事实')));assert.match(p.shots[1].promptEn,/REFERENCE ONLY UNVERIFIED INTERVAL/);assert.match(p.markdown,/不是已识别的逐帧画面/);}assert(c.calls[1].prompt.includes('"coverageGaps":[{"startSec":4,"endSec":5},{"startSec":9.5,"endSec":10}]'));assert.match(c.calls[1].prompt,/只允许四个字段/);});
test('missing markers, factual claims in a gap, crossed gaps and inexact marker times remain incomplete',async t=>{for(const mutate of [p=>{p.shots.splice(1,1);return p;},p=>{delete p.shots[1].id;return p;},p=>{p.shots[1].actionZh='人物突然跳起并转身';return p;},p=>{p.shots[1].promptEn='Invent a jump here';return p;},p=>{p.shots[0].endSec=4.5;return p;},p=>{p.shots[1].startSec=4.0001;return p;},p=>{p.shots[1].referenceOnly=false;return p;},p=>{p.shots.push({...p.shots[1],id:'duplicate-gap'});return p;}]){const dir=await root(t),c=gapClient(mutate),r=await createResearchComparison({root:dir,client:c})({plan,job,records:gapRecords()});assert.equal(r.status,'completed');assert.equal(r.promptStatus,'incomplete');assert(r.recommendations.every(x=>x.recreationPackage.status==='incomplete'&&x.recreationPackage.fullPromptText===''));assert.equal(c.calls.length,2);}});
test('a reference-only marker cannot replace an observed interval when no gap exists',async t=>{const dir=await root(t),c=client(),original=c.completeJson;c.completeJson=async function(x){if(x.stage==='compilation'){this.calls.push(x);return response({packages:ids.slice(0,3).map(recordId=>({recordId,recreationPackage:gapPackage()}))});}return original.call(this,x);};const r=await createResearchComparison({root:dir,client:c})({plan,job,records:records()});assert.equal(r.promptStatus,'incomplete');assert(r.recommendations.every(x=>!x.recreationPackage.fullPromptText));});
