import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,writeFile,mkdir,symlink,readdir} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {validateMediaUrl,verifyMediaAddress,normalizeResolvedInstagram,normalizeResolvedDouyin,canonicalDouyinVideo,createMediaResolver,createMediaCache,pruneResearchMediaCache,measureResearchMedia,MEDIA_LIMITS} from '../src/research-media.mjs';
import {createMosiClient} from '../src/mosi-client.mjs';
const videoUrl='https://scontent.test.cdninstagram.com/synthetic.mp4?signature=private-synthetic';
const sourceUrl='https://www.instagram.com/reel/SYNTHETIC/';
async function root(t){const dir=await mkdtemp(path.join(os.tmpdir(),'dsh-research-media-test-'));t.after(()=>rm(dir,{recursive:true,force:true}));return dir;}
test('only trusted HTTPS media CDN URLs and public resolved addresses are accepted',async()=>{for(const url of ['http://scontent.cdninstagram.com/v.mp4','https://scontent.cdninstagram.com.attacker.example/v.mp4','https://127.0.0.1/v.mp4','https://user:pass@scontent.cdninstagram.com/v.mp4','https://scontent.cdninstagram.com:8443/v.mp4','file:///etc/hosts'])assert.throws(()=>validateMediaUrl(url));assert.equal(validateMediaUrl(videoUrl),videoUrl);for(const ip of ['127.0.0.1','10.0.0.1','169.254.169.254','172.16.0.1','192.168.1.2','::1','::ffff:127.0.0.1','fe80::1','2001:db8::1'])await assert.rejects(verifyMediaAddress(videoUrl,{lookup:async()=>[{address:ip,family:ip.includes(':')?6:4}]}));await assert.rejects(verifyMediaAddress(videoUrl,{lookup:async()=>[{address:'8.8.8.8',family:4},{address:'127.0.0.1',family:4}]}));assert.equal((await verifyMediaAddress(videoUrl,{lookup:async()=>[{address:'8.8.8.8',family:4}]})).addresses.length,1);});
test('TikHub resolver pins original shortcode, never returns credentials and never retries',async()=>{let calls=0;const resolve=createMediaResolver({getKey:async()=>'synthetic-secret',verify:async()=>{},fetchImpl:async(url,opts)=>{calls++;assert.equal(new URL(url).pathname,'/api/v1/instagram/v3/get_post_info');assert.equal(new URL(url).searchParams.get('url'),sourceUrl);assert.equal(opts.redirect,'manual');assert.equal(opts.headers.Authorization,'Bearer synthetic-secret');return Response.json({data:{items:[{code:'SYNTHETIC',media_type:2,video_versions:[{url:videoUrl}]}]}});}});const result=await resolve({record:{url:sourceUrl}});assert.equal(result.videoUrl,videoUrl);assert.equal(result.identityVerified,true);assert(!JSON.stringify(result).includes('synthetic-secret'));assert.equal(calls,1);for(const item of [{code:'OTHER',video_url:videoUrl},{video_url:videoUrl},{code:'SYNTHETIC',is_video:false,video_url:videoUrl}])assert.throws(()=>normalizeResolvedInstagram({data:item},sourceUrl));const bad=createMediaResolver({getKey:async()=>'secret',verify:async()=>{},fetchImpl:async()=>{calls++;return new Response('private details',{status:500});}});await assert.rejects(bad({record:{url:sourceUrl}}),e=>e.code==='MEDIA_TIKHUB'&&!e.message.includes('private'));assert.equal(calls,2);});
test('temporary cache is bounded while streaming and redirects never download',async t=>{const dir=await root(t);let calls=0;const cache=createMediaCache({root:dir,limits:{...MEDIA_LIMITS,bytes:8,cacheBytes:1024},transport:async()=>{calls++;return new Response(new Uint8Array(9),{headers:{'content-type':'video/mp4'}});}});await assert.rejects(cache({media:{videoUrl,sourceUrl},jobId:'j1',recordId:'r1'}),e=>e.code==='MEDIA_SIZE');assert.equal(calls,1);const redir=createMediaCache({root:dir,transport:async()=>new Response(null,{status:302,headers:{location:'http://127.0.0.1'}})});await assert.rejects(redir({media:{videoUrl,sourceUrl},jobId:'j2',recordId:'r2'}),e=>e.code==='MEDIA_REDIRECT');});
test('cache release permits exact reuse; no signed URL is stored and cleanup only owns expired cache',async t=>{const dir=await root(t);let calls=0;const cache=createMediaCache({root:dir,transport:async()=>{calls++;return new Response('synthetic media',{headers:{'content-type':'video/mp4'}});},now:()=>1000});const a=await cache({media:{videoUrl,sourceUrl},jobId:'j1',recordId:'r1'});assert.equal(a.cached,false);await assert.rejects(cache({media:{videoUrl,sourceUrl},jobId:'j1',recordId:'r1'}));await a.release();const b=await cache({media:{videoUrl,sourceUrl},jobId:'j1',recordId:'r1'});assert.equal(b.cached,true);assert.equal(calls,1);assert(!(await readFile(path.join(b.directory,'cache.json'),'utf8')).includes('signature'));assert.equal((await pruneResearchMediaCache({root:dir,now:100000,ttlMs:1})).removed,0);await b.release();const original=path.join(dir,'user-original.mp4');await writeFile(original,'never delete');await mkdir(path.join(dir,'research-media-cache','user-folder'));assert.equal((await pruneResearchMediaCache({root:dir,now:100000,ttlMs:1})).removed,1);assert.equal(await readFile(original,'utf8'),'never delete');assert((await readdir(path.join(dir,'research-media-cache'))).includes('user-folder'));});
test('cache root symlink rejected without modifying destination',async t=>{const dir=await root(t),outside=await root(t);await symlink(outside,path.join(dir,'research-media-cache'));const cache=createMediaCache({root:dir,transport:async()=>{throw Error('should not request');}});await assert.rejects(cache({media:{videoUrl,sourceUrl},jobId:'j',recordId:'r'}),e=>e.code==='MEDIA_CACHE');assert.deepEqual(await readdir(outside),[]);});
test('MOSI accepts one validated video_url or file_id but never both or arbitrary URL',async()=>{const calls=[];const client=createMosiClient({keyProvider:async()=>'synthetic-key',transport:async(url,opts)=>{calls.push(JSON.parse(opts.body));return Response.json({status:'completed'});}});await client.analyzeVideo({videoUrl,prompt:'中文研究'});assert.deepEqual(calls[0].input[0].content[1],{type:'input_video',video_url:videoUrl});for(const input of [{fileId:'file-test',videoUrl},{videoUrl:'https://localhost/private'},{videoUrl:'http://scontent.cdninstagram.com/v.mp4'},{}])await assert.rejects(client.analyzeVideo({...input,prompt:'中文'}),e=>e.code==='MOSI_INPUT');assert.equal(calls.length,1);});
test('real synthetic FFmpeg measurements retain hardcut candidates without fabricated beat boundaries',async t=>{const dir=await root(t),run=promisify(execFile),ffmpeg='/opt/homebrew/bin/ffmpeg';try{await run(ffmpeg,['-version']);}catch{t.skip('FFmpeg unavailable for synthetic media test');return;}const clip=path.join(dir,'synthetic.mp4');await run(ffmpeg,['-hide_banner','-v','error','-f','lavfi','-i','color=c=black:s=32x32:d=0.6','-f','lavfi','-i','color=c=white:s=32x32:d=0.6','-filter_complex','[0:v][1:v]concat=n=2:v=1:a=0[v]','-map','[v]','-c:v','libx264','-an',clip]);const result=await measureResearchMedia({filePath:clip,directory:dir});assert.equal(result.hasAudio,false);assert.equal(result.audioFilePath,null);assert(result.measurements.durationSec>1);assert(result.measurements.candidateCutsSec.some(x=>x>0.4&&x<0.8));assert.deepEqual(result.measurements.logicalBeats,[]);await assert.rejects(measureResearchMedia({filePath:clip,directory:dir,maxDurationSec:0.5}),e=>e.code==='MEDIA_DURATION');});

test('media tools force MP4 demuxing and reject playlist disguised as video',async t=>{const dir=await root(t),clip=path.join(dir,'source.mp4');await writeFile(clip,'synthetic bytes');const calls=[];await measureResearchMedia({filePath:clip,directory:dir,runTool:async(bin,args)=>{calls.push(args);if(bin.endsWith('ffprobe'))return {stdout:JSON.stringify({format:{duration:'2'},streams:[{codec_type:'video',width:32,height:32},{codec_type:'audio'}]}),stderr:''};return {stdout:'',stderr:''};}});assert.equal(calls.length,3);for(const args of calls){assert.equal(args[args.indexOf('-f')+1],'mov');assert.equal(args[args.indexOf('-protocol_whitelist')+1],'file,pipe');}const exec=promisify(execFile);try{await exec('/opt/homebrew/bin/ffprobe',['-version']);}catch{t.skip('FFprobe unavailable for synthetic format rejection');return;}await writeFile(clip,'#EXTM3U\n#EXT-X-TARGETDURATION:1\n#EXTINF:1,\nfile:///synthetic-private-target.mp4\n#EXT-X-ENDLIST\n');await assert.rejects(measureResearchMedia({filePath:clip,directory:dir}),error=>error.code==='MEDIA_TOOL');});

const dySource='https://www.douyin.com/video/7448118827402972455';
const dyMedia='https://v26.douyinvod.com/synthetic/video.mp4?signature=private-synthetic';
test('Douyin canonical video resolver uses one official endpoint, checks ID and keeps signing URLs private',async()=>{let calls=0,keyCalls=0;const verifyCalls=[];const resolve=createMediaResolver({getKey:async()=>{keyCalls++;return 'synthetic-key';},verify:async url=>verifyCalls.push(url),fetchImpl:async(url,options)=>{calls++;assert.equal(new URL(url).origin,'https://api.tikhub.io');assert.equal(new URL(url).pathname,'/api/v1/douyin/app/v3/fetch_one_video');assert.equal(new URL(url).searchParams.get('aweme_id'),'7448118827402972455');assert.equal(new URL(url).searchParams.has('url'),false);assert.equal(options.redirect,'manual');return Response.json({data:{aweme_details:[{aweme_id:'7448118827402972455',video:{play_addr:{url_list:[dyMedia]}}}]}});}});const result=await resolve({record:{url:dySource+'?tracking=ignored'}});assert.equal(calls,1);assert.equal(keyCalls,1);assert.deepEqual(verifyCalls,[dyMedia]);assert.equal(result.platform,'douyin');assert.equal(result.sourceId,'7448118827402972455');assert.equal(result.sourceUrl,dySource);assert.equal(result.videoUrl,dyMedia);assert.equal(result.identityVerified,true);assert(!JSON.stringify(result).includes('synthetic-key'));for(const url of ['https://v.douyin.com/SYNTHETIC/','https://www.douyin.com/user/SYNTHETIC','https://www.douyin.com/note/7448118827402972455','https://www.douyin.com.evil.example/video/7448118827402972455','https://www.douyin.com:1234/video/7448118827402972455'])await assert.rejects(resolve({record:{url}}),e=>e.code==='MEDIA_SOURCE');assert.equal(calls,1);assert.equal(keyCalls,1);assert.equal(canonicalDouyinVideo(dySource+'/').url,dySource);});
test('Douyin detail envelopes require matching string aweme_id; untyped unknown and photo payloads fail closed',()=>{const video={play_addr:{url_list:[dyMedia]}};for(const envelope of [{aweme_detail:{aweme_id:'7448118827402972455',video}},{aweme_details:[{aweme_id:'1111111111111111111',video},{aweme_id:'7448118827402972455',video}]},{aweme_id:'7448118827402972455',video}])assert.equal(normalizeResolvedDouyin({data:envelope},dySource).sourceId,'7448118827402972455');for(const envelope of [{aweme_detail:{aweme_id:'1111111111111111111',video}},{aweme_detail:{aweme_id:7448118827402972455,video}},{unrecognized:{aweme_id:'7448118827402972455',video}}])assert.throws(()=>normalizeResolvedDouyin({data:envelope},dySource),e=>e.code==='MEDIA_IDENTITY');assert.throws(()=>normalizeResolvedDouyin({data:{aweme_detail:{aweme_id:'7448118827402972455',aweme_type:68,images:[{}],video}}},dySource),e=>e.code==='MEDIA_FORMAT');});
test('Douyin media domain policy does not admit origin hosts, lookalikes, HTTP or Instagram CDN',async()=>{assert.equal(validateMediaUrl(dyMedia,{platform:'douyin'}),dyMedia);for(const candidate of ['http://v26.douyinvod.com/synthetic.mp4','https://v26.douyinvod.com.attacker.example/video.mp4','https://www.douyin.com/aweme/v1/play/','https://aweme.snssdk.com/aweme/v1/play/',videoUrl,'https://127.0.0.1/video.mp4'])assert.throws(()=>normalizeResolvedDouyin({data:{aweme_detail:{aweme_id:'7448118827402972455',video:{play_addr:{url_list:[candidate]}}}}},dySource),e=>e.code==='MEDIA_URL');assert.throws(()=>normalizeResolvedInstagram({data:{code:'SYNTHETIC',video_url:dyMedia}},sourceUrl),e=>e.code==='MEDIA_URL');await assert.rejects(verifyMediaAddress(dyMedia,{lookup:async()=>[{address:'169.254.169.254',family:4}]}),e=>e.code==='MEDIA_DNS');});
test('restricted Douyin HTTP 200 is explicit and never falls back or retries',async()=>{let calls=0;const resolve=createMediaResolver({getKey:async()=>'synthetic-key',verify:async()=>{throw Error('must not verify missing video');},fetchImpl:async()=>{calls++;return Response.json({data:{filter_list:[{reason:8}],aweme_details:[]}});}});await assert.rejects(resolve({record:{url:dySource}}),e=>e.code==='MEDIA_UNAVAILABLE'&&e.message.includes('计费'));assert.equal(calls,1);});
test('per-task cache byte limit stays below global cap and signed Douyin URL never enters the manifest',async t=>{const dir=await root(t);const cache=createMediaCache({root:dir,transport:async()=>new Response('123456789',{headers:{'content-type':'video/mp4'}})});await assert.rejects(cache({media:{videoUrl:dyMedia,sourceUrl:dySource},jobId:'bounded-dy',recordId:'dy-test',maxBytes:8}),e=>e.code==='MEDIA_SIZE');const valid=await cache({media:{videoUrl:dyMedia,sourceUrl:dySource},jobId:'valid-dy',recordId:'dy-test',maxBytes:20});assert.equal(valid.bytes,9);assert(!(await readFile(path.join(valid.directory,'cache.json'),'utf8')).includes('signature'));await valid.release();});
