import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {createHistoryStore} from '../src/history-store.mjs';
import {createResearchService} from '../src/research-service.mjs';
const now=()=> '2026-10-10T10:00:00.000Z';
const account={username:'resume_synthetic',url:'https://www.instagram.com/resume_synthetic/'};
const rows=Array.from({length:6},(_,i)=>({url:`https://www.instagram.com/reel/RESUME_${i}/`,publishedAt:'2026-10-09T10:00:00.000Z',likes:100-i,duration:10}));
const draft={requestId:'resume_synthetic_request',source:{kind:'account',url:account.url}};
const failed=()=>({status:'partial',steps:{resolve:{status:'completed',cached:true},asr:{status:'completed'},vl:{status:'received'}},error:{code:'RESEARCH_OUTPUT'},usage:{vl:{total_tokens:15},asr:{duration:10}},visual:null,recommendations:[]});
const note=record=>({status:'completed',steps:{resolve:{status:'completed'},asr:{status:'completed'},vl:{status:'completed'}},usage:{vl:{total_tokens:15},asr:{duration:10}},titleZh:'恢复后的合成画面',tagsZh:['合成'],visual:{observations:[{startSec:0,endSec:10,descriptionZh:'合成恢复证据'}]},recommendations:[{nameZh:'合成方案',status:'conditional',reasonZh:'依据合成观察'}]});
async function setup({recovery='success'}={}){
 const root=await mkdtemp(path.join(os.tmpdir(),'dsh-resume-unstarted-')),history=createHistoryStore({root});let collections=0,analyzes=0,paidVl=0,paidAsr=0,paidResolve=0,comparison=0;const attempts=new Map();
 const service=createResearchService({root,history,now,collectAccount:async()=>{collections++;return{account,samples:rows,collectedAt:now()};},analyzeVideo:async({record,onStage})=>{analyzes++;const count=(attempts.get(record.id)||0)+1;attempts.set(record.id,count);if(record.id==='ig_RESUME_0'&&count>1){if(recovery==='request'){await onStage('analyzing',{step:'vl',status:'requesting'});paidVl++;}if(recovery==='fails')return{...failed(),cached:true};return{...note(record),cached:recovery!=='uncached',steps:{...note(record).steps,resolve:{status:'completed',cached:true}}};}await onStage('resolving_media',{step:'resolve',status:'requesting'});if(record.id!=='ig_RESUME_0')paidResolve++;await onStage('analyzing',{step:'asr',status:'requesting'});paidAsr++;await onStage('analyzing',{step:'vl',status:'requesting'});paidVl++;return record.id==='ig_RESUME_0'?failed():note(record);},compareVideos:async({records})=>{comparison++;return{status:'completed',summaryZh:'合成比较',promptStatus:'completed',recommendations:records.slice(0,3).map(r=>({recordId:r.recordId,reasonZh:'合成理由',formZh:'合成形式',materialThresholdZh:'需要素材',evidence:[{startSec:0,endSec:1}],recreationPackage:{schemaVersion:1,status:'needs-input',fullPromptText:'SYNTHETIC recovered prompt '+r.recordId}})),excluded:records.slice(3).map(r=>({recordId:r.recordId,reasonZh:'合成排除'}))};}});
 const started=await service.startResearch(draft);const job=await service.waitForIdle(started.jobId);assert.equal(job.phase,'partial');assert.equal(job.analysisGate.status,'blocked');
 return{root,history,service,job,args:{jobId:job.jobId,planRevision:job.planRevision},counts:()=>({collections,analyzes,paidVl,paidAsr,paidResolve,comparison})};
}
const request=body=>new Request('http://127.0.0.1:43129/research/resume-unstarted',{method:'POST',headers:{origin:'http://127.0.0.1:43129','content-type':'application/json','x-derek-workbench':'1'},body:JSON.stringify(body)});
async function mutate(root,fn){const file=path.join(root,'research/state.json'),state=JSON.parse(await readFile(file,'utf8'));fn(state);await writeFile(file,JSON.stringify(state));}

test('explicit resume locally recovers first response and starts only the five never-requested videos',async()=>{
 const {service,args,job:before,counts}=await setup();const frozen=structuredClone(before.plan),metadata=structuredClone(before.selectedMetadata);
 const replies=await Promise.all([service.handlers.resumeUnstarted(request(args)),service.handlers.resumeUnstarted(request(args))]);assert.ok(replies.every(r=>r.status===200));const bodies=await Promise.all(replies.map(r=>r.json()));assert.equal(bodies.filter(r=>!r.duplicate).length,1);const after=await service.waitForIdle(args.jobId);assert.equal(after.phase,'completed');assert.deepEqual(after.plan,frozen);assert.deepEqual(after.selectedMetadata,metadata);assert.equal(after.results.length,6);assert.equal(new Set(after.results.map(r=>r.recordId)).size,6);assert.equal(after.actualUsage.records.length,6);assert.equal(after.styleCandidates.length,6);assert.equal(new Set(after.styleCandidates.map(c=>c.candidateId)).size,6);assert.equal(after.actualUsage.mediaResolutionCacheHits,1);assert.equal(after.actualUsage.providerCalls.mediaResolution,5);assert.equal(after.actualUsage.providerCalls.tikhub,6);assert.equal(after.actualUsage.providerCalls.vl,6);assert.equal(after.actualUsage.providerCalls.asr,6);assert.deepEqual(counts(),{collections:1,analyzes:7,paidVl:6,paidAsr:6,paidResolve:5,comparison:1});assert.equal((await service.resumeUnstarted(args)).duplicate,true);await service.waitForIdle();assert.equal(counts().paidVl,6);assert.equal(counts().comparison,1);
});

test('failed free normalization stops at the first gate again and never starts the remaining five',async()=>{const {service,args,counts}=await setup({recovery:'fails'});await service.resumeUnstarted(args);const job=await service.waitForIdle(args.jobId);assert.equal(job.phase,'partial');assert.equal(job.videos.filter(v=>v.status==='blocked').length,5);assert.equal(job.results.length,1);assert.equal(job.actualUsage.records.length,1);assert.equal(job.actualUsage.mediaResolutionCacheHits,1);assert.equal(job.actualUsage.providerCalls.mediaResolution,0);assert.deepEqual(counts(),{collections:1,analyzes:2,paidVl:1,paidAsr:1,paidResolve:0,comparison:0});assert.equal((await service.resumeUnstarted(args)).duplicate,true);});

test('a first-video analyzer attempt to replay any paid request is rejected before the provider call',async()=>{const {service,args,counts}=await setup({recovery:'request'});await service.resumeUnstarted(args);const job=await service.waitForIdle(args.jobId);assert.equal(job.phase,'partial');assert.equal(job.analysisGate.status,'blocked');assert.equal(job.errors.at(-1).code,'RESEARCH_RESUME_PAID');assert.equal(counts().paidVl,1);assert.equal(counts().paidAsr,1);assert.equal(counts().analyzes,2);assert.equal(job.videos.filter(v=>v.status==='blocked').length,5);});

test('analyzer output must explicitly be cached before the remaining batch can continue',async()=>{const {service,args,counts}=await setup({recovery:'uncached'});await service.resumeUnstarted(args);const job=await service.waitForIdle(args.jobId);assert.equal(job.phase,'partial');assert.equal(job.errors.at(-1).code,'RESEARCH_RESUME_CACHE');assert.equal(counts().paidVl,1);assert.equal(counts().analyzes,2);});

test('foreign origins and missing workbench intent header cannot invoke resume',async()=>{const {service,args,counts}=await setup();for(const headers of [{origin:'https://foreign.test','x-derek-workbench':'1'},{origin:'http://127.0.0.1:43129'}]){const response=await service.handlers.resumeUnstarted(new Request('http://127.0.0.1:43129/research/resume-unstarted',{method:'POST',headers:{...headers,'content-type':'application/json'},body:JSON.stringify(args)}));assert.equal(response.status,403);}assert.equal(counts().analyzes,1);});

test('stale revision, changed hash, cancellation, missing received response, or started remaining videos refuse resume',async()=>{
 const mutations=[['RESEARCH_STALE',state=>state.plans[0].planRevision++],['RESEARCH_STALE',state=>state.plans[0].planHash='changed'],['RESEARCH_CANCELLED',state=>state.jobs[0].cancelRequested=true],['RESEARCH_RESUME_STATE',state=>state.jobs[0].results[0].result.steps.vl.status='requesting'],['RESEARCH_RESUME_STATE',state=>state.jobs[0].results[0].result.error.code='MOSI_TIMEOUT'],['RESEARCH_RESUME_STARTED',state=>state.jobs[0].events.push({phase:'analyzing',at:now(),detail:{recordId:'ig_RESUME_1',step:'vl',status:'requesting'}})],['RESEARCH_RESUME_STARTED',state=>state.jobs[0].results.push({recordId:'ig_RESUME_1',result:note({id:'ig_RESUME_1'})})]];
 for(const [code,change] of mutations){const {root,service,args,counts}=await setup();await mutate(root,change);await assert.rejects(service.resumeUnstarted(args),{code});assert.equal(counts().analyzes,1);}
});

test('hidden or trashed selected videos block resume without exposing saved evidence',async()=>{for(const action of ['hide','trash']){const {service,args,history,counts}=await setup();await history.mutate({action,ids:['ig_RESUME_3']});await assert.rejects(service.resumeUnstarted(args),{code:'RESEARCH_HIDDEN'});assert.equal(counts().analyzes,1);}});
