import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';
import {createHistoryStore} from '../src/history-store.mjs';
import {previousCompleteWeek,lastSevenDays,prepareReview,savePreparedReview,previewReview,weeklyReviewMain} from '../scripts/weekly-review.mjs';
const account={username:'weeklysynthetic',url:'https://www.instagram.com/weeklysynthetic/'};
async function fixture(){const dataRoot=await mkdtemp(path.join(os.tmpdir(),'weekly-synthetic-')),store=createHistoryStore({root:dataRoot});await store.ingest({account,collectedAt:'2026-10-06T01:00:00Z',provider:'synthetic',samples:['Visible','Hidden','Trashed'].map(code=>({url:`https://www.instagram.com/reel/${code}/`,title:code+' synthetic',views:1}))});await store.mutate({action:'hide',ids:['ig_Hidden']});await store.mutate({action:'trash',ids:['ig_Trashed']});return{dataRoot,store};}
test('previous complete week is Monday midnight China time, independent of host timezone',()=>{assert.deepEqual(previousCompleteWeek('2026-10-12T01:00:00Z'),{periodStart:'2026-10-04T16:00:00.000Z',periodEnd:'2026-10-11T16:00:00.000Z',timezone:'Asia/Shanghai'});assert.equal(previousCompleteWeek('2026-10-11T15:59:59Z').periodEnd,'2026-10-04T16:00:00.000Z');assert.equal(previousCompleteWeek('2026-10-11T16:00:00Z').periodEnd,'2026-10-11T16:00:00.000Z');assert.throws(()=>previousCompleteWeek('invalid'),/时间/);});
test('preview time window is precisely the last seven days',()=>{const range=lastSevenDays('2026-10-10T06:00:00Z');assert.equal(range.periodStart,'2026-10-03T06:00:00.000Z');assert.equal(range.periodEnd,'2026-10-10T06:00:00.000Z');});
test('prepare writes only active metadata to a private local snapshot and excludes hidden/trash',async()=>{const{dataRoot}=await fixture();const result=await prepareReview({dataRoot,now:'2026-10-12T01:00:00Z'}),raw=await readFile(result.sourcePath,'utf8'),source=JSON.parse(raw);assert.equal(source.records.length,1);assert.equal(source.records[0].id,'ig_Visible');assert(!raw.includes('Hidden synthetic'));assert(!raw.includes('Trashed synthetic'));assert(!raw.includes('source.mp4'));assert(!raw.includes('apiKey'));assert.equal(result.networkRequests,0);assert.equal(result.modelCalls,0);assert(result.sourcePath.startsWith(path.join(dataRoot,'library/review-drafts')));});
test('prepared weekly markdown saves source IDs and survives reopen; hidden source restricts old report',async()=>{const{dataRoot,store}=await fixture();const prepared=await prepareReview({dataRoot,now:'2026-10-12T01:00:00Z'}),markdownPath=path.join(dataRoot,'synthetic-weekly.md');await writeFile(markdownPath,'# 合成周报\n暂无成功成片证据。');const saved=await savePreparedReview({dataRoot,sourcePath:prepared.sourcePath,markdownPath});const reopened=createHistoryStore({root:dataRoot}),report=await reopened.readReview(saved.reviewId);assert.equal(report.kind,'codex-weekly');assert.deepEqual(report.recordIds,['ig_Visible']);assert(report.markdown.includes('暂无成功'));await store.mutate({action:'hide',ids:['ig_Visible']});assert.equal((await reopened.snapshot()).reviews[0].restricted,true);await assert.rejects(reopened.readReview(saved.reviewId),e=>e.code==='HISTORY_REVIEW_HIDDEN');});
test('changed library revision rejects prepared output without saving a misleading report',async()=>{const{dataRoot,store}=await fixture();const prepared=await prepareReview({dataRoot,now:'2026-10-12T01:00:00Z'}),markdownPath=path.join(dataRoot,'synthetic.md');await writeFile(markdownPath,'Synthetic');await store.mutate({action:'favorite',ids:['ig_Visible']});await assert.rejects(savePreparedReview({dataRoot,sourcePath:prepared.sourcePath,markdownPath}),e=>e.code==='HISTORY_STALE');assert.equal((await store.snapshot()).reviews.length,0);});
test('deterministic preview explicitly records no verified successes or new model activity',async()=>{const{dataRoot,store}=await fixture();const out=await previewReview({dataRoot,now:'2026-10-10T06:00:00Z'}),report=await store.readReview(out.reviewId);assert.equal(report.kind,'local-summary');assert.equal(out.counts.reportedSuccesses,0);assert.equal(out.counts.verifiedSuccesses,0);assert(report.markdown.includes('尚不能归纳'));assert(report.markdown.includes('没有调用分析模型'));assert(!report.markdown.includes('Hidden synthetic'));assert.equal(out.networkRequests,0);});
test('CLI argument path supports injected synthetic roots and rejects malformed commands',async()=>{const{dataRoot}=await fixture();const result=await weeklyReviewMain(['prepare','--data-root',dataRoot,'--now','2026-10-12T01:00:00Z']);assert.equal(result.action,'prepare');await assert.rejects(weeklyReviewMain(['publish']),/用法/);await assert.rejects(weeklyReviewMain(['prepare','--token','secret']),/不支持/);await assert.rejects(weeklyReviewMain(['save','--data-root',dataRoot]),/需要/);});
