const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list=value=>Array.isArray(value)?value:[];
const prose=value=>typeof value==='string'?value:typeof value==='number'?String(value):'';
const number=value=>typeof value==='number'&&Number.isFinite(value)?Math.round(value*100)/100:'未测量';
const json=value=>JSON.stringify(value??{},null,2);
export function analysisStatus(value){const status=value?.status;return ['completed','existing','available','complete'].includes(status)?'completed':['notstarted','not-started','pending'].includes(status)?'not-started':status||'not-started';}
export function renderAnalysis(payload,{recordTitle='视频分析'}={}){
 const E=escape,state=analysisStatus(payload),result=payload?.result||payload?.analysis||{},visual=result.visual||{},rhythm=result.rhythm||{},audio=result.audio||{},measurements=rhythm.measurements||{},inference=rhythm.modelInference||{};
 if(state==='running')return '<section class="hl-analysis-state" role="status"><span class="hl-eyebrow">正在分析</span><h3>正在读取画面与声音</h3><p>结果会保存在这条视频里。此页面只检查进度，不会重复提交分析。</p></section>';
 if(state==='failed')return `<section class="hl-analysis-state"><h3>这次分析未完成</h3><p>${E(prose(payload?.error?.message)||prose(payload?.error)||'服务暂时未返回完整结果。')}</p><p>已返回的步骤与用量保留在来源记录中。再次分析前会重新确认。</p>${source(payload)}</section>`;
 if(!['completed','partial'].includes(state))return '<section class="hl-analysis-state"><h3>把这条参考看明白</h3><p>先写下这次想参考什么，再分析画面、节奏和声音。结果会留在当前视频中。</p></section>';
 const title=prose(result.titleZh)||recordTitle;
 return `<section class="hl-analysis" aria-label="中文视频分析">${state==='partial'?'<div class="hl-notice">部分完成：已保留可用笔记，未完成的步骤没有自动重试。</div>':''}${payload?.intentMismatch||payload?.requiresExplicitReanalysis?`<div class="hl-notice" role="status">${E(payload.noteZh||'已有结果基于另一个分析重点；本次未重新调用。')}</div>`:''}<div class="hl-analysis-intro"><span class="hl-eyebrow">模思分析 · 已保存</span><h3>${E(title)}</h3>${result.summaryZh?`<p>${E(result.summaryZh)}</p>`:''}<div class="hl-tags">${list(result.tagsZh).map(t=>`<span># ${E(prose(t))}</span>`).join('')}</div>${payload.intent?`<div class="hl-intent"><b>这次参考重点</b><p>${E(payload.intent)}</p></div>`:''}</div>
 <section class="hl-analysis-section"><div class="hl-section-heading"><h3>画面观测</h3><span class="hl-badge">模型观察 · 待核对</span></div>${visual.summaryZh?`<p>${E(visual.summaryZh)}</p>`:''}${list(visual.observations).length?`<ol class="hl-observations">${list(visual.observations).map(o=>`<li><span>${typeof o.startSec==='number'?E(number(o.startSec))+' 秒'+(typeof o.endSec==='number'?' – '+E(number(o.endSec))+' 秒':''):'画面观察'}</span><p>${E(prose(o.descriptionZh)||prose(o.observation)||prose(o))}</p></li>`).join('')}</ol>`:'<p>这次结果没有提供逐段画面观测。</p>'}${list(visual.structure).length?`<details><summary>查看结构分段 · 模型推断</summary><ol>${list(visual.structure).map(s=>`<li><b>${E(s.rangeZh)}</b> ${E(s.purposeZh)}</li>`).join('')}</ol></details>`:''}</section>
 <section class="hl-analysis-section"><div class="hl-section-heading"><h3>节奏与切镜</h3><span class="hl-badge">本机机器测量</span></div><div class="hl-measurements"><div><b>${E(number(measurements.durationSec))}</b><span>视频时长 / 秒</span></div><div><b>${E(number(measurements.medianShotSec))}</b><span>候选镜头中位时长 / 秒</span></div><div><b>${Array.isArray(measurements.candidateCutsSec)?measurements.candidateCutsSec.length:E(number(measurements.candidateCutCount))}</b><span>候选切镜位置</span></div></div><p class="hl-small">机器检测的切镜位置可能漏掉渐变或相似画面，需要结合原片核对。</p>${list(measurements.candidateCutsSec).length?`<details><summary>查看候选切镜时间</summary><p>${measurements.candidateCutsSec.map(v=>E(number(v))).join('、')} 秒</p></details>`:''}${inference.summaryZh?`<div class="hl-inference"><span class="hl-badge">模型推断 · 不属于机器测量</span><p>${E(inference.summaryZh)}</p></div>`:''}</section>
 <section class="hl-analysis-section"><div class="hl-section-heading"><h3>声音与字幕</h3><span class="hl-badge">ASR 识别</span></div>${audio.hasAudio===false?'<p>这条视频没有音轨。</p>':audio.hasSpeech===false?'<p>没有识别到可用语音；视频可能只有音乐或环境声。</p>':audio.text?`<p class="hl-transcript">${E(audio.text)}</p>`:'<p>没有可展示的语音字幕。</p>'}${audio.noteZh?`<p class="hl-small">${E(audio.noteZh)}</p>`:''}${list(audio.segments).length?`<details><summary>查看带时间的字幕 · ${audio.segments.length} 段</summary><ol class="hl-observations">${audio.segments.map(s=>`<li><span>${E(number(s.start))} – ${E(number(s.end))} 秒${s.speaker?' · '+E(s.speaker):''}</span><p>${E(s.text)}</p></li>`).join('')}</ol></details>`:''}</section>
 ${list(result.styleSuggestions).length?`<details class="hl-analysis-section"><summary>参考建议 · 模型推断候选</summary>${result.styleSuggestions.map(s=>`<article class="hl-suggestion"><h4>${E(s.nameZh)}</h4><p>${E(s.reasonZh)}</p><ul>${list(s.rulesZh).map(rule=>`<li>${E(prose(rule))}</li>`).join('')}</ul>${s.caveatZh?`<p>${E(s.caveatZh)}</p>`:''}</article>`).join('')}</details>`:''}${source(payload)}</section>`;
}
function source(payload){const E=escape;return `<details class="hl-analysis-section hl-analysis-source"><summary>模型、用量与来源</summary><p>服务：${E(payload?.provider||'mosi')} · ${payload?.cached?'读取本机缓存':'已保存的分析记录'}</p>${payload?.completedAt?`<p>完成时间：${E(payload.completedAt)}</p>`:''}${Object.entries(payload?.steps||{}).map(([key,step])=>`<div><b>${key==='asr'?'语音识别':key==='vl'?'画面分析':E(key)} · ${E(step?.model||'未记录模型')}</b><p>步骤状态：${E(({completed:'已完成',running:'进行中',failed:'未完成',skipped:'已跳过'})[step?.status]||step?.status||'未记录')}</p><pre>${E(json(step?.usage||{}))}</pre>${step?.error?`<p>${E(prose(step.error?.message)||prose(step.error))}</p>`:''}</div>`).join('')}<p class="hl-small">用量来自服务返回；未返回价格时不估算费用。模型观察和建议需要结合原片核对。</p></details>`;}
