import https from 'node:https';
import {lookup as dnsLookup} from 'node:dns/promises';
import {isIP,BlockList} from 'node:net';
import {parseDouyin} from './douyin-source.mjs';

const HOSTS=new Set(['v.douyin.com','douyin.com','www.douyin.com','iesdouyin.com','www.iesdouyin.com']);
const REDIRECTS=new Set([301,302,303,307,308]);
const MESSAGES={DOUYIN_SHARE_AMBIGUOUS:'分享文字包含多个不同的抖音短链，请每次提供一个。',DOUYIN_SHARE_INPUT:'请提供 https://v.douyin.com/… 短链或包含唯一短链的分享文字。',DOUYIN_SHARE_HOST:'分享跳转超出允许的抖音 HTTPS 域，已停止。请补充完整账号或视频链接。',DOUYIN_SHARE_DNS:'分享地址不能安全解析到公开网络，未访问该地址。请补充完整账号或视频链接。',DOUYIN_SHARE_NETWORK:'抖音短链没有返回可确认的跳转，未调用 TikHub。请补充完整账号或视频链接。',DOUYIN_SHARE_TIMEOUT:'抖音短链展开超时，未自动重试或调用 TikHub。请补充完整账号或视频链接。',DOUYIN_SHARE_LIMIT:'抖音短链跳转过多或形成循环，已停止。请补充完整账号或视频链接。',DOUYIN_SHARE_PAGE:'短链没有提供可读取的 HTTP 跳转，可能依赖页面脚本。请补充完整 www.douyin.com/user/… 或 /video/… 链接。',DOUYIN_SHARE_IMAGE:'这个分享指向图文内容；当前研究需要视频或账号主页链接。'};
export function douyinShareError(code,status=502){return Object.assign(new Error(MESSAGES[code]||MESSAGES.DOUYIN_SHARE_NETWORK),{code,status,safeStatus:status});}
const asciiUrlTokens=value=>String(value).match(/https?:\/\/[^\s<>"'\u3000-\u303f\uff00-\uffef]+/gi)||[];
/** Pure parsing only. Provider permissions and credentials are not touched. */
export function parseDouyinShare(value){if(typeof value!=='string'||value.length>20000)return null;const urls=new Set();for(const token of asciiUrlTokens(value)){let url;try{url=new URL(token.replace(/[.,;!?)\]}]+$/g,''));}catch{continue;}if(url.protocol!=='https:'||url.hostname.toLowerCase()!=='v.douyin.com'||url.username||url.password||url.port)continue;const match=/^\/([A-Za-z0-9_-]{3,100})\/?$/.exec(url.pathname);if(match)urls.add('https://v.douyin.com/'+match[1]+'/');}if(urls.size>1)throw douyinShareError('DOUYIN_SHARE_AMBIGUOUS',400);return urls.size?{kind:'douyin-share',platform:'Douyin',url:[...urls][0]}:null;}
function allowedUrl(value){let url;try{url=new URL(value);}catch{throw douyinShareError('DOUYIN_SHARE_HOST',400);}if(url.protocol!=='https:'||url.username||url.password||url.port||!HOSTS.has(url.hostname.toLowerCase())||url.href.length>8192)throw douyinShareError('DOUYIN_SHARE_HOST',400);url.hash='';return url;}
// TikHub's cached OpenAPI get_all_aweme_id documents /share/video/<id>.
// /share/user/<secUid> is accepted only with the same strict canonical secUid
// shape; its live redirect form remains unverified (never infer from HTML/uid).
function canonicalShareTarget(url){const direct=parseDouyin(url.href);if(direct)return direct;if(!['iesdouyin.com','www.iesdouyin.com'].includes(url.hostname.toLowerCase()))return null;const match=/^\/share\/(user|video)\/([A-Za-z0-9_-]+)\/?$/.exec(url.pathname);return match&&!(match[1]==='user'&&/^\d+$/.test(match[2]))?parseDouyin('https://www.douyin.com/'+match[1]+'/'+match[2]):null;}
const blocked4=new BlockList();for(const [address,prefix] of [['0.0.0.0',8],['10.0.0.0',8],['100.64.0.0',10],['127.0.0.0',8],['169.254.0.0',16],['172.16.0.0',12],['192.0.0.0',24],['192.0.2.0',24],['192.168.0.0',16],['198.18.0.0',15],['198.51.100.0',24],['203.0.113.0',24],['224.0.0.0',4],['240.0.0.0',4]])blocked4.addSubnet(address,prefix,'ipv4');
const global6=new BlockList();global6.addSubnet('2000::',3,'ipv6');const blocked6=new BlockList();for(const [address,prefix] of [['2001::',32],['2001:db8::',32],['2001:10::',28],['2001:20::',28],['2002::',16],['3fff::',20]])blocked6.addSubnet(address,prefix,'ipv6');
function isPublicAddress(address){const family=isIP(address);return family===4?!blocked4.check(address,'ipv4'):family===6&&global6.check(address,'ipv6')&&!blocked6.check(address,'ipv6');}
async function publicAddresses(hostname,lookup){let addresses;try{addresses=await lookup(hostname,{all:true,verbatim:true});}catch{throw douyinShareError('DOUYIN_SHARE_DNS');}if(!Array.isArray(addresses)||!addresses.length||addresses.some(x=>!isPublicAddress(x.address)||isIP(x.address)!==Number(x.family)))throw douyinShareError('DOUYIN_SHARE_DNS');return addresses;}
// Read only HTTP headers. GET is used because some short-link services do not
// implement HEAD; destroy the response as soon as headers arrive, without
// accumulating HTML, scripts, cookies, or a media body. DNS is already pinned.
export function requestDouyinShareHeaders(value,{addresses,signal}={}){const url=allowedUrl(value);if(!Array.isArray(addresses)||!addresses.length||addresses.some(x=>!isPublicAddress(x.address)||isIP(x.address)!==Number(x.family)))return Promise.reject(douyinShareError('DOUYIN_SHARE_DNS'));return new Promise((resolve,reject)=>{let settled=false;const finish=(error,result)=>{if(settled)return;settled=true;error?reject(error):resolve(result);};const chosen=addresses[0];const request=https.get(url,{agent:false,signal,headers:{accept:'text/html','user-agent':'DSH-Research/0.6.0'},lookup:(_hostname,options,callback)=>options?.all?callback(null,[chosen]):callback(null,chosen.address,Number(chosen.family))},response=>{const result={status:response.statusCode,location:typeof response.headers.location==='string'?response.headers.location:null};response.destroy();finish(null,result);});request.on('error',()=>finish(douyinShareError(signal?.aborted?'DOUYIN_SHARE_TIMEOUT':'DOUYIN_SHARE_NETWORK')));});}
/**
 * Call only after a user-confirmed plan. This performs at most three free
 * HTTP redirects, never TikHub or another provider request. Injected request
 * receives only a validated URL, validated pinned addresses, and an abort signal.
 */
export async function resolveDouyinShare(value,{request=requestDouyinShareHeaders,lookup=dnsLookup,timeoutMs=10000,maxRedirects=3}={}){const parsed=parseDouyinShare(typeof value==='object'?value?.url:value);if(!parsed)throw douyinShareError('DOUYIN_SHARE_INPUT',400);if(!Number.isInteger(maxRedirects)||maxRedirects<1||maxRedirects>3||!Number.isFinite(timeoutMs)||timeoutMs<=0||timeoutMs>30000)throw douyinShareError('DOUYIN_SHARE_INPUT',400);const controller=new AbortController();let timer;const timedOut=new Promise((_,reject)=>{timer=setTimeout(()=>{controller.abort();reject(douyinShareError('DOUYIN_SHARE_TIMEOUT'));},timeoutMs);});const bounded=task=>Promise.race([task,timedOut]);const seen=new Set();let current=parsed.url,redirectCount=0;try{for(;;){const url=allowedUrl(current);if(seen.has(url.href))throw douyinShareError('DOUYIN_SHARE_LIMIT');seen.add(url.href);const addresses=await bounded(publicAddresses(url.hostname,lookup));const canonical=canonicalShareTarget(url);if(canonical)return {...canonical,sourceShareUrl:parsed.url,redirectCount};if(/^\/(?:note|share\/note)\//.test(url.pathname))throw douyinShareError('DOUYIN_SHARE_IMAGE',400);if(redirectCount>=maxRedirects)throw douyinShareError('DOUYIN_SHARE_LIMIT');let response;try{response=await bounded(request(url.href,{addresses,signal:controller.signal}));}catch(error){throw error?.code&&Object.hasOwn(MESSAGES,error.code)?error:douyinShareError('DOUYIN_SHARE_NETWORK');}if(!REDIRECTS.has(response?.status)){if(response?.status===200)throw douyinShareError('DOUYIN_SHARE_PAGE',409);throw douyinShareError('DOUYIN_SHARE_NETWORK');}if(typeof response.location!=='string'||!response.location.trim()||response.location.length>8192)throw douyinShareError('DOUYIN_SHARE_PAGE',409);let target;try{target=new URL(response.location,url);}catch{throw douyinShareError('DOUYIN_SHARE_HOST',400);}current=allowedUrl(target.href).href;redirectCount++;}}
 finally{clearTimeout(timer);controller.abort();}}
