import {createHash,randomUUID} from 'node:crypto';
import {createResearchStore,researchProblem,validResearchId} from './research-store.mjs';
import {canonicalHistoryUrl} from './history-store.mjs';
import {parseInstagram} from './account-core.mjs';
import {parseDouyin} from './douyin-source.mjs';
import {normalizeResearchSource,sourceCapability} from './source-capabilities.mjs';
import {sameOrigin} from './request-origin.mjs';

const runtimes=new Map(),installed=new WeakMap();
const terminal=new Set(['completed','partial','failed','cancelled']);
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const stages=new Set(['confirmed','collecting','selecting','resolving_media','analyzing','synthesizing']);
const hash=value=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const clone=value=>structuredClone(value);
const text=(value,max=2000)=>typeof value==='string'?value.trim().slice(0,max):'';
const fail=(code,message,status=400)=>{throw researchProblem(code,message,status);};
const safeDate=value=>typeof value==='string'&&Number.isFinite(Date.parse(value))?new Date(value).toISOString():null;
function processAlive(pid){if(!Number.isSafeInteger(pid)||pid<=0)return false;try{process.kill(pid,0);return true;}catch(error){return error.code!=='ESRCH';}}
const obj=value=>value&&typeof value==='object'&&!Array.isArray(value);
const hasVisualEvidence=result=>result?.steps?.vl?.status==='completed'&&Array.isArray(result?.visual?.observations)&&result.visual.observations.some(o=>Number.isFinite(o.startSec)&&o.startSec>=0&&Number.isFinite(o.endSec)&&o.endSec>o.startSec&&typeof o.descriptionZh==='string'&&o.descriptionZh.trim());
const recordIdsFromSource=source=>source.kind==='videos'?source.urls.map(url=>canonicalHistoryUrl(url).id):[];
const safeError=error=>({code:typeof error?.code==='string'&&/^(?:RESEARCH|ANALYSIS|MOSI|MEDIA|TIKHUB|DOUYIN)_[A-Z0-9_]+$/.test(error.code)?error.code:'RESEARCH_STEP_FAILED',message:typeof error?.code==='string'&&(/^(?:RESEARCH|DOUYIN)_/.test(error.code))?error.message:'此阶段未完成；已保留成功结果，不会自动重试或更换服务。',billingUnknown:error?.billingUnknown===true||error?.code==='MOSI_TIMEOUT'});
function id(value,label){if(!validResearchId(value))fail('RESEARCH_ID',`${label}标识无效。`);return value;}
function owned(value,scope={}){if(scope.sessionId&&(value.sessionId!==scope.sessionId||scope.workbenchId&&value.workbenchId!==scope.workbenchId))fail('RESEARCH_OWNER','此研究不属于当前工作台会话。',403);return value;}
function normalizePlan(payload){
 const source=normalizeResearchSource(payload.source),userIntent=text(payload.userIntent||payload.goal,5000);if(!userIntent)fail('RESEARCH_INTENT','请先说明这次想研究什么。');
 const executionMode=payload.executionMode??'research';if(!['research','planning-only','candidate-selection'].includes(executionMode))fail('RESEARCH_EXECUTION_MODE','执行模式需要选择正式研究、先看八条候选或仅保存理解卡。');
 const supplied=obj(payload.selectionPolicy)?payload.selectionPolicy:{},mode=supplied.mode||(source.kind!=='videos'?'latest':'user-picked'),count=supplied.count??(source.kind!=='videos'?2:source.urls.length);
 if(!['latest','top-in-window','user-picked'].includes(mode)||!Number.isInteger(count)||count<1||count>2)fail('RESEARCH_SELECTION','选片数量应为一到两条。');
 if(source.kind!=='videos'&&mode==='user-picked'||source.kind==='videos'&&mode!=='user-picked'||source.kind==='videos'&&count>source.urls.length)fail('RESEARCH_SELECTION','选片方式与来源不一致。');
 if(executionMode==='candidate-selection'&&source.kind==='videos')fail('RESEARCH_SELECTION','八条候选模式需要账号主页或待展开的抖音分享链接。');
 const candidateLimit=executionMode==='candidate-selection'?8:null;if(payload.candidateLimit!==undefined&&payload.candidateLimit!==null&&payload.candidateLimit!==8)fail('RESEARCH_SELECTION','当前候选预览上限为八条。');
 const selectionPolicy={mode,count};if(mode==='top-in-window'){const start=safeDate(supplied.windowStart),end=safeDate(supplied.windowEnd);if(!start||!end||start>=end||!['views','likes'].includes(supplied.metric))fail('RESEARCH_SELECTION','数据优先需要明确起止时间和播放或点赞指标。');Object.assign(selectionPolicy,{metric:supplied.metric,windowStart:start,windowEnd:end});}
 const focus=payload.analysisFocus??['开头叙事','画面风格','剪辑节奏','人声与字幕'];if(!Array.isArray(focus)||focus.length>12||focus.some(x=>typeof x!=='string'||x.length>100))fail('RESEARCH_FOCUS','分析重点格式无效。');
 const material=obj(payload.materialStatus)?payload.materialStatus:{state:'unprovided',description:text(payload.assets,3000)};if(!['unprovided','none','provided','unknown'].includes(material.state))fail('RESEARCH_MATERIALS','素材状态无效。');
 const capability=sourceCapability(source),researching=executionMode!=='planning-only',callCount=researching?count:0,accountPages=researching&&source.kind!=='videos'?1:0;
 const budgetScope={providers:researching?['tikhub','mosi']:[],maxVideos:callCount,maxAccountPages:accountPages,maxResolveCalls:callCount,maxVlCalls:callCount,maxAsrCalls:callCount,maxDurationSecPerVideo:600,maxBytesPerVideo:209715200,autoRetry:false,generationEnabled:false};
 const estimatedCalls={accountList:accountPages,mediaResolution:callCount,vl:callCount,asrUpTo:callCount};
 const knownInstagramPrice=capability.available&&capability.platform==='Instagram';
 const pricingEstimate={asOf:'2026-10-10',kind:'display-estimate-not-spending-limit',tikhub:{unitPriceUsd:knownInstagramPrice?0.008:null,maxCalls:accountPages+callCount,estimatedMaxUsd:researching&&!knownInstagramPrice?null:Number(((accountPages+callCount)*0.008).toFixed(3)),pricingStatus:knownInstagramPrice?'snapshot':'unverified',noteZh:knownInstagramPrice?'按 Instagram 接口价格快照估算。':'此来源接口单价尚未核验，不沿用 Instagram 单价；未接通的平台不会调用。'},asr:{hourlyPriceCny:2,maxDurationSec:callCount*budgetScope.maxDurationSecPerVideo,estimatedMaxCny:Math.ceil(callCount*budgetScope.maxDurationSecPerVideo/3600*2*1000)/1000},vl:{pricingStatus:researching?'limited-time-free':'not-called',estimatedMaxCny:researching?null:0,guaranteedPrice:false},noteZh:researching?'以上是 2026-10-10 已知价格快照与输入上限推算（抖音单价待核验），不是费用保证或总额授权上限。VL 当期为限时免费，后续价格与 token 用量可能变化；以供应商账单为准。宿主文字对话费用不包含在视频研究估算中。':'仅保存理解卡，不采集视频、不调用 TikHub 或模思。宿主文字对话本身按已配置模型计费。'};

 return{executionMode,candidateLimit,sourceCapability:capability,initialEstimatedCalls:executionMode==='candidate-selection'?{accountList:accountPages,mediaResolution:0,vl:0,asrUpTo:0}:estimatedCalls,topicId:payload.topicId?id(payload.topicId,'专题'):null,topicTitle:text(payload.topicTitle,120),source,userIntent,product:text(payload.product,2000),audience:text(payload.audience,2000),productProfileVersion:text(payload.productProfileVersion,120)||null,analysisFocus:[...new Set(focus.map(v=>v.trim()).filter(Boolean))],selectionPolicy,materialStatus:{state:material.state,description:text(material.description,3000)},styleVersionId:payload.styleVersionId?id(payload.styleVersionId,'风格版本'):null,exclusions:text(payload.exclusions,2000),budgetScope,estimatedCalls,pricingEstimate,modelPolicy:{visual:'moss-vl-1.0',speech:'moss-transcribe-diarize-pro',text:'host-authorized-model-only'},scopeNoteZh:executionMode==='candidate-selection'?'首次确认只读取一页元数据并展示最多八条候选，不下载或分析视频；由你再选一到两条后才深拆。':researching?'只研究最多两条视频，每条最多 10 分钟、200 MiB；不生成视频，失败不自动重试。':'仅确认并保存理解卡；不抓取、不分析、不生成视频。'};
}
/** Deterministic candidate selection. Counts describe the fetched page, never the entire account. */
export function selectResearchSamples(samples,policy,{now=new Date().toISOString(),hasMore=false}={}){
 const unique=new Map();for(const sample of samples||[]){try{const c=canonicalHistoryUrl(sample.url);if(!unique.has(c.id))unique.set(c.id,{...sample,id:c.id,url:c.url});}catch{}}
 const all=[...unique.values()],validTime=all.filter(s=>safeDate(s.publishedAt)&&Date.parse(s.publishedAt)<=Date.parse(now)),missingTimestampCount=all.length-validTime.length;
 let eligible=validTime,missingMetricCount=0;
 if(policy.mode==='top-in-window'){eligible=validTime.filter(s=>safeDate(s.publishedAt)>=policy.windowStart&&safeDate(s.publishedAt)<policy.windowEnd);missingMetricCount=eligible.filter(s=>!Number.isFinite(s[policy.metric])||s[policy.metric]<0).length;eligible=eligible.filter(s=>Number.isFinite(s[policy.metric])&&s[policy.metric]>=0).sort((a,b)=>b[policy.metric]-a[policy.metric]||Date.parse(b.publishedAt)-Date.parse(a.publishedAt)||a.id.localeCompare(b.id));}
 else if(policy.mode==='latest')eligible.sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)||a.id.localeCompare(b.id));
 else eligible=all;
 const selected=eligible.slice(0,policy.count),coverage={scope:'fetched-page-only',candidateCount:all.length,eligibleCount:eligible.length,selectedCount:selected.length,requestedCount:policy.count,missingTimestampCount:policy.mode==='user-picked'?0:missingTimestampCount,missingMetricCount,hasMore:Boolean(hasMore),completeAccountCoverage:false,noteZh:policy.mode==='user-picked'?'按用户指定的视频顺序处理。':'仅在本次取得的一页候选中选择，不代表账号完整排行。'};
 return{selected,coverage};
}
export function createResearchService({root,history,collectAccount,resolveSource,analyzeVideo,now=()=>new Date().toISOString(),isAllowed=sameOrigin}={}){
 if(!history)throw new TypeError('Research requires the existing history store');
 const store=createResearchStore({root,now});let runtime=runtimes.get(store.root);if(!runtime){runtime={ready:null,running:null,pending:false};runtimes.set(store.root,runtime);}
 const active=()=>history.snapshot({view:'active'});
 async function ready(){if(!runtime.ready)runtime.ready=(async()=>{if(await store.executorActive())return;await store.transaction(state=>{for(const job of state.jobs){if(terminal.has(job.phase)||job.phase==='waiting_selection'||processAlive(job.executionOwnerPid))continue;job.phase=job.results.length?'partial':'failed';job.error={code:'RESEARCH_INTERRUPTED',message:'应用上次退出时研究未完成；已保留结果。为避免重复收费，没有自动重发。',billingUnknown:job.events.some(e=>e.detail?.status==='requesting')};job.updatedAt=now();job.events.push({phase:job.phase,at:now(),detail:job.error});}return{};});})();return runtime.ready;}
 async function visible(ids){const snap=await active(),set=new Set(snap.records.map(r=>r.id));return ids.every(id=>set.has(id));}
 async function checkSource(source){const all=await history.snapshot({view:'all'}),ids=recordIdsFromSource(source);if(all.records.some(r=>ids.includes(r.id)&&(r.hidden||r.trashedAt)))fail('RESEARCH_HIDDEN','参考视频已隐藏或在回收站，请先恢复后处理。',409);}
 async function checkPlan(plan,scope){owned(plan,scope);await checkSource(plan.source);if(plan.styleVersionSnapshot&&!await visible(plan.styleVersionSnapshot.recordIds))fail('RESEARCH_HIDDEN','引用的风格证据已隐藏或在回收站。',409);if(plan.topicId){const snap=await active();if(!snap.topics.some(t=>t.id===plan.topicId))fail('RESEARCH_TOPIC','专题不存在或已无可见资料。',404);}return plan;}
 async function checkJob(job,scope){owned(job,scope);await checkSource(job.plan.source);if(job.resolvedSource)await checkSource(job.resolvedSource);if(job.plan.styleVersionSnapshot&&!await visible(job.plan.styleVersionSnapshot.recordIds))fail('RESEARCH_HIDDEN','研究引用的风格证据已隐藏或在回收站。',409);if(!await visible(job.selectedRecordIds))fail('RESEARCH_HIDDEN','研究引用了隐藏或回收站记录，请先恢复后查看。',409);return job;}
 async function publicJob(job,scope){await checkJob(job,scope);const result=clone(job);if(Array.isArray(result.candidates)){const ids=new Set((await active()).records.map(r=>r.id));result.candidates=result.candidates.filter(c=>ids.has(c.recordId));result.hiddenCandidateCount=job.candidates.length-result.candidates.length;}return result;}
 async function updateJob(jobId,callback){return store.transaction(state=>{const job=state.jobs.find(j=>j.jobId===jobId);if(!job)fail('RESEARCH_NOT_FOUND','研究任务不存在。',404);callback(job,state);job.updatedAt=now();return job;});}
 async function checkpoint(jobId,phase,detail={}){const current=(await store.read()).jobs.find(j=>j.jobId===jobId);if(current?.cancelRequested)fail('RESEARCH_CANCELLED','已取消尚未开始的步骤。',409);await checkJob(current);return updateJob(jobId,job=>{if(stages.has(phase))job.phase=phase;job.events.push({phase,at:now(),detail});if(detail.status==='requesting'){const step=detail.step,key=step==='account-list'?'accountList':step==='resolve'?'mediaResolution':step==='vl'?'vl':step==='asr'?'asr':null;if(key){job.actualUsage.providerCalls??={tikhub:0,accountList:0,mediaResolution:0,vl:0,asr:0};job.actualUsage.providerCalls[key]++;if(['accountList','mediaResolution'].includes(key))job.actualUsage.providerCalls.tikhub++;}}if(job.events.length>500)job.events=job.events.slice(-500);if(detail.recordId){const video=job.videos.find(v=>v.recordId===detail.recordId);if(video){video.stage=phase;video.detail=detail;video.updatedAt=now();}}});}
 async function processJob(job){
  const jobId=job.jobId,plan=job.plan;
  try{
   await updateJob(jobId,current=>{current.executionOwnerPid=process.pid;});await checkPlan(plan);
   if(plan.executionMode==='planning-only'){await updateJob(jobId,current=>{if(current.cancelRequested)fail('RESEARCH_CANCELLED','已取消尚未开始的步骤。',409);current.phase='completed';current.completedAt=now();current.noteZh='理解卡已确认并保存在本机。本次仅验证计划与确认流程，没有采集、分析或生成视频。';current.actualUsage={records:[],providerCalls:{tikhub:0,vl:0,asr:0},mediaTransfers:0};current.events.push({phase:'completed',at:now(),detail:{executionMode:'planning-only',noteZh:current.noteZh}});});return;}
   const capability=sourceCapability(plan.source);if(!capability.available)fail('RESEARCH_CAPABILITY',capability.reasonZh,409);
   let effectivePlan={...plan,source:job.resolvedSource||plan.source},selectedIds=[];
   if(job.phase==='selection_confirmed'){
    const current=(await store.read()).jobs.find(j=>j.jobId===jobId);if(current.cancelRequested)fail('RESEARCH_CANCELLED','已取消尚未开始的步骤。',409);const latest=(await store.read()).plans.find(p=>p.planId===plan.planId);if(!latest||latest.planRevision!==job.planRevision)fail('RESEARCH_STALE','理解卡已变化，旧候选不能继续分析。',409);await checkJob(current);selectedIds=[...current.selectedRecordIds];
   }else{
    await checkpoint(jobId,'collecting');
    if(plan.source.kind==='douyin-share'){
     if(typeof resolveSource!=='function')fail('RESEARCH_SOURCE_RESOLVER','抖音分享链接展开服务尚未连接；请提供完整主页或视频链接。',409);
     await checkpoint(jobId,'collecting',{step:'source-link',status:'requesting',provider:'public-redirect-headers'});
     const resolved=await resolveSource(plan.source.url);if(!['account','video'].includes(resolved?.kind))fail('RESEARCH_SOURCE','分享链接未解析成账号或视频，请补充完整链接。',409);
     if(plan.executionMode==='candidate-selection'&&resolved.kind!=='account')fail('RESEARCH_SOURCE_KIND','这条分享链接实际是单条视频，不能列账号八条候选；请提供账号主页，或把理解卡改为单视频研究。',409);
     const resolvedSource=resolved.kind==='account'?normalizeResearchSource({kind:'account',url:resolved.url}):normalizeResearchSource({kind:'videos',urls:[resolved.url]});effectivePlan={...plan,source:resolvedSource,selectionPolicy:resolved.kind==='video'?{mode:'user-picked',count:1}:plan.selectionPolicy};
     await updateJob(jobId,current=>{current.resolvedSource=resolvedSource;current.sourceResolution={status:'completed',redirectCount:resolved.redirectCount??null,networkKind:'public-response-headers',paidApiCalls:0};});
    }
    let payload;
    if(effectivePlan.source.kind==='account'){
     if(typeof collectAccount!=='function')fail('RESEARCH_COLLECTOR','账号采集服务尚未连接。',409);
     await checkpoint(jobId,'collecting',{step:'account-list',status:'requesting',provider:'TikHub'});payload=await collectAccount({url:effectivePlan.source.url,consent:true});
     if(effectivePlan.source.platform==='Douyin'?(payload?.account?.platform!=='Douyin'||payload?.account?.secUid!==effectivePlan.source.secUid):payload?.account?.username!==effectivePlan.source.username)fail('RESEARCH_ACCOUNT','采集结果账号与确认单不一致。',409);
    }else payload={account:null,samples:effectivePlan.source.urls.map(url=>({url,title:'待分析参考视频',ownerVerified:true})),provider:'user-provided',collectedAt:now(),hasMore:false};
    await checkpoint(jobId,'selecting');const candidateMode=plan.executionMode==='candidate-selection',all=await history.snapshot({view:'all'}),hiddenIds=new Set(all.records.filter(r=>r.hidden||r.trashedAt).map(r=>r.id));
    const safeSamples=(Array.isArray(payload.samples)?payload.samples:[]).filter(s=>{try{return!hiddenIds.has(canonicalHistoryUrl(s.url).id);}catch{return false;}});
    const selection=selectResearchSamples(safeSamples,{...effectivePlan.selectionPolicy,count:candidateMode?plan.candidateLimit:effectivePlan.selectionPolicy.count},{now:now(),hasMore:payload.hasMore});
    if(payload.coverage?.noteZh)selection.coverage.noteZh=payload.coverage.noteZh;selection.coverage.excludedOtherOwners=payload.excludedOtherOwners||0;selection.coverage.excludedNonVideos=payload.excludedNonVideos||0;selection.coverage.unknownOwnerCount=payload.unknownOwnerCount||0;
    const ingestPayload=candidateMode?{...payload,samples:selection.selected}:payload,ingested=await history.ingest(ingestPayload);selectedIds=selection.selected.map(s=>s.id);let topicId=plan.topicId;
    if(!topicId&&plan.topicTitle){const created=await history.mutate({action:'create-topic',title:plan.topicTitle,kind:effectivePlan.source.kind==='account'?'brand':'topic',ids:selectedIds});topicId=created.topic.id;}
    if(!topicId)topicId=(await active()).topics.find(t=>t.recordIds.some(id=>selectedIds.includes(id)))?.id||null;
    if(topicId&&selectedIds.length)await history.mutate({action:'link-topic',topicId,ids:selectedIds});
    await updateJob(jobId,(current,state)=>{current.topicId=topicId;const currentPlan=state.plans.find(p=>p.planId===current.planId);if(currentPlan?.planRevision===current.planRevision)currentPlan.resolvedTopicId=topicId;current.coverage=selection.coverage;current.batchId=ingested.batchId;current.selectedRecordIds=candidateMode?[]:selectedIds;current.videos=candidateMode?[]:selectedIds.map(recordId=>({recordId,stage:'selected',status:'pending'}));});
    if(!selectedIds.length)fail('RESEARCH_NO_SAMPLES','本次候选缺少可比较的发布时间或指标，或没有可见视频；未启动分析。',409);
    if(candidateMode){await updateJob(jobId,current=>{if(current.cancelRequested)fail('RESEARCH_CANCELLED','已取消尚未开始的步骤。',409);current.candidates=selection.selected.map(s=>({recordId:s.id,url:s.url,title:s.title||'未提供标题',publishedAt:s.publishedAt||null,views:Number.isFinite(s.views)?s.views:null,likes:Number.isFinite(s.likes)?s.likes:null,duration:Number.isFinite(s.duration)?s.duration:null,ownerVerified:s.ownerVerified===true,status:'metadata-only',styleStatus:'not-analyzed'}));current.candidateSetHash=hash([current.jobId,current.planRevision,current.candidates]);current.phase='waiting_selection';current.noteZh='已保存最多八条元数据候选；尚未下载、分析画面或识别风格。请选择一到两条后确认深拆。';current.events.push({phase:'waiting_selection',at:now(),detail:{candidateCount:current.candidates.length,paidAnalysisCalls:0}});});return;}
   }
   for(const recordId of selectedIds){
    try{
     await checkpoint(jobId,'resolving_media',{recordId});const record=(await active()).records.find(r=>r.id===recordId);if(!record)fail('RESEARCH_HIDDEN','视频已隐藏或移入回收站。',409);if(typeof analyzeVideo!=='function')fail('RESEARCH_ANALYZER','视频分析服务尚未连接。',409);
     const result=await analyzeVideo({record,plan:effectivePlan,jobId,onStage:async(stage,detail={})=>checkpoint(jobId,stage,{...detail,recordId})});
     await checkpoint(jobId,'synthesizing',{recordId});const normalized=clone(result);if(!obj(normalized))fail('RESEARCH_RESULT','分析结果格式无效。',409);
     await updateJob(jobId,current=>{const item={recordId,result:normalized,completedAt:now()};current.results.push(item);current.actualUsage.records.push({recordId,usage:normalized.usage||null});const video=current.videos.find(v=>v.recordId===recordId);video.status=normalized.status==='partial'?'partial':'completed';video.stage='saved';video.updatedAt=now();
      for(const [index,recommendation] of (Array.isArray(normalized.recommendations)?normalized.recommendations:[]).slice(0,2).entries()){if(recommendation.status==='notRecommended')continue;const nameZh=text(recommendation.nameZh,120)||'待确认风格',existing=current.styleCandidates.find(c=>c.nameZh===nameZh);if(existing){existing.recordIds=[...new Set([...existing.recordIds,recordId])];existing.recommendation.evidence=[...(existing.recommendation.evidence||[]),...(recommendation.evidence||[])];continue;}if(current.styleCandidates.length>=2)continue;current.styleCandidates.push({candidateId:'candidate_'+hash([jobId,recordId,index]).slice(0,24),recordIds:[recordId],sourceJobId:jobId,topicId:current.topicId,nameZh,recommendation,status:'candidate',createdAt:now()});}
     });
     if(hasVisualEvidence(normalized)&&normalized.titleZh&&history.attachAnalysisMetadata)await history.attachAnalysisMetadata(recordId,{displayTitleZh:normalized.titleZh,summaryZh:normalized.summaryZh||'',autoTagsZh:normalized.tagsZh||[],analysisRef:{recordId,analysisId:normalized.evidenceRef?.analysisId||jobId,provider:'mosi',model:'moss-vl-1.0',completedAt:now()}});
    }catch(error){const safe=safeError(error);await updateJob(jobId,current=>{const video=current.videos.find(v=>v.recordId===recordId);video.status=error.code==='RESEARCH_CANCELLED'?'cancelled':'failed';video.error=safe;video.updatedAt=now();current.errors.push({recordId,...safe});});if(['RESEARCH_CANCELLED','RESEARCH_HIDDEN'].includes(error.code))throw error;}
   }
   await updateJob(jobId,current=>{const expected=plan.executionMode==='candidate-selection'?current.selectedRecordIds.length:effectivePlan.selectionPolicy.count,allComplete=current.videos.every(v=>v.status==='completed')&&current.selectedRecordIds.length===expected;current.phase=current.results.length?(allComplete?'completed':'partial'):'failed';current.completedAt=now();current.events.push({phase:current.phase,at:now(),detail:{}});});
  }catch(error){await updateJob(jobId,current=>{current.phase=error.code==='RESEARCH_CANCELLED'?'cancelled':current.results.length?'partial':'failed';current.error=safeError(error);current.completedAt=now();current.events.push({phase:current.phase,at:now(),detail:current.error});});}
 }
 function schedule(){if(runtime.running){runtime.pending=true;return;}runtime.pending=false;runtime.running=Promise.resolve().then(async()=>{let release;while(!(release=await store.acquireExecutor())){if(!(await store.read()).jobs.some(j=>['confirmed','selection_confirmed'].includes(j.phase)&&!j.cancelRequested))return;await pause(100);}try{while(true){const state=await store.read(),next=state.jobs.find(j=>['confirmed','selection_confirmed'].includes(j.phase)&&!j.cancelRequested);if(!next)break;await processJob(next);}}finally{await release();}}).catch(async error=>{await store.transaction(state=>{for(const job of state.jobs.filter(j=>['confirmed','selection_confirmed'].includes(j.phase))){job.phase='failed';job.error=safeError(error);job.updatedAt=now();}return{};}).catch(()=>{});}).finally(()=>{runtime.running=null;if(runtime.pending)schedule();});}
 const service={
  async preparePlan(payload,scope={}){await ready();if(!obj(payload))fail('RESEARCH_PLAN','理解卡格式无效。');const data=normalizePlan(payload);await checkSource(data.source);if(data.topicId&&!((await active()).topics.some(t=>t.id===data.topicId)))fail('RESEARCH_TOPIC','请选择当前可见的品牌或专题。',404);
   let styleVersionSnapshot=null;if(data.styleVersionId){const style=(await store.read()).styles.find(s=>s.styleVersionId===data.styleVersionId);if(!style||!await visible(style.recordIds))fail('RESEARCH_STYLE','风格版本不存在或引用了不可见资料。',404);if(data.topicId&&style.topicId!==data.topicId)fail('RESEARCH_STYLE','请选择当前专题内的风格版本。',409);styleVersionSnapshot=style;}
   const core={...data,styleVersionSnapshot},planHash=hash(core);
   return store.transaction(state=>{let plan;if(payload.planId){plan=state.plans.find(p=>p.planId===id(payload.planId,'理解卡'));if(!plan)fail('RESEARCH_NOT_FOUND','理解卡不存在。',404);owned(plan,scope);if(payload.expectedRevision!==plan.planRevision)fail('RESEARCH_STALE','理解卡已更新，请重新查看并确认最新版本。',409);if(plan.planHash===planHash)return{planId:plan.planId,planRevision:plan.planRevision,plan};for(const job of state.jobs.filter(j=>j.planId===plan.planId&&j.planRevision===plan.planRevision&&!terminal.has(j.phase))){job.cancelRequested=true;job.updatedAt=now();job.events.push({phase:'confirmation_invalidated',at:now(),detail:{message:'理解卡已修改，旧版本尚未开始的步骤停止；已经送达供应商的请求可能已计费。'}});if(['confirmed','waiting_selection','selection_confirmed'].includes(job.phase)){job.phase='cancelled';job.completedAt=now();}}plan={...plan,...core,planRevision:plan.planRevision+1,planHash,status:'awaiting_confirmation',updatedAt:now(),confirmedJobId:null};state.plans[state.plans.findIndex(p=>p.planId===plan.planId)]=plan;}else{plan={...core,planId:'plan_'+randomUUID(),planRevision:1,planHash,status:'awaiting_confirmation',sessionId:scope.sessionId||null,workbenchId:scope.workbenchId||null,createdAt:now(),updatedAt:now(),confirmedJobId:null};state.plans.push(plan);}return{planId:plan.planId,planRevision:plan.planRevision,plan};});
  },
  async getPlan(input,scope={}){await ready();const plan=(await store.read()).plans.find(p=>p.planId===id(typeof input==='string'?input:input?.planId,'理解卡'));if(!plan)fail('RESEARCH_NOT_FOUND','理解卡不存在。',404);return clone(await checkPlan(plan,scope));},
  async confirmPlan({planId,planRevision}={}){await ready();const current=await service.getPlan({planId});const capability=sourceCapability(current.source);if(current.executionMode!=='planning-only'&&!capability.available)fail('RESEARCH_CAPABILITY',capability.reasonZh,409);if(current.planRevision!==planRevision)fail('RESEARCH_STALE','理解卡已变化，请确认最新版本。',409);const result=await store.transaction(state=>{const plan=state.plans.find(p=>p.planId===planId);if(plan.planRevision!==planRevision)fail('RESEARCH_STALE','理解卡已变化，请确认最新版本。',409);const requestKey=hash([planId,planRevision,plan.planHash]),prior=state.jobs.find(j=>j.requestKey===requestKey);if(prior)return{jobId:prior.jobId,job:prior,duplicate:true};const job={jobId:'research_'+randomUUID(),planId,planRevision,confirmedPlanHash:plan.planHash,requestKey,plan:clone(plan),sessionId:plan.sessionId,workbenchId:plan.workbenchId,topicId:plan.topicId,phase:'confirmed',confirmedAt:now(),confirmedBy:'user-ui',executionOwnerPid:process.pid,createdAt:now(),updatedAt:now(),selectedRecordIds:[],videos:[],results:[],styleCandidates:[],estimatedUsage:{calls:plan.estimatedCalls},actualUsage:{records:[],providerCalls:{tikhub:0,accountList:0,mediaResolution:0,vl:0,asr:0},callCountPolicy:'attempted-stage-calls-not-invoice'},errors:[],events:[{phase:'confirmed',at:now(),detail:{}}],cancelRequested:false};state.jobs.push(job);plan.status='confirmed';plan.confirmedJobId=job.jobId;return{jobId:job.jobId,job,duplicate:false};});if(!result.duplicate)schedule();return{...result,job:await publicJob(result.job)};},
  async getJob(input,scope={}){await ready();const job=(await store.read()).jobs.find(j=>j.jobId===id(typeof input==='string'?input:input?.jobId,'研究任务'));if(!job)fail('RESEARCH_NOT_FOUND','研究任务不存在。',404);return publicJob(job,scope);},
  async readResult(input,scope={}){const job=await service.getJob(input,scope);return{jobId:job.jobId,topicId:job.topicId,status:job.phase,executionMode:job.plan.executionMode||'research',noteZh:job.noteZh||null,actualUsage:job.actualUsage,coverage:job.coverage||null,results:job.results,styleCandidates:job.styleCandidates,candidates:job.candidates||[],candidateSetHash:job.candidateSetHash||null,planRevision:job.planRevision,errors:job.errors,error:job.error||null,evidencePolicy:'原片观察、机器测量、模型建议与用户采用分开记录；两条样本不代表全账号。'};},
  async selectCandidates({jobId,planRevision,candidateSetHash,recordIds}={}){await ready();const current=await service.getJob({jobId});if(current.plan.executionMode!=='candidate-selection')fail('RESEARCH_SELECTION','此任务不是候选选择模式。',409);if(!Array.isArray(recordIds)||!recordIds.length||recordIds.length>current.plan.selectionPolicy.count||new Set(recordIds).size!==recordIds.length||recordIds.some(v=>!validResearchId(v)))fail('RESEARCH_SELECTION','请选择一到两条不同的候选视频。');if(!await visible(recordIds))fail('RESEARCH_HIDDEN','所选候选已隐藏或在回收站，请重新查看。',409);const result=await store.transaction(state=>{const job=state.jobs.find(j=>j.jobId===jobId),plan=state.plans.find(p=>p.planId===job.planId);if(!plan||plan.planRevision!==planRevision||job.planRevision!==planRevision)fail('RESEARCH_STALE','理解卡已变化，旧候选确认无效。',409);if(typeof candidateSetHash!=='string'||candidateSetHash!==job.candidateSetHash)fail('RESEARCH_CANDIDATES_STALE','候选列表已变化，请刷新后重新选择。',409);if(recordIds.some(id=>!job.candidates?.some(c=>c.recordId===id)))fail('RESEARCH_SELECTION','所选视频不在这次候选列表中。',409);const selectionKey=hash([jobId,planRevision,candidateSetHash,[...recordIds].sort()]);if(job.selectionKey){if(job.selectionKey===selectionKey)return{jobId,job,duplicate:true};fail('RESEARCH_SELECTION_LOCKED','这次选择已开始处理，不能替换已确认视频；请新建研究。',409);}if(job.cancelRequested||job.phase!=='waiting_selection')fail('RESEARCH_SELECTION_STATE','此任务当前不在等待选择阶段。',409);job.selectionKey=selectionKey;job.selectedRecordIds=job.candidates.filter(c=>recordIds.includes(c.recordId)).map(c=>c.recordId);job.videos=job.selectedRecordIds.map(recordId=>({recordId,stage:'selected',status:'pending'}));job.selectionConfirmedAt=now();job.selectionConfirmedBy='user-ui';job.phase='selection_confirmed';job.executionOwnerPid=process.pid;job.updatedAt=now();job.noteZh='已确认所选视频，开始深拆；没有重新采集账号列表。';job.events.push({phase:'selection_confirmed',at:now(),detail:{count:recordIds.length}});return{jobId,job,duplicate:false};});if(!result.duplicate)schedule();return{...result,job:await publicJob(result.job)};},
  async readByRecord({recordId}={},scope={}){await ready();id(recordId,'视频');const snapshot=await history.snapshot({view:'all'}),record=snapshot.records.find(r=>r.id===recordId);if(record&&(record.hidden||record.trashedAt))fail('RESEARCH_HIDDEN','视频已隐藏或在回收站，请先恢复后查看。',409);if(!record)return{status:'not-started',recordId,libraryUpdated:false};const state=await store.read();for(const job of [...state.jobs].reverse()){if(scope.sessionId&&(job.sessionId!==scope.sessionId||scope.workbenchId&&job.workbenchId!==scope.workbenchId))continue;const item=job.results.find(r=>r.recordId===recordId);if(!item)continue;await checkJob(job,scope);const status=item.result.status==='completed'&&hasVisualEvidence(item.result)?'completed':'partial';return clone({status,recordId,result:item.result,intent:job.plan.userIntent,jobId:job.jobId,planId:job.planId,planRevision:job.planRevision,libraryUpdated:false});}return{status:'not-started',recordId,libraryUpdated:false};},
  async listPlans({topicId,sessionId}={},scope={}){await ready();const state=await store.read(),wantedSession=scope.sessionId||sessionId;const plans=[];for(const plan of state.plans){if(topicId&&plan.topicId!==topicId&&plan.resolvedTopicId!==topicId||wantedSession&&plan.sessionId!==wantedSession)continue;try{await checkPlan(plan,scope);plans.push(plan);}catch(error){if(![403,404,409].includes(error.status))throw error;}}
   const jobs=[];for(const job of state.jobs){if(topicId&&job.topicId!==topicId||wantedSession&&job.sessionId!==wantedSession)continue;try{jobs.push(await publicJob(job,scope));}catch(error){if(![403,404,409].includes(error.status))throw error;}}
   const styles=[];for(const style of state.styles)if((!topicId||style.topicId===topicId)&&await visible(style.recordIds))styles.push(style);return clone({plans:plans.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),jobs:jobs.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),styles});
  },
  async topicContext({topicId,sessionId}={},scope={}){await ready();const snap=await active(),topic=topicId?snap.topics.find(t=>t.id===topicId):null;if(topicId&&!topic)fail('RESEARCH_TOPIC','专题不存在或已无可见资料。',404);const records=topic?snap.records.filter(r=>topic.recordIds.includes(r.id)):[];return{topic,topics:topic?undefined:snap.topics,records,...await service.listPlans({topicId,sessionId},scope)};},
  async confirmStyle({jobId,candidateId,nameZh}={}){const job=await service.getJob({jobId}),candidate=job.styleCandidates.find(c=>c.candidateId===id(candidateId,'风格候选'));if(!candidate)fail('RESEARCH_STYLE','风格候选不存在。',404);if(!job.topicId)fail('RESEARCH_TOPIC','请先把研究关联到品牌或专题。',409);if(!await visible(candidate.recordIds))fail('RESEARCH_HIDDEN','候选证据已隐藏或在回收站。',409);return store.transaction(state=>{const old=state.styles.find(s=>s.sourceJobId===jobId&&s.candidateId===candidateId);if(old)return{style:old,duplicate:true};const name=text(nameZh,120)||candidate.nameZh,style={styleVersionId:'style_'+randomUUID(),version:1,nameZh:name,topicId:job.topicId,sourceJobId:jobId,candidateId,recordIds:candidate.recordIds,recommendation:clone(candidate.recommendation),status:'user-confirmed',confirmedAt:now(),sourcePlanRevision:job.planRevision,immutable:true,evidenceStatus:'user-adopted-not-outcome-verified'};state.styles.push(style);return{style,duplicate:false};});},
  async cancelJob({jobId}={}){await service.getJob({jobId});return updateJob(jobId,job=>{if(terminal.has(job.phase))return;job.cancelRequested=true;job.events.push({phase:'cancellation_requested',at:now(),detail:{message:'尚未发起的步骤将停止；已送达供应商的请求可能已计费。'}});if(['confirmed','waiting_selection','selection_confirmed'].includes(job.phase)){job.phase='cancelled';job.completedAt=now();}});},
  async waitForIdle(jobId){await ready();while(runtime.running)await runtime.running;return jobId?service.getJob({jobId}):undefined;}
 };
 service.readTopicContext=service.topicContext;
 service.handlers=createResearchHandlers({service,isAllowed});return service;
}
const respond=(value,status=200)=>Response.json(value,{status,headers:{'cache-control':'no-store','x-content-type-options':'nosniff'}});
async function limitedJson(request){const max=64*1024,reader=request.body?.getReader();if(!reader)fail('RESEARCH_BODY','请求内容为空。');let bytes=0,raw='';const decoder=new TextDecoder();try{while(true){const {value,done}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>max){await reader.cancel();fail('RESEARCH_BODY','请求内容超过 64 KB。',413);}raw+=decoder.decode(value,{stream:true});}raw+=decoder.decode();}finally{reader.releaseLock();}try{const value=JSON.parse(raw);if(!obj(value))throw Error();return value;}catch{fail('RESEARCH_BODY','请求 JSON 格式无效。');}}
export function createResearchHandlers({service,isAllowed=sameOrigin}={}){
 async function handle(request,method,fn){if(request.method!==method)return respond({error:'此接口不支持该请求方式。'},405);if(!await isAllowed(request)||method==='POST'&&request.headers.get('x-derek-workbench')!=='1')return respond({error:'请求来源校验失败。'},403);try{return respond(await fn(method==='POST'?await limitedJson(request):new URL(request.url)));}catch(error){const status=[400,403,404,409,413].includes(error?.status)?error.status:500;return respond({error:status===500?'研究操作未完成；原记录保留，没有自动重试。':error.message,code:error?.code?.startsWith('RESEARCH_')?error.code:undefined},status);}}
 return{plans:request=>request.method==='GET'?handle(request,'GET',u=>u.searchParams.has('planId')?service.getPlan({planId:u.searchParams.get('planId')}):service.listPlans({topicId:u.searchParams.get('topicId')||undefined,sessionId:u.searchParams.get('sessionId')||undefined})):handle(request,'POST',body=>service.preparePlan(body)),confirm:request=>handle(request,'POST',body=>service.confirmPlan(body)),select:request=>handle(request,'POST',body=>service.selectCandidates(body)),job:request=>handle(request,'GET',u=>service.getJob({jobId:u.searchParams.get('jobId')})),result:request=>handle(request,'GET',u=>service.readResult({jobId:u.searchParams.get('jobId')})),recordResult:request=>handle(request,'GET',u=>service.readByRecord({recordId:u.searchParams.get('recordId')})),context:request=>handle(request,'GET',u=>service.topicContext({topicId:u.searchParams.get('topicId')||undefined,sessionId:u.searchParams.get('sessionId')||undefined})),confirmStyle:request=>handle(request,'POST',body=>service.confirmStyle(body)),cancel:request=>handle(request,'POST',body=>service.cancelJob(body))};
}
export function applyResearchService(ctx,{service,prefix='/api/derek-video-replicate/research',...options}={}){
 let prefixes=installed.get(ctx);if(!prefixes){prefixes=new Set();installed.set(ctx,prefixes);}if(prefixes.has(prefix))return service;service??=createResearchService(options);const h=service.handlers;for(const [suffix,methods,fetch]of[['/plans',['GET','POST'],h.plans],['/confirm',['POST'],h.confirm],['/select',['POST'],h.select],['/jobs',['GET'],h.job],['/result',['GET'],h.result],['/record-result',['GET'],h.recordResult],['/context',['GET'],h.context],['/styles/confirm',['POST'],h.confirmStyle],['/cancel',['POST'],h.cancel]])ctx.connection.fetch.register({path:prefix+suffix,methods,requestBody:'buffered',fetch});prefixes.add(prefix);return service;
}
