import {lookup as dnsLookup} from 'node:dns/promises';
import {isIP} from 'node:net';
import https from 'node:https';
import {spawn} from 'node:child_process';
import {Readable} from 'node:stream';
import {mkdir,open,readFile,rename,stat,lstat,realpath,readdir,rm,access} from 'node:fs/promises';
import {constants} from 'node:fs';
import path from 'node:path';
import {createHash,randomUUID} from 'node:crypto';

export const MEDIA_LIMITS=Object.freeze({bytes:200*1024*1024,cacheBytes:512*1024*1024,durationSec:600,timeoutMs:120000,ttlMs:24*60*60*1000});
// Platform-specific allowlists stay intentionally narrow. Unknown CDN hosts need
// explicit review; a TikHub response never widens these lists.
export const MEDIA_CDN_DOMAINS=Object.freeze({instagram:Object.freeze(['cdninstagram.com','fbcdn.net']),douyin:Object.freeze(['douyinvod.com'])});
const CDN_DOMAINS=Object.values(MEDIA_CDN_DOMAINS).flat();
const ERROR_MESSAGES={MEDIA_URL:'视频地址不在已支持的公开媒体域内。',MEDIA_DNS:'视频地址不能安全解析为公开网络地址。',MEDIA_REDIRECT:'媒体地址发生重定向，已停止；没有自动换地址或重复采集。',MEDIA_EXPIRED:'媒体地址已失效或不可访问，未自动重新采集。',MEDIA_SIZE:'视频为空或超过本次批准的体积上限，未送交模型。',MEDIA_TIMEOUT:'媒体读取超时，未自动重试。',MEDIA_FORMAT:'返回内容不是可分析的视频。',MEDIA_DURATION:'视频超过本次批准的时长上限，未截断或送交模型。',MEDIA_CACHE:'临时媒体缓存不可用或容量已满。',MEDIA_TOOL:'本机 FFmpeg / FFprobe 未完成媒体测量。',MEDIA_SOURCE:'研究媒体解析支持 Instagram 单条视频或 www.douyin.com/video/作品ID，暂不展开抖音短链。',MEDIA_UNAVAILABLE:'抖音作品不可用，可能已删除或访问受限；接口可能已计费，未自动重试。',MEDIA_TIKHUB:'TikHub 未返回可确认的视频；未自动重试或切换服务。',MEDIA_IDENTITY:'TikHub 返回作品与所选视频不一致，已停止处理。',MEDIA_KEY:'TikHub 服务器端凭据不可用。'};
export function mediaError(code,status=502){return Object.assign(new Error(ERROR_MESSAGES[code]||ERROR_MESSAGES.MEDIA_TIKHUB),{code,safeStatus:status});}
export function safeMediaError(error){const code=Object.hasOwn(ERROR_MESSAGES,error?.code)?error.code:'MEDIA_TIKHUB';return {code,message:ERROR_MESSAGES[code]};}
const idHash=value=>createHash('sha256').update(String(value)).digest('hex');
function publicAddress(value){
 const family=isIP(value);if(family===4){const p=value.split('.').map(Number);return !(p[0]===0||p[0]===10||p[0]===127||p[0]>=224||p[0]===169&&p[1]===254||p[0]===172&&p[1]>=16&&p[1]<=31||p[0]===192&&(p[1]===168||p[1]===0||p[1]===2)||p[0]===100&&p[1]>=64&&p[1]<=127||p[0]===198&&(p[1]===18||p[1]===19||p[1]===51)||p[0]===203&&p[1]===0&&p[2]===113);}
 // Public global unicast only; mapped IPv4 and local/link-local/multicast are refused.
 return family===6&&/^[23][0-9a-f]{3}:/i.test(value)&&!/^2001:(?:db8|0|10|20):/i.test(value);
}
export function validateMediaUrl(value,{platform}={}){const domains=platform?MEDIA_CDN_DOMAINS[platform]||[]:CDN_DOMAINS;let url;try{url=new URL(value);}catch{throw mediaError('MEDIA_URL',400);}if(url.protocol!=='https:'||url.username||url.password||url.port&&url.port!=='443'||url.href.length>8192||!domains.some(domain=>url.hostname===domain||url.hostname.endsWith('.'+domain))||isIP(url.hostname)||url.hash)throw mediaError('MEDIA_URL',400);return url.href;}
export async function verifyMediaAddress(value,{lookup=dnsLookup}={}){const url=new URL(validateMediaUrl(value));let addresses;try{addresses=await lookup(url.hostname,{all:true,verbatim:true});}catch{throw mediaError('MEDIA_DNS');}if(!Array.isArray(addresses)||!addresses.length||addresses.some(x=>!publicAddress(x.address)))throw mediaError('MEDIA_DNS');return {url:url.href,addresses};}
// DNS is verified once and pinned into this request. No redirect handling or origin credentials.
export async function safeMediaTransport(value,{signal,lookup=dnsLookup}={}){const verified=await verifyMediaAddress(value,{lookup});return new Promise((resolve,reject)=>{const address=verified.addresses[0];const request=https.get(verified.url,{signal,headers:{accept:'video/*,application/octet-stream','user-agent':'DSH-Research/0.6.0'},lookup:(_hostname,options,callback)=>options?.all?callback(null,[address]):callback(null,address.address,address.family)},response=>{resolve(new Response(Readable.toWeb(response),{status:response.statusCode,headers:response.headers}));});request.on('error',()=>reject(mediaError(signal?.aborted?'MEDIA_TIMEOUT':'MEDIA_EXPIRED')));});}
function canonicalInstagram(value){let url;try{url=new URL(value);}catch{throw mediaError('MEDIA_SOURCE',400);}const match=url.pathname.match(/^\/(?:reel|reels|p)\/([A-Za-z0-9_-]{1,100})\/?$/);if(url.protocol!=='https:'||!['instagram.com','www.instagram.com'].includes(url.hostname)||url.username||url.password||!match)throw mediaError('MEDIA_SOURCE',400);return {url:'https://www.instagram.com/reel/'+match[1]+'/',shortcode:match[1],platform:'instagram'};}
export function canonicalDouyinVideo(value){let url;try{url=new URL(value);}catch{throw mediaError('MEDIA_SOURCE',400);}const match=url.pathname.match(/^\/video\/([0-9]{6,24})\/?$/);if(url.protocol!=='https:'||!['douyin.com','www.douyin.com'].includes(url.hostname)||url.username||url.password||url.port||!match)throw mediaError('MEDIA_SOURCE',400);return {url:'https://www.douyin.com/video/'+match[1],awemeId:match[1],platform:'douyin'};}
function canonicalSource(value){let url;try{url=new URL(value);}catch{throw mediaError('MEDIA_SOURCE',400);}return ['douyin.com','www.douyin.com'].includes(url.hostname)?canonicalDouyinVideo(value):canonicalInstagram(value);}
async function boundedJson(response,max=4*1024*1024){if(!response.body?.getReader)throw mediaError('MEDIA_TIKHUB');const reader=response.body.getReader(),chunks=[];let total=0;try{for(;;){const {done,value}=await reader.read();if(done)break;total+=value.byteLength;if(total>max){await reader.cancel();throw mediaError('MEDIA_TIKHUB');}chunks.push(value);}return JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{throw mediaError('MEDIA_TIKHUB');}finally{reader.releaseLock();}}
export function normalizeResolvedInstagram(raw,sourceUrl){const source=canonicalInstagram(sourceUrl);const envelope=raw?.data&&typeof raw.data==='object'?raw.data:raw;const item=envelope?.items?.[0]||envelope?.data?.items?.[0]||envelope?.xdt_api__v1__media__shortcode__web_info?.items?.[0]||envelope?.graphql?.shortcode_media||envelope?.shortcode_media||envelope;
 const returnedCode=item?.code||item?.shortcode;if(returnedCode&&returnedCode!==source.shortcode)throw mediaError('MEDIA_IDENTITY');
 if(!returnedCode)throw mediaError('MEDIA_IDENTITY');
 const videoUrl=item?.video_versions?.find(x=>typeof x?.url==='string')?.url||item?.video_url;if(!videoUrl||item?.media_type===1||item?.is_video===false)throw mediaError('MEDIA_TIKHUB');
 const normalized=validateMediaUrl(videoUrl,{platform:'instagram'});return {sourceUrl:source.url,videoUrl:normalized,sourceId:source.shortcode,platform:'instagram',provider:'TikHub',identityVerified:true};}
// OpenAPI documents the endpoint and aweme_id but leaves detail data as an
// untyped ResponseModel. These limited detail envelopes require a matching ID;
// compatibility with a new live response is still a separate acceptance check.
export function normalizeResolvedDouyin(raw,sourceUrl){const source=canonicalDouyinVideo(sourceUrl),envelope=raw?.data&&typeof raw.data==='object'?raw.data:raw;if(envelope?.filter_detail||Array.isArray(envelope?.filter_list)&&envelope.filter_list.length)throw mediaError('MEDIA_UNAVAILABLE');const entries=Array.isArray(envelope?.aweme_details)?envelope.aweme_details.slice(0,100):[envelope?.aweme_detail||envelope];const item=entries.find(value=>typeof value?.aweme_id==='string'&&value.aweme_id===source.awemeId);if(!item)throw mediaError('MEDIA_IDENTITY');if(item.image_post_info||Array.isArray(item.images)&&item.images.length||[2,68].includes(item.aweme_type))throw mediaError('MEDIA_FORMAT');const video=item.video;if(!video||typeof video!=='object')throw mediaError('MEDIA_TIKHUB');const urls=[...(Array.isArray(video.play_addr?.url_list)?video.play_addr.url_list:[]),...(Array.isArray(video.bit_rate)?video.bit_rate.slice(0,10).flatMap(x=>Array.isArray(x?.play_addr?.url_list)?x.play_addr.url_list:[]):[]),...(Array.isArray(video.download_addr?.url_list)?video.download_addr.url_list:[])].slice(0,40);let videoUrl;for(const candidate of urls){try{videoUrl=validateMediaUrl(candidate,{platform:'douyin'});break;}catch{}}if(!videoUrl)throw mediaError('MEDIA_URL',400);return {sourceUrl:source.url,videoUrl,sourceId:source.awemeId,platform:'douyin',provider:'TikHub',identityVerified:true};}
export function createMediaResolver({getKey,fetchImpl=globalThis.fetch,verify=verifyMediaAddress}={}){if(typeof getKey!=='function')throw new TypeError('createMediaResolver requires getKey');return async ({record})=>{const source=canonicalSource(record?.url||record?.sourceUrl);let key;try{key=await getKey();}catch{throw mediaError('MEDIA_KEY',503);}if(typeof key!=='string'||!key)throw mediaError('MEDIA_KEY',503);
 const url=new URL('https://api.tikhub.io'+(source.platform==='douyin'?'/api/v1/douyin/app/v3/fetch_one_video':'/api/v1/instagram/v3/get_post_info'));url.searchParams.set(source.platform==='douyin'?'aweme_id':'url',source.platform==='douyin'?source.awemeId:source.url);let response;try{response=await fetchImpl(url.href,{method:'GET',headers:{Authorization:'Bearer '+key,Accept:'application/json'},redirect:'manual',signal:AbortSignal.timeout(40000)});}catch{throw mediaError('MEDIA_TIKHUB');}finally{key='';}
 if(!response.ok||response.redirected||response.status>=300&&response.status<400)throw mediaError('MEDIA_TIKHUB');const raw=await boundedJson(response);const media=source.platform==='douyin'?normalizeResolvedDouyin(raw,source.url):normalizeResolvedInstagram(raw,source.url);await verify(media.videoUrl);return media;};}
async function privateJson(file,value){const temp=file+'.'+randomUUID()+'.tmp';await open(temp,'wx',0o600).then(async handle=>{try{await handle.writeFile(JSON.stringify(value));}finally{await handle.close();}});await rename(temp,file);}
async function confinedRoot(root){await mkdir(root,{recursive:true,mode:0o700});if((await lstat(root)).isSymbolicLink())throw mediaError('MEDIA_CACHE');return realpath(root);}
function processAlive(pid){if(!Number.isSafeInteger(pid)||pid<=0)return true;try{process.kill(pid,0);return true;}catch(error){return error.code!=='ESRCH';}}
async function cacheUsage(root){let bytes=0;for(const entry of await readdir(root,{withFileTypes:true})){if(!entry.isDirectory()||!/^media-[a-f0-9]{64}$/.test(entry.name))continue;const dir=path.join(root,entry.name);for(const file of await readdir(dir,{withFileTypes:true})){if(file.isFile())bytes+=(await stat(path.join(dir,file.name))).size;}}return bytes;}
export async function pruneResearchMediaCache({root,now=Date.now(),ttlMs=MEDIA_LIMITS.ttlMs}={}){const base=await confinedRoot(path.join(root,'research-media-cache'));let removed=0;for(const entry of await readdir(base,{withFileTypes:true})){if(!entry.isDirectory()||!/^media-[a-f0-9]{64}$/.test(entry.name))continue;const dir=path.join(base,entry.name);let marker;try{marker=JSON.parse(await readFile(path.join(dir,'cache.json'),'utf8'));}catch{continue;}if(marker.owner!=='dsh-research-v1'||!Number.isFinite(marker.createdAt)||now-marker.createdAt<ttlMs)continue;try{const lock=JSON.parse(await readFile(path.join(dir,'in-use.lock'),'utf8'));if(processAlive(lock.pid))continue;}catch(error){if(error.code!=='ENOENT')continue;}await rm(dir,{recursive:true,force:true});removed++;}return {removed};}
export function createMediaCache({root,transport=safeMediaTransport,now=()=>Date.now(),limits=MEDIA_LIMITS}={}){if(!root)throw new TypeError('createMediaCache requires root');return async ({media,jobId,recordId,maxBytes=MEDIA_LIMITS.bytes})=>{if(!Number.isSafeInteger(maxBytes)||maxBytes<1)throw mediaError('MEDIA_SIZE',413);const byteLimit=Math.min(maxBytes,limits.bytes,MEDIA_LIMITS.bytes);validateMediaUrl(media?.videoUrl);const base=await confinedRoot(path.join(root,'research-media-cache'));await pruneResearchMediaCache({root,now:now(),ttlMs:limits.ttlMs});const key='media-'+idHash(jobId+'\0'+recordId);const directory=path.join(base,key);const created=await mkdir(directory,{recursive:true,mode:0o700});if((await lstat(directory)).isSymbolicLink())throw mediaError('MEDIA_CACHE');if(!created){let marker;try{marker=JSON.parse(await readFile(path.join(directory,'cache.json'),'utf8'));}catch{}if(marker?.owner!=='dsh-research-v1')throw mediaError('MEDIA_CACHE');}const releaseFile=path.join(directory,'in-use.lock');let lock;try{lock=await open(releaseFile,'wx',0o600);}catch{throw mediaError('MEDIA_CACHE',409);}await lock.writeFile(JSON.stringify({pid:process.pid,createdAt:now()}));await lock.close();const release=async()=>rm(releaseFile,{force:true});let output,pending;try{const filePath=path.join(directory,'source.mp4');let manifest;try{manifest=JSON.parse(await readFile(path.join(directory,'cache.json'),'utf8'));}catch{}if(manifest?.owner==='dsh-research-v1'&&manifest.status!=='pending'&&manifest.sourceUrl===media.sourceUrl&&now()-manifest.createdAt<limits.ttlMs){const info=await lstat(filePath);if(info.isFile()&&!info.isSymbolicLink()&&info.size>0&&info.size<=byteLimit)return {filePath,directory,release,cached:true,bytes:info.size};}
 if(await cacheUsage(base)+byteLimit>limits.cacheBytes)throw mediaError('MEDIA_CACHE',507);
 await privateJson(path.join(directory,'cache.json'),{owner:'dsh-research-v1',createdAt:now(),sourceUrl:media.sourceUrl,status:'pending'});const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),limits.timeoutMs);let response;try{response=await transport(media.videoUrl,{signal:controller.signal});if(response.redirected||response.status>=300&&response.status<400)throw mediaError('MEDIA_REDIRECT');if(!response.ok||!response.body?.getReader)throw mediaError('MEDIA_EXPIRED');const type=(response.headers.get('content-type')||'').split(';')[0].toLowerCase();if(!type.startsWith('video/')&&type!=='application/octet-stream')throw mediaError('MEDIA_FORMAT');const length=Number(response.headers.get('content-length')||0);if(length>byteLimit)throw mediaError('MEDIA_SIZE',413);
 pending=path.join(directory,'pending-'+randomUUID()+'.mp4');output=await open(pending,'wx',0o600);let bytes=0;const reader=response.body.getReader();try{for(;;){const {value,done}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>byteLimit){await reader.cancel();throw mediaError('MEDIA_SIZE',413);}await output.write(value);}if(bytes<=0)throw mediaError('MEDIA_SIZE',413);}finally{reader.releaseLock();await output.close();output=null;}await rename(pending,filePath);await privateJson(path.join(directory,'cache.json'),{owner:'dsh-research-v1',createdAt:now(),sourceUrl:media.sourceUrl,bytes});return {filePath,directory,bytes,cached:false,release};
 }catch(error){await output?.close().catch(()=>{});if(pending)await rm(pending,{force:true}).catch(()=>{});if(controller.signal.aborted)throw mediaError('MEDIA_TIMEOUT');throw error?.code?.startsWith('MEDIA_')?error:mediaError('MEDIA_EXPIRED');}finally{clearTimeout(timer);await response?.body?.cancel().catch(()=>{});}
 }catch(error){await release();throw error;}};}
function run(executable,args,{limit=2*1024*1024,timeoutMs=MEDIA_LIMITS.timeoutMs}={}){return new Promise((resolve,reject)=>{const child=spawn(executable,args,{stdio:['ignore','pipe','pipe']}),data={stdout:'',stderr:''};let total=0,done=false;const finish=(error)=>{if(done)return;done=true;clearTimeout(timer);error?reject(mediaError('MEDIA_TOOL',503)):resolve(data);};const timer=setTimeout(()=>{child.kill('SIGKILL');finish(true);},timeoutMs);for(const stream of ['stdout','stderr'])child[stream].on('data',chunk=>{total+=chunk.length;if(total>limit){child.kill('SIGKILL');finish(true);}else data[stream]+=chunk.toString();});child.on('error',()=>finish(true));child.on('close',code=>finish(code!==0));});}
async function binary(name){for(const candidate of ['/opt/homebrew/bin/'+name,'/usr/local/bin/'+name,'/usr/bin/'+name]){try{await access(candidate,constants.X_OK);return candidate;}catch{}}return name;}
// The supported Instagram / Douyin media input is MP4. Force the MOV/MP4 demuxer rather than auto-detecting a playlist
// whose file:// segments could point outside this task's owned cache.
export async function measureResearchMedia({filePath,directory,runTool=run,maxDurationSec=MEDIA_LIMITS.durationSec}={}){if(!Number.isFinite(maxDurationSec)||maxDurationSec<=0)throw mediaError('MEDIA_DURATION',413);maxDurationSec=Math.min(maxDurationSec,MEDIA_LIMITS.durationSec);const local=await realpath(filePath);if(!(await stat(local)).isFile())throw mediaError('MEDIA_FORMAT');const ffprobe=await binary('ffprobe'),ffmpeg=await binary('ffmpeg');let info;try{info=JSON.parse((await runTool(ffprobe,['-v','error','-protocol_whitelist','file,pipe','-f','mov','-show_entries','format=duration:stream=codec_type,width,height,r_frame_rate','-of','json',local])).stdout);}catch(error){throw error?.code?error:mediaError('MEDIA_FORMAT');}const video=info.streams?.find(x=>x.codec_type==='video');const durationSec=Number(info.format?.duration);if(!video||!Number.isFinite(durationSec)||durationSec<=0)throw mediaError('MEDIA_FORMAT');if(durationSec>maxDurationSec)throw mediaError('MEDIA_DURATION',413);const hasAudio=info.streams?.some(x=>x.codec_type==='audio')===true;
 const cuts=await runTool(ffmpeg,['-hide_banner','-nostdin','-protocol_whitelist','file,pipe','-f','mov','-i',local,'-an','-sn','-vf',"scale=320:-2,select='gt(scene,0.16)',showinfo",'-f','null','-']);const candidateCutsSec=[...cuts.stderr.matchAll(/pts_time:([\d.]+)/g)].map(m=>Number(m[1])).filter((t,i,a)=>Number.isFinite(t)&&t>0.2&&t<durationSec-0.2&&(i===0||t-a[i-1]>=0.1)).slice(0,500);const boundaries=[0,...candidateCutsSec,durationSec],durations=boundaries.slice(1).map((x,i)=>x-boundaries[i]).sort((a,b)=>a-b);const medianShotSec=durations.length%2?durations[Math.floor(durations.length/2)]:(durations[durations.length/2-1]+durations[durations.length/2])/2;
 const measurements={source:'local-machine-measurement',method:'ffmpeg-scene-score-0.16-scale320',durationSec,width:video.width,height:video.height,hasAudio,candidateCutsSec,candidateShotCount:boundaries.length-1,medianShotSec,logicalBeats:[],noteZh:'机器切点是候选边界，闪光、运动或低对比切镜可能误判。没有把等时长段落当成真实切镜，也未测量音乐节拍。'};let audioFilePath=null;if(hasAudio){audioFilePath=path.join(directory,'audio-'+randomUUID()+'.flac');await runTool(ffmpeg,['-hide_banner','-nostdin','-v','error','-n','-protocol_whitelist','file,pipe','-f','mov','-i',local,'-map','0:a:0','-vn','-sn','-ac','1','-ar','16000','-c:a','flac',audioFilePath]);}return {measurements,hasAudio,audioFilePath};}
