import {createHash,randomUUID} from 'node:crypto';
import {createResearchStore,researchProblem,validResearchId} from './research-store.mjs';
import {canonicalHistoryUrl} from './history-store.mjs';
import {parseInstagram} from './account-core.mjs';
import {parseDouyin} from './douyin-source.mjs';
import {normalizeResearchSource,sourceCapability} from './source-capabilities.mjs';
import {sameOrigin} from './request-origin.mjs';

const runtimes=new Map(),installed=new WeakMap();
const terminal=new Set(['completed','partial','failed','cancelled']);
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const stages=new Set(['confirmed','collecting','selecting','resolving_media','analyzing','synthesizing','comparing']);
const hash=value=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const clone=value=>structuredClone(value);
const text=(value,max=2000)=>typeof value==='string'?value.trim().slice(0,max):'';
const fail=(code,message,status=400)=>{throw researchProblem(code,message,status);};
const safeDate=value=>typeof value==='string'&&Number.isFinite(Date.parse(value))?new Date(value).toISOString():null;
function processAlive(pid){if(!Number.isSafeInteger(pid)||pid<=0)return false;try{process.kill(pid,0);return true;}catch(error){return error.code!=='ESRCH';}}
const obj=value=>value&&typeof value==='object'&&!Array.isArray(value);
const hasVisualEvidence=result=>result?.steps?.vl?.status==='completed'&&Array.isArray(result?.visual?.observations)&&result.visual.observations.some(o=>Number.isFinite(o.startSec)&&o.startSec>=0&&Number.isFinite(o.endSec)&&o.endSec>o.startSec&&typeof o.descriptionZh==='string'&&o.descriptionZh.trim());
const recordIdsFromSource=source=>source.kind==='videos'?source.urls.map(url=>canonicalHistoryUrl(url).id):[];
const safeError=error=>({code:typeof error?.code==='string'&&/^(?:RESEARCH|ANALYSIS|MOSI|MEDIA|TIKHUB|DOUYIN)_[A-Z0-9_]+$/.test(error.code)?error.code:'RESEARCH_STEP_FAILED',message:typeof error?.code==='string'&&(/^(?:RESEARCH|DOUYIN)_/.test(error.code))?error.message:'此阶段未完成；已保留成功结果，不会自动重试或更换服务。',billingUnknown:error?.billingUnknown===true||error?.code==='MOSI_TIMEOUT'});
function id(value,label){if(!validResearchId(value))fail('RESEARCH_ID',`${label}标识无效。`);return value;}
function owned(value,scope={}){if(scope.sessionId&&(value.sessionId!==scope.sessionId||scope.workbenchId&&value.workbenchId!==scope.workbenchId))fail('RESEARCH_OWNER','此研究不属于当前工作台会话。',403);return value;}
function normalizePlan(payload,anchorAt=new Date().toISOString()){
 const executionMode=payload.executionMode??'research',accountStudy=executionMode==='account-study';if(!['research','planning-only','candidate-selection','account-study'].includes(executionMode))fail('RESEARCH_EXECUTION_MODE','执行模式无效。');
 const source=normalizeResearchSource(payload.source),userIntent=text(payload.userIntent||payload.goal||(accountStudy?'研究本次账号样本的风格、节奏与可复刻方案':''),5000);if(!userIntent)fail('RESEARCH_INTENT','请先说明这次想研究什么。');
 if(accountStudy&&!['account','douyin-share'].includes(source.kind))fail('RESEARCH_SELECTION','账号研究需要一个账号主页或账号分享链接；单视频请使用原有的一到两条研究入口。');
 const supplied=obj(payload.selectionPolicy)?payload.selectionPolicy:{},mode=supplied.mode||(accountStudy?'balanced':source.kind!=='videos'?'latest':'user-picked'),count=supplied.count??(accountStudy?6:source.kind!=='videos'?2:source.urls.length);
 if(accountStudy?!['latest','balanced','top-in-page'].includes(mode)||![4,5,6].includes(count):!['latest','top-in-window','user-picked'].includes(mode)||!Number.isInteger(count)||count<1||count>2)fail('RESEARCH_SELECTION',accountStudy?'账号研究请选择四到六条，按均衡、数据优先或最新处理。':'选片数量应为一到两条。');
 if(source.kind!=='videos'&&mode==='user-picked'||source.kind==='videos'&&mode!=='user-picked'||source.kind==='videos'&&count>source.urls.length)fail('RESEARCH_SELECTION','选片方式与来源不一致。');
 if(executionMode==='candidate-selection'&&source.kind==='videos')fail('RESEARCH_SELECTION','八条候选模式需要账号主页或待展开的抖音分享链接。');
 const candidateLimit=executionMode==='candidate-selection'?8:null;if(payload.candidateLimit!==undefined&&payload.candidateLimit!==null&&payload.candidateLimit!==8)fail('RESEARCH_SELECTION','当前候选预览上限为八条。');
 const selectionPolicy={mode,count};if(accountStudy){if(supplied.windowDays!==undefined&&supplied.windowDays!==30)fail('RESEARCH_WINDOW','账号研究仅采样最近三十天，不以旧片补数量。');const end=safeDate(anchorAt);if(!end)fail('RESEARCH_WINDOW','研究时间窗口无效。');Object.assign(selectionPolicy,{windowDays:30,windowStart:new Date(Date.parse(end)-30*86400000).toISOString(),windowEnd:end});}if(['balanced','top-in-page'].includes(mode)){const metric=supplied.metric??'likes';if(!['views','likes'].includes(metric))fail('RESEARCH_SELECTION','数据指标请选择播放或点赞。');selectionPolicy.metric=metric;}if(mode==='top-in-window'){const start=safeDate(supplied.windowStart),end=safeDate(supplied.windowEnd);if(!start||!end||start>=end||!['views','likes'].includes(supplied.metric))fail('RESEARCH_SELECTION','数据优先需要明确起止时间和播放或点赞指标。');Object.assign(selectionPolicy,{metric:supplied.metric,windowStart:start,windowEnd:end});}
 const focus=payload.analysisFocus??['开头叙事','画面风格','剪辑节奏','人声与字幕'];if(!Array.isArray(focus)||focus.length>12||focus.some(x=>typeof x!=='string'||x.length>100))fail('RESEARCH_FOCUS','分析重点格式无效。');
 const material=obj(payload.materialStatus)?payload.materialStatus:{state:'unprovided',description:text(payload.assets,3000)};if(!['unprovided','none','provided','unknown'].includes(material.state))fail('RESEARCH_MATERIALS','素材状态无效。');
 const capability=sourceCapability(source),researching=executionMode!=='planning-only',callCount=researching?count:0,accountPages=researching&&source.kind!=='videos'?(accountStudy?2:1):0;
 const budgetScope={providers:researching?(accountStudy?['tikhub','mosi','deepseek']:['tikhub','mosi']):[],maxVideos:callCount,maxAccountPages:accountPages,maxResolveCalls:callCount,maxVlCalls:callCount,maxAsrCalls:callCount,maxDurationSecPerVideo:600,maxBytesPerVideo:209715200,vlMaxOutputTokens:accountStudy?5000:2500,...(accountStudy?{maxMetadataCandidates:24,maxComparisonCalls:1,maxPromptCompileCalls:1,firstVideoGate:true}:{}),autoRetry:false,generationEnabled:false};
 const estimatedCalls={accountList:accountPages,mediaResolution:callCount,vl:callCount,asrUpTo:callCount,...(accountStudy?{comparison:1,promptCompile:1}:{})};
 const knownInstagramPrice=capability.available&&capability.platform==='Instagram';
 const pricingEstimate={asOf:'2026-10-10',kind:'display-estimate-not-spending-limit',tikhub:{unitPriceUsd:knownInstagramPrice?0.008:null,maxCalls:accountPages+callCount,estimatedMaxUsd:researching&&!knownInstagramPrice?null:Number(((accountPages+callCount)*0.008).toFixed(3)),pricingStatus:knownInstagramPrice?'snapshot':'unverified',noteZh:knownInstagramPrice?'按 Instagram 接口价格快照估算。':'此来源接口单价尚未核验，不沿用 Instagram 单价；未接通的平台不会调用。'},asr:{hourlyPriceCny:2,maxDurationSec:callCount*budgetScope.maxDurationSecPerVideo,estimatedMaxCny:Math.ceil(callCount*budgetScope.maxDurationSecPerVideo/3600*2*1000)/1000},vl:{pricingStatus:researching?'limited-time-free':'not-called',estimatedMaxCny:researching?null:0,guaranteedPrice:false},noteZh:researching?'以上是 2026-10-10 已知价格快照与输入上限推算（抖音单价待核验），不是费用保证或总额授权上限。VL 当期为限时免费，后续价格与 token 用量可能变化；以供应商账单为准。宿主文字对话费用不包含在视频研究估算中。':'仅保存理解卡，不采集视频、不调用 TikHub 或模思。宿主文字对话本身按已配置模型计费。'};

 return{executionMode,candidateLimit,sourceCapability:capability,initialEstimatedCalls:executionMode==='candidate-selection'?{accountList:accountPages,mediaResolution:0,vl:0,asrUpTo:0}:estimatedCalls,topicId:payload.topicId?id(payload.topicId,'专题'):null,topicTitle:text(payload.topicTitle,120),source,userIntent,product:text(payload.product,2000),audience:text(payload.audience,2000),productProfileVersion:text(payload.productProfileVersion,120)||null,analysisFocus:[...new Set(focus.map(v=>v.trim()).filter(Boolean))],selectionPolicy,materialStatus:{state:material.state,description:text(material.description,3000)},styleVersionId:payload.styleVersionId?id(payload.styleVersionId,'风格版本'):null,exclusions:text(payload.exclusions,2000),budgetScope,estimatedCalls,pricingEstimate,modelPolicy:{visual:'moss-vl-1.0',speech:'moss-transcribe-diarize-pro',text:'host-authorized-model-only',...(accountStudy?{comparison:'deepseek-authorized-model',compilePromptsWithText:true}:{})},scopeNoteZh:accountStudy?'仅一个账号、最近三十天，最多两页二十四条元数据，从中研究五到六条（旧四条设置兼容）；旧片、未来日期及未知日期不补数量。均衡选样基于元数据，画面分析后才综合推荐最多三条。无自动重试或额外补分析，不生成视频。':executionMode==='candidate-selection'?'首次确认只读取一页元数据并展示最多八条候选，不下载或分析视频；由你再选一到两条后才深拆。':researching?'只研究最多两条视频，每条最多 10 分钟、200 MiB；不生成视频，失败不自动重试。':'仅确认并保存理解卡；不抓取、不分析、不生成视频。'};
}
/** Deterministic candidate selection. Counts describe the fetched page, never the entire account. */
export function selectResearchSamples(samples,policy,{now=new Date().toISOString(),hasMore=false}={}){
 const unique=new Map();for(const sample of samples||[]){try{const c=canonicalHistoryUrl(sample.url);if(!unique.has(c.id))unique.set(c.id,{...sample,id:c.id,url:c.url});}catch{}}
 const all=[...unique.values()],strictWindow=policy.windowDays===30,endTime=strictWindow?Date.parse(policy.windowEnd):Date.parse(now),startTime=strictWindow?Date.parse(policy.windowStart):-Infinity;
 if(strictWindow&&(!Number.isFinite(endTime)||!Number.isFinite(startTime)||endTime-startTime!==30*86400000))fail('RESEARCH_WINDOW','已确认的三十天窗口无效，未启动分析。',409);
 const unknownTimestampCount=all.filter(s=>!safeDate(s.publishedAt)).length,futureTimestampCount=all.filter(s=>safeDate(s.publishedAt)&&Date.parse(s.publishedAt)>endTime).length,olderThanWindowCount=strictWindow?all.filter(s=>safeDate(s.publishedAt)&&Date.parse(s.publishedAt)<startTime).length:0;
 const validTime=all.filter(s=>safeDate(s.publishedAt)&&Date.parse(s.publishedAt)<=endTime&&Date.parse(s.publishedAt)>=startTime),missingTimestampCount=unknownTimestampCount+futureTimestampCount;
 let eligible=validTime,missingMetricCount=0;
 const byTime=(a,b)=>(Date.parse(b.publishedAt)||0)-(Date.parse(a.publishedAt)||0)||a.id.localeCompare(b.id);
 const metric=policy.metric||'likes',knownMetric=s=>Number.isFinite(s[metric])&&s[metric]>=0;
 const byMetric=(a,b)=>Number(knownMetric(b))-Number(knownMetric(a))||(knownMetric(a)&&knownMetric(b)?b[metric]-a[metric]:0)||byTime(a,b);
 if(policy.mode==='top-in-window'){eligible=validTime.filter(s=>safeDate(s.publishedAt)>=policy.windowStart&&safeDate(s.publishedAt)<policy.windowEnd);missingMetricCount=eligible.filter(s=>!knownMetric(s)).length;eligible=eligible.filter(knownMetric).sort(byMetric);}
 else if(policy.mode==='latest')eligible.sort(byTime);
 else if(['top-in-page','balanced'].includes(policy.mode)){
  // Future-dated and missing-time rows cannot establish a recent account sample.
  missingMetricCount=validTime.filter(s=>!knownMetric(s)).length;
  eligible=validTime.filter(knownMetric).sort(byMetric);
  if(policy.mode==='balanced'){
   const bucket=s=>`${!Number.isFinite(s.duration)?'unknown':s.duration<=15?'short':s.duration<=30?'medium':'long'}:${(Date.parse(now)-Date.parse(s.publishedAt))/86400000<=7?'week':(Date.parse(now)-Date.parse(s.publishedAt))/86400000<=30?'month':'older'}`;
   // Start with the strongest known interaction metric, then cover metadata buckets.
   // Only use the strongest eight (or twice the requested count); this is not visual classification.
   const pool=eligible.slice(0,Math.min(12,Math.max(8,policy.count*2))),picked=[],seen=new Set();
   for(const sample of pool){if(seen.has(bucket(sample)))continue;picked.push(sample);seen.add(bucket(sample));if(picked.length===policy.count)break;}
   for(const sample of eligible)if(!picked.includes(sample))picked.push(sample);
   // Unknown metrics may fill a recent sample, but never outrank known performance.
   const unknown=validTime.filter(sample=>!knownMetric(sample)).sort(byTime),supplement=[];
   if(picked.length<policy.count){for(const sample of unknown){if(seen.has(bucket(sample)))continue;supplement.push(sample);seen.add(bucket(sample));if(picked.length+supplement.length===policy.count)break;}}
   for(const sample of unknown)if(!supplement.includes(sample))supplement.push(sample);
   eligible=[...picked,...supplement];
  }
 }else eligible=all;
 const selected=eligible.slice(0,policy.count),coverage={scope:'fetched-page-only',candidateCount:all.length,eligibleCount:eligible.length,selectedCount:selected.length,requestedCount:policy.count,missingTimestampCount:policy.mode==='user-picked'?0:missingTimestampCount,missingMetricCount,hasMore:Boolean(hasMore),completeAccountCoverage:false,noteZh:policy.mode==='user-picked'?'按用户指定的视频顺序处理。':policy.mode==='balanced'?'优先比较已知互动指标，并覆盖时长和发布时间区间；近期指标未知的视频可按时间和时长补入，仍标记数据未知，不能称为表现好。这是元数据均衡，不代表视觉风格多样性。':policy.mode==='top-in-page'?'只在本页按已知互动指标排序；缺失指标不按零计算，不代表账号完整排行。':'仅在本次取得的一页候选中选择，不代表账号完整排行。'};
 if(policy.mode==='balanced')coverage.unknownMetricSelectedCount=selected.filter(sample=>!knownMetric(sample)).length;
 if(strictWindow)Object.assign(coverage,{scope:'bounded-recent-window',windowDays:30,windowStart:policy.windowStart,windowEnd:policy.windowEnd,unknownTimestampCount,futureTimestampCount,olderThanWindowCount,noteZh:'严格限定已知发布时间位于本任务冻结的近三十天窗口；旧片、未来与未知日期均排除，不补数量。 '+coverage.noteZh});
 if(['balanced','top-in-page'].includes(policy.mode))Object.assign(coverage,{selectionBasis:'metadata-only',metric,visualDiversityVerified:false});
 return{selected,coverage};
}
/** Validate AI comparison against only this task's completed visual evidence. Invalid output is never heuristically repaired. */
export function validateComparison(output,records){
 const invalid=()=>fail('RESEARCH_COMPARISON_OUTPUT','综合比较响应无效，未把未经验证的排名作为推荐。',409);
 if(!obj(output)||!['completed','pending','failed'].includes(output.status))invalid();
 const summaryZh=text(output.summaryZh,5000);if(!summaryZh)invalid();
 const metadata={};if(output.promptStatus!==undefined){if(!['completed','incomplete','failed','skipped'].includes(output.promptStatus))invalid();metadata.promptStatus=output.promptStatus;}
 if(output.providerCalls!==undefined){if(!obj(output.providerCalls)||![0,1].includes(output.providerCalls.comparison)||![0,1].includes(output.providerCalls.compilation))invalid();metadata.providerCalls={comparison:output.providerCalls.comparison,compilation:output.providerCalls.compilation};}
 if(obj(output.usage))metadata.usage=clone(output.usage);
 if(output.provider!==undefined)metadata.provider=text(output.provider,120);if(output.model!==undefined)metadata.model=text(output.model,200)||null;if(obj(output.models))metadata.models=Object.fromEntries(['comparison','compilation'].filter(key=>obj(output.models[key])).map(key=>[key,{provider:text(output.models[key].provider,120)||null,model:text(output.models[key].model,200)||null}]));
 if(output.status!=='completed')return{status:output.status,summaryZh,recommendations:[],excluded:[],...metadata};
 if(!Array.isArray(output.recommendations)||output.recommendations.length>3||!Array.isArray(output.excluded))invalid();
 const available=new Map(records.filter(item=>hasVisualEvidence(item.result)).map(item=>[item.recordId,item])),seen=new Set();
 const recommendations=output.recommendations.map(item=>{
  if(!obj(item)||!available.has(item.recordId)||seen.has(item.recordId))invalid();seen.add(item.recordId);
  const fields={recordId:item.recordId,reasonZh:text(item.reasonZh,3000),formZh:text(item.formZh,1000),materialThresholdZh:text(item.materialThresholdZh,3000)};if(!fields.reasonZh||!fields.formZh||!fields.materialThresholdZh)invalid();
  const record=available.get(item.recordId),measured=record.result.rhythm?.measurements?.durationSec,metadata=record.metadata?.duration,observations=record.result.visual.observations;
  const end=Number.isFinite(measured)&&measured>0?measured:Number.isFinite(metadata)&&metadata>0?metadata:Math.max(...observations.map(o=>Number.isFinite(o.endSec)?o.endSec:0));
  if(!Array.isArray(item.evidence)||!item.evidence.length||item.evidence.length>30)invalid();
  fields.evidence=item.evidence.map(e=>{if(!obj(e)||!Number.isFinite(e.startSec)||!Number.isFinite(e.endSec)||e.startSec<0||e.endSec<=e.startSec||e.endSec>end+0.001||!observations.some(o=>Number.isFinite(o.startSec)&&Number.isFinite(o.endSec)&&e.startSec<o.endSec&&e.endSec>o.startSec))invalid();return{startSec:e.startSec,endSec:e.endSec};});
  if(item.recreationPackage!==undefined){if(!obj(item.recreationPackage))invalid();fields.recreationPackage=clone(item.recreationPackage);}
  return fields;
 });
 const excluded=output.excluded.map(item=>{if(!obj(item)||!available.has(item.recordId)||seen.has(item.recordId)||!text(item.reasonZh,3000))invalid();seen.add(item.recordId);return{recordId:item.recordId,reasonZh:text(item.reasonZh,3000)};});
 if(seen.size!==available.size)invalid();
 return{status:'completed',summaryZh,recommendations,excluded,...metadata};
}
function startBusinessScope(plan){
 const names=['executionMode','source','userIntent','product','audience','topicId','topicTitle','productProfileVersion','analysisFocus','materialStatus','styleVersionId','exclusions'];
 return{...Object.fromEntries(names.map(key=>[key,plan[key]??null])),selectionPolicy:{mode:plan.selectionPolicy.mode,count:plan.selectionPolicy.count,metric:plan.selectionPolicy.metric||null,windowDays:plan.selectionPolicy.windowDays||null}};
}
function wholeStudyCompletion(job,plan){
 if(plan.executionMode!=='account-study'||plan.budgetScope?.maxComparisonCalls!==1)return{complete:true};
 const comparison=job.comparison;if(comparison?.status!=='completed')return{complete:false,noteZh:comparison?.status==='failed'?'逐条分析结果已保存，综合比较未完成；本次研究仅部分完成，不会自动重试。':'逐条分析结果已保存，综合比较仍待完成；本次研究仅部分完成。'};
 const recommendations=Array.isArray(comparison.recommendations)?comparison.recommendations:[];
 if(!recommendations.length&&['skipped','completed'].includes(comparison.promptStatus))return{complete:true};
 if(comparison.promptStatus!=='completed'||recommendations.some(item=>!['ready','needs-input'].includes(item.recreationPackage?.status)||!text(item.recreationPackage?.fullPromptText,100000)))return{complete:false,noteZh:'逐条分析与综合比较已保存，完整提示词尚未全部整理完成；本次研究仅部分完成，不会自动重试。'};
 return{complete:true};
}
function summarizeAccount(job){
 const successful=job.results.filter(item=>hasVisualEvidence(item.result)),groups=new Map(),tags=new Set();
 for(const item of successful){for(const tag of item.result.tagsZh||[])if(typeof tag==='string'&&tag.trim())tags.add(tag.trim());const names=[...new Set((item.result.recommendations||[]).map(r=>text(r.nameZh,120)).filter(Boolean))];for(const nameZh of names.length?names:['未明确归类']){if(!groups.has(nameZh))groups.set(nameZh,[]);groups.get(nameZh).push(item.recordId);}}
 return{tagsZh:[...tags].slice(0,16),styleGroups:[...groups].map(([nameZh,recordIds])=>({nameZh,recordIds})),sampleCount:successful.length,noteZh:`仅归纳本任务中 ${successful.length} 条已有画面证据的视频；标签与分组来自本次模型分析，不引用旧案例，也不代表整个账号或复刻成功。`};
}
export function createResearchService({root,history,collectAccount,resolveSource,analyzeVideo,compareVideos,now=()=>new Date().toISOString(),isAllowed=sameOrigin}={}){
 if(!history)throw new TypeError('Research requires the existing history store');
 const store=createResearchStore({root,now});let runtime=runtimes.get(store.root);if(!runtime){runtime={ready:null,running:null,pending:false};runtimes.set(store.root,runtime);}
 const active=()=>history.snapshot({view:'active'});
 async function ready(){if(!runtime.ready)runtime.ready=(async()=>{if(await store.executorActive())return;await store.transaction(state=>{for(const job of state.jobs){if(terminal.has(job.phase)||job.phase==='waiting_selection'||processAlive(job.executionOwnerPid))continue;job.phase=job.results.length?'partial':'failed';job.error={code:'RESEARCH_INTERRUPTED',message:'应用上次退出时研究未完成；已保留结果。为避免重复收费，没有自动重发。',billingUnknown:job.events.some(e=>e.detail?.status==='requesting')};job.updatedAt=now();job.events.push({phase:job.phase,at:now(),detail:job.error});}return{};});})();return runtime.ready;}
 async function visible(ids){const snap=await active(),set=new Set(snap.records.map(r=>r.id));return ids.every(id=>set.has(id));}
 async function checkSource(source){const all=await history.snapshot({view:'all'}),ids=recordIdsFromSource(source);if(all.records.some(r=>ids.includes(r.id)&&(r.hidden||r.trashedAt)))fail('RESEARCH_HIDDEN','参考视频已隐藏或在回收站，请先恢复后处理。',409);}
 async function checkPlan(plan,scope){owned(plan,scope);await checkSource(plan.source);if(plan.styleVersionSnapshot&&!await visible(plan.styleVersionSnapshot.recordIds))fail('RESEARCH_HIDDEN','引用的风格证据已隐藏或在回收站。',409);if(plan.topicId){const snap=await active();if(!snap.topics.some(t=>t.id===plan.topicId))fail('RESEARCH_TOPIC','专题不存在或已无可见资料。',404);}return plan;}
 async function checkJob(job,scope){owned(job,scope);await checkSource(job.plan.source);if(job.resolvedSource)await checkSource(job.resolvedSource);if(job.plan.styleVersionSnapshot&&!await visible(job.plan.styleVersionSnapshot.recordIds))fail('RESEARCH_HIDDEN','研究引用的风格证据已隐藏或在回收站。',409);if(!await visible(job.selectedRecordIds))fail('RESEARCH_HIDDEN','研究引用了隐藏或回收站记录，请先恢复后查看。',409);return job;}
 async function publicJob(job,scope){await checkJob(job,scope);const result=clone(job);if(Array.isArray(result.candidates)){const ids=new Set((await active()).records.map(r=>r.id));result.candidates=result.candidates.filter(c=>ids.has(c.recordId));result.hiddenCandidateCount=job.candidates.length-result.candidates.length;}return result;}
 async function updateJob(jobId,callback){return store.transaction(state=>{const job=state.jobs.find(j=>j.jobId===jobId);if(!job)fail('RESEARCH_NOT_FOUND','研究任务不存在。',404);callback(job,state);job.updatedAt=now();return job;});}
 async function checkpoint(jobId,phase,detail={}){const current=(await store.read()).jobs.find(j=>j.jobId===jobId);if(current?.cancelRequested)fail('RESEARCH_CANCELLED','已取消尚未开始的步骤。',409);await checkJob(current);return updateJob(jobId,(job,state)=>{if(job.cancelRequested)fail('RESEARCH_CANCELLED','已取消尚未开始的步骤。',409);if(job.plan.executionMode==='account-study'&&job.plan.budgetScope?.maxComparisonCalls===1){const livePlan=state.plans.find(item=>item.planId===job.planId);if(!livePlan||livePlan.planRevision!==job.planRevision||livePlan.planHash!==job.confirmedPlanHash||job.plan.planHash!==job.confirmedPlanHash)fail('RESEARCH_STALE','研究版本或确认内容已变化，已阻止旧步骤继续执行。',409);}if(stages.has(phase))job.phase=phase;job.events.push({phase,at:now(),detail});if(detail.status==='requesting'){const step=detail.step,key=step==='account-list'?'accountList':step==='resolve'?'mediaResolution':step==='vl'?'vl':step==='asr'?'asr':step==='comparison'?'comparison':null;if(key){job.actualUsage.providerCalls??={tikhub:0,accountList:0,mediaResolution:0,vl:0,asr:0};job.actualUsage.providerCalls[key]=(job.actualUsage.providerCalls[key]||0)+1;if(['accountList','mediaResolution'].includes(key))job.actualUsage.providerCalls.tikhub++;}}if(job.events.length>500)job.events=job.events.slice(-500);if(detail.recordId){const video=job.videos.find(v=>v.recordId===detail.recordId);if(video){video.stage=phase;video.detail=detail;video.updatedAt=now();}}});}
 async function collectBoundedAccount(jobId,plan){
  const bounded=plan.executionMode==='account-study',maxPages=bounded?Math.min(2,plan.budgetScope.maxAccountPages||1):1,maxRows=bounded?Math.min(24,plan.budgetScope.maxMetadataCandidates||12):12;
  let cursor=null,payload=null,rows=[],pagesFetched=0,metadataTruncated=false,collectionStopReason='page-limit';const seenCursors=new Set(),totals={excludedOtherOwners:0,excludedNonVideos:0,unknownOwnerCount:0};
  for(let page=0;page<maxPages;page++){
   await checkpoint(jobId,'collecting',{step:'account-list',status:'requesting',provider:'TikHub',page:page+1});
   let response;try{response=await collectAccount({url:plan.source.url,consent:true,...(cursor?{cursor}:{})});}catch(error){if(!payload||['RESEARCH_CANCELLED','RESEARCH_HIDDEN'].includes(error.code))throw error;collectionStopReason='page-failed';await updateJob(jobId,current=>{current.collectionError=safeError(error);current.events.push({phase:'collection_partial',at:now(),detail:current.collectionError});});break;}
   if(plan.source.platform==='Douyin'?(response?.account?.platform!=='Douyin'||response?.account?.secUid!==plan.source.secUid):response?.account?.username!==plan.source.username)fail('RESEARCH_ACCOUNT','采集结果账号与确认单不一致。',409);
   if(response.collectionSource==='cache')await updateJob(jobId,current=>{current.actualUsage.providerCalls.accountList=Math.max(0,current.actualUsage.providerCalls.accountList-1);current.actualUsage.providerCalls.tikhub=Math.max(0,current.actualUsage.providerCalls.tikhub-1);current.events.push({phase:'collecting',at:now(),detail:{step:'account-list',status:'cache-hit',paidApiCalls:0,collectedAt:response.collectedAt||null}});});
   pagesFetched++;const pageRows=Array.isArray(response.samples)?response.samples:[];metadataTruncated||=pageRows.length>12;rows.push(...pageRows.slice(0,Math.min(12,maxRows-rows.length)));payload={...response,samples:rows};await updateJob(jobId,current=>{current.collectionPages??=[];current.collectionPages.push({page:pagesFetched,source:response.collectionSource||'provider',collectedAt:response.collectedAt||null,samples:clone(pageRows.slice(0,12))});});for(const key of Object.keys(totals))totals[key]+=response[key]||0;
   if(!bounded){collectionStopReason='single-page';break;}
   const hidden=new Set((await history.snapshot({view:'all'})).records.filter(r=>r.hidden||r.trashedAt).map(r=>r.id)),safeRows=rows.filter(row=>{try{return!hidden.has(canonicalHistoryUrl(row.url).id);}catch{return false;}});
   const selected=selectResearchSamples(safeRows,plan.selectionPolicy,{now:now(),hasMore:response.hasMore});
   if(selected.selected.length>=plan.selectionPolicy.count){collectionStopReason='enough-eligible';break;}
   if(!response.hasMore){collectionStopReason='no-more-pages';break;}
   if(page+1>=maxPages||rows.length>=maxRows){collectionStopReason='page-limit';break;}
   const next=response.nextCursor;if(typeof next!=='string'||!next||next.length>2048||/[\u0000-\u001f\u007f]/.test(next)){collectionStopReason='missing-cursor';break;}
   if(next===cursor||seenCursors.has(next)){collectionStopReason='repeated-cursor';break;}
   seenCursors.add(next);cursor=next;
  }
  return{...payload,...totals,pagesFetched,metadataTruncated,collectionStopReason};
 }
 async function compareCompletedJob(jobId,plan){
  const current=(await store.read()).jobs.find(j=>j.jobId===jobId);await checkJob(current);if(current.cancelRequested)fail('RESEARCH_CANCELLED','已取消尚未开始的步骤。',409);
  const records=current.results.filter(item=>hasVisualEvidence(item.result)).map(item=>({recordId:item.recordId,metadata:clone(current.selectedMetadata?.find(row=>row.recordId===item.recordId)||{}),result:clone(item.result)}));
  if(typeof compareVideos!=='function'||!records.length){await updateJob(jobId,job=>{job.comparison={status:'pending',summaryZh:records.length?'本次逐条分析已保存，综合比较服务尚未接通。':'本次缺少成功的画面证据，尚不能综合比较。',recommendations:[],excluded:[]};});return;}
  await checkpoint(jobId,'comparing',{step:'comparison',status:'requesting'});
  try{const output=await compareVideos({plan:clone(plan),job:clone(current),records});await checkpoint(jobId,'comparing',{step:'comparison',status:'received'});const comparison=validateComparison(output,records);await updateJob(jobId,job=>{job.comparison=comparison;if(comparison.providerCalls){job.actualUsage.providerCalls.comparison=comparison.providerCalls.comparison;job.actualUsage.providerCalls.promptCompile=comparison.providerCalls.compilation;job.actualUsage.providerCalls.deepseek=comparison.providerCalls.comparison+comparison.providerCalls.compilation;}if(comparison.usage)job.actualUsage.comparison=clone(comparison.usage);for(const item of comparison.recommendations){if(item.recreationPackage){const analyzed=job.results.find(row=>row.recordId===item.recordId);if(analyzed){analyzed.result.recreationPackage=clone(item.recreationPackage);analyzed.result.recreationPackageSource='deepseek-comparison';}}const candidate=job.styleCandidates.find(c=>c.recordIds.length===1&&c.recordIds[0]===item.recordId);if(candidate){candidate.comparisonRecommendation=clone(item);if(item.recreationPackage)candidate.recreationPackage=clone(item.recreationPackage);}}job.events.push({phase:'comparison_saved',at:now(),detail:{status:comparison.status}});});}
  catch(error){if(['RESEARCH_CANCELLED','RESEARCH_HIDDEN'].includes(error?.code))throw error;await updateJob(jobId,job=>{job.comparison={status:'failed',summaryZh:'综合比较未完成；逐条拆解已保存，不会自动重试。',recommendations:[],excluded:[],error:safeError(error)};});}
 }
 async function processJob(job){
  const jobId=job.jobId,plan=job.plan;
  try{
   await updateJob(jobId,current=>{current.executionOwnerPid=process.pid;});await checkPlan(plan);
   if(plan.executionMode==='planning-only'){await updateJob(jobId,current=>{if(current.cancelRequested)fail('RESEARCH_CANCELLED','已取消尚未开始的步骤。',409);current.phase='completed';current.completedAt=now();current.noteZh='理解卡已确认并保存在本机。本次仅验证计划与确认流程，没有采集、分析或生成视频。';current.actualUsage={records:[],providerCalls:{tikhub:0,vl:0,asr:0},mediaTransfers:0};current.events.push({phase:'completed',at:now(),detail:{executionMode:'planning-only',noteZh:current.noteZh}});});return;}
   const capability=sourceCapability(plan.source);if(!capability.available)fail('RESEARCH_CAPABILITY',capability.reasonZh,409);
   let effectivePlan={...plan,source:job.resolvedSource||plan.source},selectedIds=[];
   if(job.phase==='selection_confirmed'){
    const current=(await store.read()).jobs.find(j=>j.jobId===jobId);if(current.cancelRequested)fail('RESEARCH_CANCELLED','已取消尚未开始的步骤。',409);const latest=(await store.read()).plans.find(p=>p.planId===plan.planId);if(!latest||latest.planRevision!==job.planRevision)fail('RESEARCH_STALE','理解卡已变化，旧候选不能继续分析。',409);await checkJob(current);selectedIds=[...current.selectedRecordIds];
   }else{
    await checkpoint(jobId,'collecting');
    if(plan.source.kind==='douyin-share'){
     if(typeof resolveSource!=='function')fail('RESEARCH_SOURCE_RESOLVER','抖音分享链接展开服务尚未连接；请提供完整主页或视频链接。',409);
     await checkpoint(jobId,'collecting',{step:'source-link',status:'requesting',provider:'public-redirect-headers'});
     const resolved=await resolveSource(plan.source.url);if(!['account','video'].includes(resolved?.kind))fail('RESEARCH_SOURCE','分享链接未解析成账号或视频，请补充完整链接。',409);
     if(['candidate-selection','account-study'].includes(plan.executionMode)&&resolved.kind!=='account')fail('RESEARCH_SOURCE_KIND','这条分享链接实际是单条视频；账号研究需要账号主页，单视频请使用原有的一到两条研究入口。',409);
     const resolvedSource=resolved.kind==='account'?normalizeResearchSource({kind:'account',url:resolved.url}):normalizeResearchSource({kind:'videos',urls:[resolved.url]});effectivePlan={...plan,source:resolvedSource,selectionPolicy:resolved.kind==='video'?{mode:'user-picked',count:1}:plan.selectionPolicy};
     await updateJob(jobId,current=>{current.resolvedSource=resolvedSource;current.sourceResolution={status:'completed',redirectCount:resolved.redirectCount??null,networkKind:'public-response-headers',paidApiCalls:0};});
    }
    let payload;
    if(effectivePlan.source.kind==='account'){
     if(typeof collectAccount!=='function')fail('RESEARCH_COLLECTOR','账号采集服务尚未连接。',409);
     payload=await collectBoundedAccount(jobId,effectivePlan);
    }else payload={account:null,samples:effectivePlan.source.urls.map(url=>({url,title:'待分析参考视频',ownerVerified:true})),provider:'user-provided',collectedAt:now(),hasMore:false};
    await checkpoint(jobId,'selecting');const candidateMode=plan.executionMode==='candidate-selection',all=await history.snapshot({view:'all'}),hiddenIds=new Set(all.records.filter(r=>r.hidden||r.trashedAt).map(r=>r.id));
    const safeSamples=(Array.isArray(payload.samples)?payload.samples:[]).filter(s=>{try{return!hiddenIds.has(canonicalHistoryUrl(s.url).id);}catch{return false;}});
    const selection=selectResearchSamples(safeSamples,{...effectivePlan.selectionPolicy,count:candidateMode?plan.candidateLimit:effectivePlan.selectionPolicy.count},{now:now(),hasMore:payload.hasMore});
    if(payload.coverage?.noteZh)selection.coverage.noteZh=plan.executionMode==='account-study'?selection.coverage.noteZh+' '+payload.coverage.noteZh:payload.coverage.noteZh;if(plan.executionMode==='account-study')Object.assign(selection.coverage,{maxMetadataCandidates:plan.budgetScope.maxMetadataCandidates||12,pagesFetched:payload.pagesFetched||1,metadataTruncated:payload.metadataTruncated===true,collectionStopReason:payload.collectionStopReason||'single-page',collectionSource:payload.collectionSource||'provider'});selection.coverage.excludedOtherOwners=payload.excludedOtherOwners||0;selection.coverage.excludedNonVideos=payload.excludedNonVideos||0;selection.coverage.unknownOwnerCount=payload.unknownOwnerCount||0;
    const ingestPayload=candidateMode?{...payload,samples:selection.selected}:payload,ingested=await history.ingest(ingestPayload);selectedIds=selection.selected.map(s=>s.id);let topicId=plan.topicId;
    if(!topicId&&plan.topicTitle){const created=await history.mutate({action:'create-topic',title:plan.topicTitle,kind:effectivePlan.source.kind==='account'?'brand':'topic',ids:selectedIds});topicId=created.topic.id;}
    if(!topicId)topicId=(await active()).topics.find(t=>t.recordIds.some(id=>selectedIds.includes(id)))?.id||null;
    if(topicId&&selectedIds.length)await history.mutate({action:'link-topic',topicId,ids:selectedIds});
    await updateJob(jobId,(current,state)=>{current.topicId=topicId;const currentPlan=state.plans.find(p=>p.planId===current.planId);if(currentPlan?.planRevision===current.planRevision)currentPlan.resolvedTopicId=topicId;current.coverage=selection.coverage;current.batchId=ingested.batchId;current.selectedMetadata=selection.selected.map(item=>({recordId:item.id,url:item.url,publishedAt:item.publishedAt||null,views:item.views??null,likes:item.likes??null,duration:item.duration??null}));current.selectedRecordIds=candidateMode?[]:selectedIds;current.videos=candidateMode?[]:selectedIds.map(recordId=>({recordId,stage:'selected',status:'pending'}));});
    if(!selectedIds.length)fail('RESEARCH_NO_SAMPLES','本次候选缺少可比较的发布时间或指标，或没有可见视频；未启动分析。',409);
    if(candidateMode){await updateJob(jobId,current=>{if(current.cancelRequested)fail('RESEARCH_CANCELLED','已取消尚未开始的步骤。',409);current.candidates=selection.selected.map(s=>({recordId:s.id,url:s.url,title:s.title||'未提供标题',publishedAt:s.publishedAt||null,views:Number.isFinite(s.views)?s.views:null,likes:Number.isFinite(s.likes)?s.likes:null,duration:Number.isFinite(s.duration)?s.duration:null,ownerVerified:s.ownerVerified===true,status:'metadata-only',styleStatus:'not-analyzed'}));current.candidateSetHash=hash([current.jobId,current.planRevision,current.candidates]);current.phase='waiting_selection';current.noteZh='已保存最多八条元数据候选；尚未下载、分析画面或识别风格。请选择一到两条后确认深拆。';current.events.push({phase:'waiting_selection',at:now(),detail:{candidateCount:current.candidates.length,paidAnalysisCalls:0}});});return;}
   }
   for(const [videoIndex,recordId] of selectedIds.entries()){
    const freeRecovery=job.resumeUnstarted?.firstRecordId===recordId;let currentVisualSuccess=false;
    try{
     await checkpoint(jobId,'resolving_media',{recordId});const record=(await active()).records.find(r=>r.id===recordId);if(!record)fail('RESEARCH_HIDDEN','视频已隐藏或移入回收站。',409);if(typeof analyzeVideo!=='function')fail('RESEARCH_ANALYZER','视频分析服务尚未连接。',409);
     const result=await analyzeVideo({record,plan:effectivePlan,jobId,onStage:async(stage,detail={})=>{if(freeRecovery&&detail.status==='requesting')fail('RESEARCH_RESUME_PAID','首条只能免费读取已有响应，已阻止重新发起供应商请求。',409);return checkpoint(jobId,stage,{...detail,recordId});}});if(freeRecovery&&result?.cached!==true)fail('RESEARCH_RESUME_CACHE','首条没有确认来自已有响应，已停止后续步骤。',409);
     await checkpoint(jobId,'synthesizing',{recordId});const normalized=clone(result);if(!obj(normalized))fail('RESEARCH_RESULT','分析结果格式无效。',409);currentVisualSuccess=hasVisualEvidence(normalized);
     await updateJob(jobId,current=>{const item={recordId,result:normalized,completedAt:now()};const resultIndex=current.results.findIndex(value=>value.recordId===recordId);if(resultIndex>=0)current.results[resultIndex]=item;else current.results.push(item);const usage={recordId,usage:normalized.usage||null,mediaResolutionCached:normalized.steps?.resolve?.cached===true},usageIndex=current.actualUsage.records.findIndex(value=>value.recordId===recordId);if(usageIndex>=0)current.actualUsage.records[usageIndex]=usage;else current.actualUsage.records.push(usage);if(normalized.steps?.resolve?.cached===true&&!current.events.some(event=>event.detail?.recordId===recordId&&event.detail?.step==='resolve'&&event.detail?.status==='cache-hit')&&current.events.some(event=>event.detail?.recordId===recordId&&event.detail?.step==='resolve'&&event.detail?.status==='requesting')){current.actualUsage.providerCalls.mediaResolution=Math.max(0,(current.actualUsage.providerCalls.mediaResolution||0)-1);current.actualUsage.providerCalls.tikhub=Math.max(0,(current.actualUsage.providerCalls.tikhub||0)-1);current.actualUsage.mediaResolutionCacheHits=(current.actualUsage.mediaResolutionCacheHits||0)+1;current.events.push({phase:'resolving_media',at:now(),detail:{recordId,step:'resolve',status:'cache-hit',paidApiCalls:0}});}const video=current.videos.find(v=>v.recordId===recordId);video.status=normalized.status==='partial'?'partial':'completed';video.stage='saved';video.updatedAt=now();
      if(plan.executionMode==='account-study'&&hasVisualEvidence(normalized)&&current.styleCandidates.length<6&&!current.styleCandidates.some(candidate=>candidate.candidateId==='candidate_'+hash([jobId,recordId,0]).slice(0,24))){const recommendation=(Array.isArray(normalized.recommendations)?normalized.recommendations:[])[0]||{nameZh:normalized.titleZh||'本次视频方案',status:'unassessed',reasonZh:'本次未提供复刻资格判断；保留拆解不表示复刻效果已验证。'};current.styleCandidates.push({candidateId:'candidate_'+hash([jobId,recordId,0]).slice(0,24),recordIds:[recordId],sourceJobId:jobId,topicId:current.topicId,nameZh:text(recommendation.nameZh,120)||'本次视频方案',recommendation:clone(recommendation),recreationPackage:normalized.recreationPackage?clone(normalized.recreationPackage):null,status:'candidate',createdAt:now()});}
      if(plan.executionMode!=='account-study')for(const [index,recommendation] of (Array.isArray(normalized.recommendations)?normalized.recommendations:[]).slice(0,2).entries()){if(recommendation.status==='notRecommended')continue;const nameZh=text(recommendation.nameZh,120)||'待确认风格',existing=current.styleCandidates.find(c=>c.nameZh===nameZh);if(existing){existing.recordIds=[...new Set([...existing.recordIds,recordId])];existing.recommendation.evidence=[...(existing.recommendation.evidence||[]),...(recommendation.evidence||[])];continue;}if(current.styleCandidates.length>=2)continue;current.styleCandidates.push({candidateId:'candidate_'+hash([jobId,recordId,index]).slice(0,24),recordIds:[recordId],sourceJobId:jobId,topicId:current.topicId,nameZh,recommendation,status:'candidate',createdAt:now()});}
     });
     if(hasVisualEvidence(normalized)&&normalized.titleZh&&history.attachAnalysisMetadata)await history.attachAnalysisMetadata(recordId,{displayTitleZh:normalized.titleZh,summaryZh:normalized.summaryZh||'',autoTagsZh:normalized.tagsZh||[],analysisRef:{recordId,analysisId:normalized.evidenceRef?.analysisId||jobId,provider:'mosi',model:'moss-vl-1.0',completedAt:now()}});
    }catch(error){const safe=safeError(error);await updateJob(jobId,current=>{const video=current.videos.find(v=>v.recordId===recordId);video.status=error.code==='RESEARCH_CANCELLED'?'cancelled':'failed';video.error=safe;video.updatedAt=now();current.errors.push({recordId,...safe});});if(['RESEARCH_CANCELLED','RESEARCH_HIDDEN','RESEARCH_STALE'].includes(error.code))throw error;}
    if(videoIndex===0&&plan.budgetScope.firstVideoGate===true){const fresh=(await store.read()).jobs.find(j=>j.jobId===jobId),first=fresh.results.find(item=>item.recordId===recordId);if(!currentVisualSuccess||!hasVisualEvidence(first?.result)){await updateJob(jobId,current=>{current.analysisGate={status:'blocked',recordId,messageZh:'首条视频尚未取得成功的画面分析，已停止后续扩量；其余视频没有发起分析，也不会自动重试。'};current.noteZh=current.analysisGate.messageZh;for(const video of current.videos.filter(v=>v.status==='pending')){video.status='blocked';video.stage='not-started';video.reasonZh=current.analysisGate.messageZh;}current.events.push({phase:'analysis_gate_blocked',at:now(),detail:current.analysisGate});});break;}await updateJob(jobId,current=>{current.analysisGate={status:'passed',recordId};if(current.resumeUnstarted)current.noteZh='首条已从现有响应恢复画面分析，继续本次原定但尚未开始的视频；没有重新采集或重跑首条收费步骤。';});}
   }
   if(plan.executionMode==='account-study'&&plan.budgetScope.maxComparisonCalls===1)await compareCompletedJob(jobId,effectivePlan);
   await updateJob(jobId,current=>{const expected=plan.executionMode==='candidate-selection'?current.selectedRecordIds.length:effectivePlan.selectionPolicy.count,allAnalysesComplete=current.videos.every(v=>v.status==='completed')&&current.selectedRecordIds.length===expected,study=wholeStudyCompletion(current,plan),allComplete=allAnalysesComplete&&study.complete;current.phase=current.analysisGate?.status==='blocked'?'partial':current.results.length?(allComplete?'completed':'partial'):'failed';if(current.analysisGate?.status!=='blocked'&&current.results.length&&!study.complete)current.noteZh=study.noteZh;current.completedAt=now();current.events.push({phase:current.phase,at:now(),detail:{}});});
  }catch(error){await updateJob(jobId,current=>{current.phase=error.code==='RESEARCH_CANCELLED'?'cancelled':current.results.length?'partial':'failed';current.error=safeError(error);current.completedAt=now();current.events.push({phase:current.phase,at:now(),detail:current.error});});}
 }
 function schedule(){if(runtime.running){runtime.pending=true;return;}runtime.pending=false;runtime.running=Promise.resolve().then(async()=>{let release;while(!(release=await store.acquireExecutor())){if(!(await store.read()).jobs.some(j=>['confirmed','selection_confirmed'].includes(j.phase)&&!j.cancelRequested))return;await pause(100);}try{while(true){const state=await store.read(),next=state.jobs.find(j=>['confirmed','selection_confirmed'].includes(j.phase)&&!j.cancelRequested);if(!next)break;await processJob(next);}}finally{await release();}}).catch(async error=>{await store.transaction(state=>{for(const job of state.jobs.filter(j=>['confirmed','selection_confirmed'].includes(j.phase))){job.phase='failed';job.error=safeError(error);job.updatedAt=now();}return{};}).catch(()=>{});}).finally(()=>{runtime.running=null;if(runtime.pending)schedule();});}
 async function validatedCore(payload,anchorAt=now()){
  if(!obj(payload))fail('RESEARCH_PLAN','理解卡格式无效。');const data=normalizePlan(payload,anchorAt);await checkSource(data.source);
  if(data.topicId&&!((await active()).topics.some(t=>t.id===data.topicId)))fail('RESEARCH_TOPIC','请选择当前可见的品牌或专题。',404);
  let styleVersionSnapshot=null;if(data.styleVersionId){const style=(await store.read()).styles.find(s=>s.styleVersionId===data.styleVersionId);if(!style||!await visible(style.recordIds))fail('RESEARCH_STYLE','风格版本不存在或引用了不可见资料。',404);if(data.topicId&&style.topicId!==data.topicId)fail('RESEARCH_STYLE','请选择当前专题内的风格版本。',409);styleVersionSnapshot=style;}
  return {...data,styleVersionSnapshot};
 }
 function newConfirmedJob(plan){const requestKey=hash([plan.planId,plan.planRevision,plan.planHash]);return {jobId:'research_'+randomUUID(),planId:plan.planId,planRevision:plan.planRevision,confirmedPlanHash:plan.planHash,requestKey,plan:clone(plan),sessionId:plan.sessionId,workbenchId:plan.workbenchId,topicId:plan.topicId,phase:'confirmed',confirmedAt:now(),confirmedBy:'user-ui',executionOwnerPid:process.pid,createdAt:now(),updatedAt:now(),selectedRecordIds:[],videos:[],results:[],styleCandidates:[],estimatedUsage:{calls:plan.estimatedCalls},actualUsage:{records:[],providerCalls:{tikhub:0,accountList:0,mediaResolution:0,vl:0,asr:0},callCountPolicy:'attempted-stage-calls-not-invoice'},errors:[],events:[{phase:'confirmed',at:now(),detail:{}}],cancelRequested:false};}
 const service={
  async preparePlan(payload,scope={}){await ready();const previous=payload?.planId?(await store.read()).plans.find(p=>p.planId===payload.planId):null,anchorAt=previous?.createdAt||now(),core=await validatedCore(payload,anchorAt),planHash=hash(core);
   return store.transaction(state=>{let plan;if(payload.planId){plan=state.plans.find(p=>p.planId===id(payload.planId,'理解卡'));if(!plan)fail('RESEARCH_NOT_FOUND','理解卡不存在。',404);owned(plan,scope);if(payload.expectedRevision!==plan.planRevision)fail('RESEARCH_STALE','理解卡已更新，请重新查看并确认最新版本。',409);if(plan.planHash===planHash)return{planId:plan.planId,planRevision:plan.planRevision,plan};for(const job of state.jobs.filter(j=>j.planId===plan.planId&&j.planRevision===plan.planRevision&&!terminal.has(j.phase))){job.cancelRequested=true;job.updatedAt=now();job.events.push({phase:'confirmation_invalidated',at:now(),detail:{message:'理解卡已修改，旧版本尚未开始的步骤停止；已经送达供应商的请求可能已计费。'}});if(['confirmed','waiting_selection','selection_confirmed'].includes(job.phase)){job.phase='cancelled';job.completedAt=now();}}plan={...plan,...core,planRevision:plan.planRevision+1,planHash,status:'awaiting_confirmation',updatedAt:now(),confirmedJobId:null};state.plans[state.plans.findIndex(p=>p.planId===plan.planId)]=plan;}else{plan={...core,planId:'plan_'+randomUUID(),planRevision:1,planHash,status:'awaiting_confirmation',sessionId:scope.sessionId||null,workbenchId:scope.workbenchId||null,createdAt:anchorAt,updatedAt:now(),confirmedJobId:null};state.plans.push(plan);}return{planId:plan.planId,planRevision:plan.planRevision,plan};});
  },
  async startResearch(payload,scope={}){
   await ready();if(!obj(payload))fail('RESEARCH_PLAN','研究请求格式无效。');const requestId=id(payload.requestId,'请求');
   if(payload.executionMode!==undefined&&payload.executionMode!=='account-study')fail('RESEARCH_EXECUTION_MODE','一键账号研究仅支持账号研究模式。');
   if(payload.planId||payload.expectedRevision!==undefined)fail('RESEARCH_START_SCOPE','一键研究会创建独立任务；修改旧理解卡请使用原有入口。',409);
   const requestScope={sessionId:scope.sessionId||null,workbenchId:scope.workbenchId||null};
   const result=await store.transaction(async state=>{
    const prior=state.jobs.find(job=>job.startRequestId===requestId),anchorAt=prior?.plan.createdAt||now();
    const input=prior?{...payload,selectionPolicy:{...(payload.selectionPolicy||{}),count:payload.selectionPolicy?.count??prior.plan.selectionPolicy.count}}:payload;
    const core=await validatedCore({...input,executionMode:'account-study'},anchorAt),planHash=hash(core),startScopeHash=hash([core,requestScope]);
    const business=startBusinessScope(core);if(prior&&!prior.plan.selectionPolicy.windowDays&&payload.selectionPolicy?.windowDays===undefined)business.selectionPolicy.windowDays=null;
    const startSemanticHash=hash([business,requestScope]);
    if(prior){const savedHash=prior.startSemanticHash||hash([startBusinessScope(prior.plan),{sessionId:prior.sessionId||null,workbenchId:prior.workbenchId||null}]);if(savedHash!==startSemanticHash)fail('RESEARCH_START_CONFLICT','同一处理请求已绑定其他内容或会话；修改后请开始一个新的研究请求。',409);return{planId:prior.planId,planRevision:prior.planRevision,jobId:prior.jobId,job:prior,duplicate:true};}
    if(!core.sourceCapability.available)fail('RESEARCH_CAPABILITY',core.sourceCapability.reasonZh,409);
    const plan={...core,planId:'plan_'+randomUUID(),planRevision:1,planHash,status:'awaiting_confirmation',...requestScope,createdAt:anchorAt,updatedAt:now(),confirmedJobId:null};
    const job=newConfirmedJob(plan);Object.assign(job,{startRequestId:requestId,startScopeHash,startSemanticHash,startedVia:'user-ui-start'});job.events[0].detail={action:'start',executionMode:'account-study'};
    plan.status='confirmed';plan.confirmedJobId=job.jobId;state.plans.push(plan);state.jobs.push(job);
    return{planId:plan.planId,planRevision:plan.planRevision,jobId:job.jobId,job,duplicate:false};
   });
   if(!result.duplicate)schedule();return{...result,job:await publicJob(result.job,scope)};
  },
  async getPlan(input,scope={}){await ready();const plan=(await store.read()).plans.find(p=>p.planId===id(typeof input==='string'?input:input?.planId,'理解卡'));if(!plan)fail('RESEARCH_NOT_FOUND','理解卡不存在。',404);return clone(await checkPlan(plan,scope));},
  async confirmPlan({planId,planRevision}={}){await ready();const current=await service.getPlan({planId});const capability=sourceCapability(current.source);if(current.executionMode!=='planning-only'&&!capability.available)fail('RESEARCH_CAPABILITY',capability.reasonZh,409);if(current.planRevision!==planRevision)fail('RESEARCH_STALE','理解卡已变化，请确认最新版本。',409);const result=await store.transaction(state=>{const plan=state.plans.find(p=>p.planId===planId);if(plan.planRevision!==planRevision)fail('RESEARCH_STALE','理解卡已变化，请确认最新版本。',409);const requestKey=hash([planId,planRevision,plan.planHash]),prior=state.jobs.find(j=>j.requestKey===requestKey);if(prior)return{jobId:prior.jobId,job:prior,duplicate:true};const job=newConfirmedJob(plan);state.jobs.push(job);plan.status='confirmed';plan.confirmedJobId=job.jobId;return{jobId:job.jobId,job,duplicate:false};});if(!result.duplicate)schedule();return{...result,job:await publicJob(result.job)};},
  async getJob(input,scope={}){await ready();const job=(await store.read()).jobs.find(j=>j.jobId===id(typeof input==='string'?input:input?.jobId,'研究任务'));if(!job)fail('RESEARCH_NOT_FOUND','研究任务不存在。',404);return publicJob(job,scope);},
  async readResult(input,scope={}){const job=await service.getJob(input,scope),confirmedStyles=(await store.read()).styles.filter(style=>style.sourceJobId===job.jobId);return{jobId:job.jobId,topicId:job.topicId,status:job.phase,executionMode:job.plan.executionMode||'research',noteZh:job.noteZh||null,actualUsage:job.actualUsage,coverage:job.coverage||null,results:job.results,styleCandidates:job.styleCandidates,confirmedStyles,accountSummary:job.plan.executionMode==='account-study'?summarizeAccount(job):null,comparison:job.comparison||{status:'pending',summaryZh:'尚未完成本次视频综合比较。',recommendations:[],excluded:[]},candidates:job.candidates||[],candidateSetHash:job.candidateSetHash||null,planRevision:job.planRevision,errors:job.errors,error:job.error||null,evidencePolicy:'原片观察、机器测量、模型建议与用户采用分开记录；本次少量样本不代表全账号。'};},
  async selectCandidates({jobId,planRevision,candidateSetHash,recordIds}={}){await ready();const current=await service.getJob({jobId});if(current.plan.executionMode!=='candidate-selection')fail('RESEARCH_SELECTION','此任务不是候选选择模式。',409);if(!Array.isArray(recordIds)||!recordIds.length||recordIds.length>current.plan.selectionPolicy.count||new Set(recordIds).size!==recordIds.length||recordIds.some(v=>!validResearchId(v)))fail('RESEARCH_SELECTION','请选择一到两条不同的候选视频。');if(!await visible(recordIds))fail('RESEARCH_HIDDEN','所选候选已隐藏或在回收站，请重新查看。',409);const result=await store.transaction(state=>{const job=state.jobs.find(j=>j.jobId===jobId),plan=state.plans.find(p=>p.planId===job.planId);if(!plan||plan.planRevision!==planRevision||job.planRevision!==planRevision)fail('RESEARCH_STALE','理解卡已变化，旧候选确认无效。',409);if(typeof candidateSetHash!=='string'||candidateSetHash!==job.candidateSetHash)fail('RESEARCH_CANDIDATES_STALE','候选列表已变化，请刷新后重新选择。',409);if(recordIds.some(id=>!job.candidates?.some(c=>c.recordId===id)))fail('RESEARCH_SELECTION','所选视频不在这次候选列表中。',409);const selectionKey=hash([jobId,planRevision,candidateSetHash,[...recordIds].sort()]);if(job.selectionKey){if(job.selectionKey===selectionKey)return{jobId,job,duplicate:true};fail('RESEARCH_SELECTION_LOCKED','这次选择已开始处理，不能替换已确认视频；请新建研究。',409);}if(job.cancelRequested||job.phase!=='waiting_selection')fail('RESEARCH_SELECTION_STATE','此任务当前不在等待选择阶段。',409);job.selectionKey=selectionKey;job.selectedRecordIds=job.candidates.filter(c=>recordIds.includes(c.recordId)).map(c=>c.recordId);job.videos=job.selectedRecordIds.map(recordId=>({recordId,stage:'selected',status:'pending'}));job.selectionConfirmedAt=now();job.selectionConfirmedBy='user-ui';job.phase='selection_confirmed';job.executionOwnerPid=process.pid;job.updatedAt=now();job.noteZh='已确认所选视频，开始深拆；没有重新采集账号列表。';job.events.push({phase:'selection_confirmed',at:now(),detail:{count:recordIds.length}});return{jobId,job,duplicate:false};});if(!result.duplicate)schedule();return{...result,job:await publicJob(result.job)};},
  async resumeUnstarted({jobId,planRevision}={}){
   await ready();const current=await service.getJob({jobId});
   const result=await store.transaction(state=>{
    const job=state.jobs.find(item=>item.jobId===jobId),plan=state.plans.find(item=>item.planId===job.planId);
    if(!plan||plan.planRevision!==planRevision||job.planRevision!==planRevision||plan.planHash!==job.confirmedPlanHash||job.plan.planHash!==job.confirmedPlanHash)fail('RESEARCH_STALE','研究版本或确认内容已变化，不能继续旧步骤。',409);
    if(job.cancelRequested||job.phase==='cancelled')fail('RESEARCH_CANCELLED','任务已取消，不能继续。',409);
    if(job.resumeUnstarted)return{jobId,job,duplicate:true};
    if(job.phase!=='partial'||job.plan.executionMode!=='account-study'||job.analysisGate?.status!=='blocked'||job.plan.budgetScope.firstVideoGate!==true)fail('RESEARCH_RESUME_STATE','仅可继续首条画面门禁阻塞的原任务。',409);
    const firstRecordId=job.selectedRecordIds[0],first=job.results.find(item=>item.recordId===firstRecordId)?.result;
    if(!first||!(first.steps?.vl?.status==='completed'||first.steps?.vl?.status==='received'&&first.error?.code==='RESEARCH_OUTPUT'))fail('RESEARCH_RESUME_STATE','首条缺少可免费恢复的已接收视觉响应；不会重发收费请求。',409);
    const remaining=job.selectedRecordIds.slice(1);
    if(remaining.some(recordId=>job.results.some(item=>item.recordId===recordId)||!job.videos.some(video=>video.recordId===recordId&&['blocked','pending'].includes(video.status))||job.events.some(event=>event.detail?.recordId===recordId&&event.detail?.status==='requesting')))fail('RESEARCH_RESUME_STARTED','后续视频已存在请求或结果，不能通过此入口重跑。',409);
    job.resumeUnstarted={firstRecordId,remainingRecordIds:remaining,planRevision,confirmedPlanHash:job.confirmedPlanHash,requestedAt:now(),requestedBy:'user-ui',policy:'first-cache-only-remaining-never-requested'};
    for(const video of job.videos)if(remaining.includes(video.recordId)){video.status='pending';video.stage='selected';delete video.reasonZh;}
    job.phase='selection_confirmed';job.executionOwnerPid=process.pid;job.updatedAt=now();delete job.completedAt;job.noteZh='先免费读取首条已有响应；只有恢复成功，才继续本次尚未开始的视频。';job.events.push({phase:'resume_unstarted_confirmed',at:now(),detail:{firstRecordId,remainingCount:remaining.length,paidRetries:0}});
    return{jobId,job,duplicate:false};
   });
   if(!result.duplicate)schedule();return{...result,job:await publicJob(result.job)};
  },
  async readByRecord({recordId}={},scope={}){await ready();id(recordId,'视频');const snapshot=await history.snapshot({view:'all'}),record=snapshot.records.find(r=>r.id===recordId);if(record&&(record.hidden||record.trashedAt))fail('RESEARCH_HIDDEN','视频已隐藏或在回收站，请先恢复后查看。',409);if(!record)return{status:'not-started',recordId,libraryUpdated:false};const state=await store.read();for(const job of [...state.jobs].reverse()){if(scope.sessionId&&(job.sessionId!==scope.sessionId||scope.workbenchId&&job.workbenchId!==scope.workbenchId))continue;const item=job.results.find(r=>r.recordId===recordId);if(!item)continue;await checkJob(job,scope);const status=item.result.status==='completed'&&hasVisualEvidence(item.result)?'completed':'partial';return clone({status,recordId,result:item.result,intent:job.plan.userIntent,jobId:job.jobId,planId:job.planId,planRevision:job.planRevision,libraryUpdated:false});}return{status:'not-started',recordId,libraryUpdated:false};},
  async listPlans({topicId,sessionId}={},scope={}){await ready();const state=await store.read(),wantedSession=scope.sessionId||sessionId;const plans=[];for(const plan of state.plans){if(topicId&&plan.topicId!==topicId&&plan.resolvedTopicId!==topicId||wantedSession&&plan.sessionId!==wantedSession)continue;try{await checkPlan(plan,scope);plans.push(plan);}catch(error){if(![403,404,409].includes(error.status))throw error;}}
   const jobs=[];for(const job of state.jobs){if(topicId&&job.topicId!==topicId||wantedSession&&job.sessionId!==wantedSession)continue;try{jobs.push(await publicJob(job,scope));}catch(error){if(![403,404,409].includes(error.status))throw error;}}
   const styles=[];for(const style of state.styles)if((!topicId||style.topicId===topicId)&&await visible(style.recordIds))styles.push(style);return clone({plans:plans.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),jobs:jobs.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),styles});
  },
  async topicContext({topicId,sessionId}={},scope={}){await ready();const snap=await active(),topic=topicId?snap.topics.find(t=>t.id===topicId):null;if(topicId&&!topic)fail('RESEARCH_TOPIC','专题不存在或已无可见资料。',404);const records=topic?snap.records.filter(r=>topic.recordIds.includes(r.id)):[];return{topic,topics:topic?undefined:snap.topics,records,...await service.listPlans({topicId,sessionId},scope)};},
  async confirmStyle({jobId,candidateId,nameZh}={}){const job=await service.getJob({jobId}),candidate=job.styleCandidates.find(c=>c.candidateId===id(candidateId,'风格候选'));if(!candidate)fail('RESEARCH_STYLE','风格候选不存在。',404);if(!job.topicId)fail('RESEARCH_TOPIC','请先把研究关联到品牌或专题。',409);if(!await visible(candidate.recordIds))fail('RESEARCH_HIDDEN','候选证据已隐藏或在回收站。',409);return store.transaction(state=>{const old=state.styles.find(s=>s.sourceJobId===jobId&&s.candidateId===candidateId);if(old)return{style:old,duplicate:true};const name=text(nameZh,120)||candidate.nameZh,style={styleVersionId:'style_'+randomUUID(),version:1,nameZh:name,topicId:job.topicId,sourceJobId:jobId,candidateId,recordIds:candidate.recordIds,recommendation:clone(candidate.recommendation),comparisonRecommendation:clone(candidate.comparisonRecommendation||null),recreationPackage:clone(candidate.recreationPackage??(candidate.recordIds.length===1?job.results.find(item=>item.recordId===candidate.recordIds[0])?.result?.recreationPackage:null)??null),status:'user-confirmed',confirmedAt:now(),sourcePlanRevision:job.planRevision,immutable:true,evidenceStatus:'user-adopted-not-outcome-verified'};state.styles.push(style);return{style,duplicate:false};});},
  async cancelJob({jobId}={}){await service.getJob({jobId});return updateJob(jobId,job=>{if(terminal.has(job.phase))return;job.cancelRequested=true;job.events.push({phase:'cancellation_requested',at:now(),detail:{message:'尚未发起的步骤将停止；已送达供应商的请求可能已计费。'}});if(['confirmed','waiting_selection','selection_confirmed'].includes(job.phase)){job.phase='cancelled';job.completedAt=now();}});},
  async waitForIdle(jobId){await ready();while(runtime.running)await runtime.running;return jobId?service.getJob({jobId}):undefined;}
 };
 service.readTopicContext=service.topicContext;
 service.handlers=createResearchHandlers({service,isAllowed});return service;
}
const respond=(value,status=200)=>Response.json(value,{status,headers:{'cache-control':'no-store','x-content-type-options':'nosniff'}});
async function limitedJson(request){const max=64*1024,reader=request.body?.getReader();if(!reader)fail('RESEARCH_BODY','请求内容为空。');let bytes=0,raw='';const decoder=new TextDecoder();try{while(true){const {value,done}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>max){await reader.cancel();fail('RESEARCH_BODY','请求内容超过 64 KB。',413);}raw+=decoder.decode(value,{stream:true});}raw+=decoder.decode();}finally{reader.releaseLock();}try{const value=JSON.parse(raw);if(!obj(value))throw Error();return value;}catch{fail('RESEARCH_BODY','请求 JSON 格式无效。');}}
export function createResearchHandlers({service,isAllowed=sameOrigin}={}){
 async function handle(request,method,fn){if(request.method!==method)return respond({error:'此接口不支持该请求方式。'},405);if(!await isAllowed(request)||method==='POST'&&request.headers.get('x-derek-workbench')!=='1')return respond({error:'请求来源校验失败。'},403);try{return respond(await fn(method==='POST'?await limitedJson(request):new URL(request.url)));}catch(error){const status=[400,403,404,409,413].includes(error?.status)?error.status:500;return respond({error:status===500?'研究操作未完成；原记录保留，没有自动重试。':error.message,code:error?.code?.startsWith('RESEARCH_')?error.code:undefined},status);}}
 return{resumeUnstarted:request=>handle(request,'POST',body=>service.resumeUnstarted(body)),start:request=>handle(request,'POST',body=>service.startResearch(body)),plans:request=>request.method==='GET'?handle(request,'GET',u=>u.searchParams.has('planId')?service.getPlan({planId:u.searchParams.get('planId')}):service.listPlans({topicId:u.searchParams.get('topicId')||undefined,sessionId:u.searchParams.get('sessionId')||undefined})):handle(request,'POST',body=>service.preparePlan(body)),confirm:request=>handle(request,'POST',body=>service.confirmPlan(body)),select:request=>handle(request,'POST',body=>service.selectCandidates(body)),job:request=>handle(request,'GET',u=>service.getJob({jobId:u.searchParams.get('jobId')})),result:request=>handle(request,'GET',u=>service.readResult({jobId:u.searchParams.get('jobId')})),recordResult:request=>handle(request,'GET',u=>service.readByRecord({recordId:u.searchParams.get('recordId')})),context:request=>handle(request,'GET',u=>service.topicContext({topicId:u.searchParams.get('topicId')||undefined,sessionId:u.searchParams.get('sessionId')||undefined})),confirmStyle:request=>handle(request,'POST',body=>service.confirmStyle(body)),cancel:request=>handle(request,'POST',body=>service.cancelJob(body))};
}
export function applyResearchService(ctx,{service,prefix='/api/derek-video-replicate/research',...options}={}){
 let prefixes=installed.get(ctx);if(!prefixes){prefixes=new Set();installed.set(ctx,prefixes);}if(prefixes.has(prefix))return service;service??=createResearchService(options);const h=service.handlers;for(const [suffix,methods,fetch]of[['/resume-unstarted',['POST'],h.resumeUnstarted],['/start',['POST'],h.start],['/plans',['GET','POST'],h.plans],['/confirm',['POST'],h.confirm],['/select',['POST'],h.select],['/jobs',['GET'],h.job],['/result',['GET'],h.result],['/record-result',['GET'],h.recordResult],['/context',['GET'],h.context],['/styles/confirm',['POST'],h.confirmStyle],['/cancel',['POST'],h.cancel]])ctx.connection.fetch.register({path:prefix+suffix,methods,requestBody:'buffered',fetch});prefixes.add(prefix);return service;
}
